CircuitPython_Essentials/CircuitPython_AnalogIn.py
CircuitPython_Essentials/CircuitPython_AnalogOut.py
CircuitPython_Essentials/CircuitPython_CapTouch.py
CircuitPython_Essentials/CircuitPython_CapTouch_2Pins.py
CircuitPython_Essentials/CircuitPython_Digital_In_Out.py
CircuitPython_Essentials/CircuitPython_DotStar.py
CircuitPython_Essentials/CircuitPython_HIDKeyboard.py
CircuitPython_Essentials/CircuitPython_I2C.py
CircuitPython_Essentials/CircuitPython_I2C_Scan.py
CircuitPython_Essentials/CircuitPython_Internal_RGB_LED_colors.py
CircuitPython_Essentials/CircuitPython_Internal_RGB_LED_rainbow.py
CircuitPython_Essentials/CircuitPython_Logger.py
CircuitPython_Essentials/CircuitPython_Logger_Boot.py
CircuitPython_Essentials/CircuitPython_NeoPixel.py
CircuitPython_Essentials/CircuitPython_NeoPixel_RGBW.py
CircuitPython_Essentials/CircuitPython_PWM.py
CircuitPython_Essentials/CircuitPython_PWM_Piezo.py
CircuitPython_Essentials/CircuitPython_PWM_Piezo_simpleio.py
CircuitPython_Essentials/CircuitPython_Servo.py
CircuitPython_Essentials/CircuitPython_UART.py
CircuitPython_Essentials/PWM_Test_Script.py
CircuitPython_Essentials/SPI_Test_Script.py
CircuitPython_Essentials/UART_Test_Script.py

Changing the directory name to match the guide title. At the time that we started unifying the quick starts, we hadn't decided to create a separate guide for them. Now that we have one, the directory structure should match the guide name. I will be updating all the links in the guide before removing the other directory. All further working examples will be pushed to this directory.

CircuitPython Essentials examples

---

ROB_Control/code.py

CircuitPython code to run on the Adafruit Circuit Playground Express to control the Nintendo R.O.B. robot from 1985 using the CPX IR LED, accelerometer, and buttons to activate various functions.
This code is explained in the guide Controlling a Classic Nintendo R.O.B. Robot Using Circuit Playground Express at https://learn.adafruit.com/
Support cool hacks by buying Open Source Hardware at Adafruit.com

Code for CircuitPython for Nintendo R.O.B.

---

CircuitPython_Made_Easy_On_CPX/cpx_sound_meter.py
Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_SoundMeter.py

Incompatible change made in `PDMIn()` constructor: keyword arg changed from `frequency` to `sample_rate`. Include both in sample code. (FYI see https://github.com/adafruit/circuitpython/issues/881)

add notes for PDMIn name change of frequency to sample_rate

---

CircuitPython_Made_Easy_On_CPX/cpx_play_file.py
CircuitPython_Made_Easy_On_CPX/cpx_play_file_buttons.py

The file name originally had a space in it (it shipped on CPX when CPX shipped with CircuitPython). When uploaded to the Learn System via "media", the system automatically replaced the space with an underscore rendering the code incorrect. Updated code to match Learn system upload.

Updated filename to match Learn system media upload change

---

Arcade_Button_Control_Box/Arcade_Button_Control_Box.py

Arcade button example was importing specific pins, including `board.D13`, which wasn't used. A user in Discord said mu complained about this, and it was kind of confusing. Changed to `import board` and just use pins.
Now if example is edited, import list does not need to be changed.

don't import specific pins

---

Introducing_CircuitPlaygroundExpress/Playground_808.py

The code sample (as it was) when run on my new adfruit circuitboard playground express was throwing an error
```
Traceback (most recent call last):
File "main.py", line 43, in <module>
File "main.py", line 34, in play_file
TypeError: extra positional arguments given
```
Line 34 was:
```
a = audioio.AudioOut(board.A0, f)
```
It looks as if audioio.AudioOut has been changed to only accept one arg
Inspiration for this PR was found at:
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/CircuitPython_Essentials/CircuitPython_Audio_Out_Wave.py

fixing audioio.AudioOut which now seems to have only one param

---

Adafruit_UDA1334A/CircuitPython_I2S_Tone.py

Changed the array type to allow I2S signed values. Eliminated the baseline in the ``math.sin`` portion of the code. Updated the calculated value range to represent a maximum value of 32767 rather than 32678 to avoid distortion caused by value wrap-around.
The outcome is that the audio signal is now centered around the baseline (zero), allowing for double the dynamic range without distortion. Also changed the full-scale value to +/- 32767 to further reduce potential distortion.
Tested using CircuitPython 3.0.0 on a Feather M0 Express.

Accomodate the zero baseline, reduce distortion

---

CircuitPython_Essentials/CircuitPython_Servo.py
Combo_Dial_Safe/main.py

Replacing `simpleio`'s servo helper with `adafruit_motor`'s servo helper. 
Issue: https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO/issues/33
**Learn Guide Pages Affected by this change:**
- https://learn.adafruit.com/circuitpython-essentials/circuitpython-servo, Tested on Feather M4, SG92R Servo.
- https://learn.adafruit.com/combo-dial-safe-with-circuit-playground-express/code-with-circuitpython#download-the-combo-dial-python-code-3-5, Tested on CPX, SG92R Servo.

Replace SimpleIO servo with Adafruit_Motor Servo

---

Circuit_Playground_Jack_o_Lantern/JackOLantern_CircuitPlayground.ino
Circuit_Playground_Jack_o_Lantern/JackOLantern_HalloWing.ino
Circuit_Playground_Jack_o_Lantern/jack_o_lantern_circuit_playground.py
Circuit_Playground_Jack_o_Lantern/jack_o_lantern_hallowing.py

Previously standalone code in guide; move to repo for embed, add Hallowing variants.

Add Jack-o'-Lantern code

---

IO_House_Series/Lights_and_Temp/io_house_light_temp.py

Switching from manually importing https://github.com/rpi-ws281x/rpi-ws281x-python to our adafruit_circuitpython_neopixel library, since it works on RasPi now. Setup page on the guide has been switched over to reflect this change.

IO Home #1: Switch to adafruit_circuitpython_neopixel library

---

TheThingsNetwork_Feather/tinylora_dht22_decoder.js
TheThingsNetwork_Feather/tinylora_hello_decoder.js
TheThingsNetwork_Feather/ttn_lmic_dht22_decoder.js

Adding two TTN payload decoder scripts (for TinyLoRa) to embed in the 'Using Feather 32u4' pages. 
Renaming original decoder (for LMIC) to avoid confusion.

add decoder scripts for TinyLoRa Guide

---

NeoTrellis_M4_Sound_Board/code.py

Star Trek was one of the first color television shows so they had a very primary palette of colors. Changed intro swirl to RED, GREEN, BLUE as Limor asked that the pastel colors be more Star Trek.
Dano should test this - if it isn't enough Trek, maybe a different animation?

Update startup colors to be more primary

---

CircuitPython_Made_Easy_On_CPX/cpx_red_led.py

Hi,
This change keeps the red led turned on. Currently, without while loop, the led is only turned on for a fraction of a second and is turned off once the program ends.
[If this is merged, I guess you would also need to move the description of the while loop into the first paragraph, i.e. from "Blinky" to "Red LED": https://learn.adafruit.com/circuitpython-made-easy-on-circuit-playground-express/red-led]

Update cpx_red_led.py (and guidelines)

---

home-assistant-io/feather_bme280.yaml

Correcting IO feed path to resolve error: `[12:42:53](Message skipped because it was too big to fit in TCP buffer - This is only cosmetic)`

Fix Home Assistant YAML

---

BLE_Crickit_Light_Switch/ble_crickit_light_switch.py

This simplifies the code, removing `advertising_now` and removing moving the server one degree at a time. That code was there from the CircusPython to move the servo more slowly and to call `sparkle()` as continuously as possible. It's not necessary here.
The Learn Guide will need a tiny update to remove the sentence saying the servo is moved one degree at a time.

simplify ble_crickit_light_switch.py

---

Grand_Central_MIDI_Knobs/Grand_Central_MIDI_Knobs.py

Flag no longer used in this version or Range_Index. It was left over from the RetroMeter code and was used to beep/flash when index values change.

Remove Range_Index artifact

---

PyPortal_Smart_Thermometer/thermometer_helper.py

adding `/` and `space` characters to glyph string

Fix PyPortal Thermostat Font Preloading

---

Magic_Nine_Ball/magic_nine_ball.py

Was using `Sprite` instead of `TileGrid`.
Now use builtin `brightness` control.
I'm seeing flickering when the brightness gets near 1.0, but I think that's an issue unrelated to this code, and probably needs to be fixed elsewhere.

Update display and brightness code in Magic_Nine_Ball

---

PyPortal_Word_of_the_Day/code.py

- Was able to add a feature to switch between a word's definition and an example sentence. 
- Only error I can't remove from pylint is:
`Access to a protected member _json_path of a client class (protected-access)`

Add example feature

---

EInk_Weather_Station/adafruit_epd_weather/adafruit_epd_weather.ino

Increased moonphasenames from [28] to [29] to include the last day before a new moon and avoid an out-of-bounds error causing sketch to crash. This commit also clean ups mixed end of line feeds, which may explain the issue of the display not properly showing the changed diffs in GitHub.

Fix out-of-bounds error with moonphasenames array

---

lorawan_sensing_network/lora_device.py
lorawan_sensing_network/lora_gateway.py

re: https://forums.adafruit.com/viewtopic.php?f=57&t=153641
`pres_val = 101275` won't fit in 2 bytes, increasing size of bytearray to fit `pres_val`. Third byte handled in the gateway's `pkt_int_to_float` method as an optional kwarg

fixed drop byte in Feather/Pi LoRa Weather Monitor

---

PyPortal_Calculator/calculator.py

This fixes a couple bugs like entering: `9 + 23 % =` and `9 + -23 =` were yielding wrong results.

Last minute bug fixes

---

Adafruit_Prop_Maker_FeatherWing/Prop_Maker_Accelerometer_Simpletest.py

The interrupt is hooked to D6, not D5.

Fix Interrupt pin number

---

PyPortal_AdafruitIO_Logger/pyportal_adafruit_io_logger.py
PyPortal_IOT_Scale/pyportal_scale.py
PyPortal_Smart_Thermometer/thermometer.py
pyportal_weather_station/code.py

The Adafruit IO CircuitPython module's latest release changes a class name, `RESTCLIENT` to `IO_HTTP`. This PR adds the appropriate substitutions to Learning System Guides which use this module.
https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/releases/tag/2.0.0

Update Adafruit IO CircuitPython Examples for breaking v2.0

---

Matrix_7-Segment_LED_Backpack_Raspberry_Pi/alphanum4_test.py
Matrix_7-Segment_LED_Backpack_Raspberry_Pi/bicolor24_test.py
Matrix_7-Segment_LED_Backpack_Raspberry_Pi/matrix8x8_test.py
Matrix_7-Segment_LED_Backpack_Raspberry_Pi/matrix_bicolor_test.py

Merged code examples from original LED_Backpack and HT16K33. Deprecating LED Backpack Display on Raspberry Pi and BeagleBone Black guide in favor of Matrix and 7-Segement LED Backpack with the Raspberry Pi guide.

Matrix 7 segment led backpack merge

---

Pi_Hole_Ad_Blocker/stats.py

Lots of people running this 24/7 and ruining their OLEDs. This adds a simple screen blanking so the display is only on for a short period of time.

Add simple screen blanking for PiHole stats

---

Adafruit_ESP32_Arduino_Demos/SerialESPPassthrough/SerialESPPassthrough.ino

Updating ESP32 Serial Passthrough sketch to reflect supported boards (https://github.com/adafruit/WiFiNINA/blob/master/examples/JSONdemo/JSONdemo.ino#L21)

Update ESP32 Serial Passthrough for more boards

---

M4_Eyes/user_touchneopixels.cpp

Frame rendering dropped precipitously on Hallowing M4 upon updating to adafruit/master user_touchneopixels.cpp (from 29 to 13 fps). I traced the issue to the Arcada capacitive touch button sampling. This patch simply reduces the number of times the buttons are read. This may make them a bit more finicky but that'd be my preference given the trade-off.
FPS still starts slow but eventually does reach 29 again.

Reduced cap touch sampling to fix performance

---

PyPortal_Smart_Thermometer/thermometer_helper.py

fixes #891 
remove unnecessary appends and calls to refresh_soon and wait_for_frame
tested on CP4.10. and CP5.0alpha-4

revise PyPortal_Smart_Thermometer thermometer_helper.py 

---

CircusPython_BLE/circus.py

First redone Learn Guide code for new BLE API. Program structure somewhat simplified.
@tannewt adding you in case you have general BLE-use style suggestions. We might think about some helper functions (like making advertising simpler).
Tested on my CircusPython rig with current Bluefruit app.

CircusPython_BLE: update for CircuitPython 5.0.0-beta.0

---

NeoPixel_Badge_Lanyard/code.py

Edited BLE part of code to match new CircuitPython 5.0.0-beta.0.
Tested with a NeoPixel strip. This updates the code in two Learn Guides:
- [CircuitPython BLE Controlled NeoPixel Hat](https://learn.adafruit.com/circuitpython-feather-ble-neopixel-hat)
- [NeoPixel Badge Lanyard with Bluetooth LE
](https://learn.adafruit.com/bluetooth-neopixel-badge-lanyard)

update NeoPixel_Badge_Lanyard BLE code

---

BLE_CPB_Color_Picker/ble_color_picker.py

https://learn.adafruit.com/cpx-cauldron was pointing to the library example for a color picker. Copy that code to this repo and update it for CircuitPython 5.0.0-beta.0.
Tested on a CPB.

Add Learn Guide version of updated BLE color picker

---

Getting_Started_With_BLE_and_CP/button_presses.py
Getting_Started_With_BLE_and_CP/color_picker.py
Getting_Started_With_BLE_and_CP/location.py
Getting_Started_With_BLE_and_CP/mobile_movement_data_streams.py

update BLE Getting Started for CircuitPython 5.0.0-beta.0 BLE API changes

---

Snow_Globe_BLE_CPB/ble_snowglobe.py

Updated for new API
revised the way advertising is started/restarted  to avoid errors
also set the  default shake threshold to 20 ( was 27 and hard to get it to respond)
Tested on CPB

Update Snow_Globe_BLE_CPB for CP 5.0 Beta _bleio

---

pi_radio/rfm69_check.py
pi_radio/rfm9x_check.py

Print error messages for RFM69/RFM9x test scripts to the terminal to help with debugging.
https://forums.adafruit.com/viewtopic.php?f=50&t=159573&p=785930#p785930

Print RFMx RuntimeError messages

---

Jupyter_USB/LSM6DSOX_Accel.ipynb

Updated to reflect the name change of the LSM6DSOX library. Tested with a FT232H

Updated for LSM6DSOX->LSM6DS rename

---

ItsyBitsy_Infinity_Mirror/code.py

code for Infinity Mirror Coaster

code for Infinity Mirror Coaster

---

PyPortal_User_Interface/code.py

All of the spaces added to string text after ``\`` was carried over to the display.

Fixing string text spacing issue.

---

README.md

Currently clicking the build badge just takes you to the badge image. This commit fixes it to link to the builds page on Travis

Fixing build badge link

---

CircuitStonks/code.py

I kept getting an ```SCK in use ``` error when using busio.SPI(.....)
this change makes it work for me.
Tested on feather_bluefruit_sense with airlift_featherwing and minitft_featherwing.
Same issue with feather_nrf52840_express.

use board.SPI() in circuitstonks demo

---

BLE_Vibration_Bracelet/code.py.py

Adding code for BLE vibration bracelet Learn Guide. 
- Uses ANCS to receive notifications with a Feather nRF52840
- Onboard NeoPixel lights up a specific color depending on the app and also vibrates. 
- NeoPixel lights up blue and vibrates on the hour for mindfulness

code for BLE vibration bracelet

---

CircuitPython_RGBMatrix/fruit.py

The tile width setting was lost when I simplified the demo for inclusion in the guide.  Restore it.

RGBMatrix: fruit demo: fix ValueError exception

---

FONA_SMS_Sensor/code.py

Updating FONA SMS sensor guide for FONA library v2.0.0 update
https://learn.adafruit.com/textable-sensor-with-fona-and-circuitpython/code-walkthrough

Update FONA SMS Sensor for FONA Library Update

---

PyPortal_AWS_IOT_Planter/code.py
PyPortal_GCP_IOT_Planter/code.py
pyportal_pet_planter/code.py

Addresses https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/40
This pull request:
* Changes import statements in MiniMQTT code examples to reflect the library's modified path in release `3.1.0`
* Updated https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1122, excluded from this PR

Fix import path in MiniMQTT examples

---

CircuitPython_Essentials/CircuitPython_Audio_Out_MP3.py

A new page in the CircuitPython Essentials guide will explain how to use MP3 playback on supported devices.  This is the code sample/example.

Add MP3 code sample to Essentials guide

---

ulab_Crunch_Numbers_Fast/waterfall.py

At one time, ulab's min and max had a bug where they returned an array with a single item inside.  This bug has been fixed (by 5.3.0 if not earlier) so remove the workaround.
Reported by @firepixie, thanks!

ulab: correct waterfall demo

---

CircuitPython_Essentials/CircuitPython_I2C_Scan.py
CircuitPython_Essentials/CircuitPython_I2C_TSL2561.py

A user in discord was confused by this example code vs some newer code that used `board.I2C()`. Change the simple examples to use `board.I2C()`. Once this is changed the page text will be updated.

Change CircuitPython Essentials examples to use board.I2C()

---

MIDI_Solenoid_Drum_Kit/code.py

Adding code for the MIDI solenoid drum kit Learn Guide.
When a MIDI note (60, 61, 62 or 63) is received, a solenoid strikes.

Adding code for MIDI Solenoid Drum Kit

---

CircuitPython_SharpDisplay_Displayio/code.py

The other sample code snippets use D6, so this code should too even if I was testing with D2 on a Particle Xenon.

Change chip select pin to D6 to match other samples

---

CircuitPython_SharpDisplay_Displayio/code.py

Between adafruit_display_text release 2.8.0 on July 24 and the current version, the behavior of specifying just x/y changed.  The same code works with both versions if anchor_point / anchored_position is specified, so go with that even though it's a bit more verbose

SharpDisplay demo: Always use anchor_point/anchored_position

---

EInk_Bonnet_Event_Calendar/event_calendar.py
EInk_Bonnet_Weather_Station/weather.py

After trying out the examples on the real eInk bonnet, I think these should be changed.

Fixed rotation for real eInk bonnet

---

NeoPixel_Gemma_Torch/code.py

adding neopixel gemma torch code. Ran pylint on code.py using following version:
pylint 2.4.3
astroid 2.3.2
Python 3.7.4
************* Module code
code.py:1:0: C0114: Missing module docstring (missing-module-docstring)
code.py:1:0: E0401: Unable to import 'board' (import-error)
code.py:2:0: E0401: Unable to import 'neopixel' (import-error)
code.py:3:0: E0401: Unable to import 'adafruit_dotstar' (import-error)
--------------------------------------------------------------------
Your code has been rated at -0.67/10 (previous run: -0.67/10, +0.00) 
Safe to ignoring the rating since they're just import errors?

neopixel gemma torch code

---

PyGamer_Thermal_Camera/code.py

The pybadger library was updated and this code needs to change to reflect the newer versions. As it is now this code crashes with the current version of the PyBadger library.
This PR updates the import, removes the initializer and sets the pixel brightness directly. These are the changes needed for the newer versions of that library. 
I don't have the thermal camera so I can't test the full project but I did run this code on a PyGamer and it does now get past all of th errors related to the PyBadger library.

Fix PyGamer Thermal camera

---

.github/workflows/githubci.yml

Python 3.9 has issue with intelhex, https://github.com/python-intelhex/intelhex/issues/45.
While waiting for Intellihex, CI script updated to match https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/171
Affected PR's, will need to re-run after this is approved and merged in: https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1268

Fix CI for nrf52832/cpb

---

lorawan_sensing_network/lora_device.py

**What Changed**
This change simply changes the payload in `rfm9x.send()` to the expected argument, `bme280_data_bytes`. @brentru 
This fixes #1281 
**Tests**
No matching test suites were found, but I did look at the source code and noticed that it is, in fact, expecting some bytes. See [here](https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/blob/6590c91a9146f41a7984a52febce9b21d0df8748/adafruit_rfm9x.py#L599)

Update payload variable in send function

---

Adafruit_IO_Air_Quality/code.py

Adding optional initialization for an alternate build using the pmsa003l and bme680.
Generalizes language/methods for BME sensors types.
Fixes incorrect value being returned by `read_bme`
Tested on:
Feather M4 + AirLift Featherwing + BME280 + PMS5003
and
Feather M4 + AirLift Featherwing + BME680 + pmsa003l

Update Air Quality Sensor to support pmsa003l and BME680

---

FeatherCAN_CircuitPython/listener-ack.py
FeatherCAN_CircuitPython/listener.py
FeatherCAN_CircuitPython/sender-ack.py
FeatherCAN_CircuitPython/sender.py

.. because I was testing on a board _without_ `BOOST_STANDBY` I did not initially notice this problem.

fix BOOST_STANDBY pin handling

---

ESP32_S2_WiFi_Tests/code.py

Fixed up a few visual things I noticed while playing around with the WiFi examples on my UnexpectedMaker FeatherS2 board.
Just a typo for "Available" and a double-wrapped `print()` statement that caused the terminal to print the text as well as a line just containing `None`.

Cleaning up a few things in the WiFi test example

---

MagTag_CountdownCelebration/code.py

Date parsing failed for time zones with positive offsets, like Europe/Stockholm. 
I rewrote the parsing to use substrings instead of split. Also, the text was off screen in the Y direction, so I moved it down to be visible.

Fix date time parsing + Y offset

---

Matrix_Portal_Moon_Clock/code.py

Introduce 'MONTH_DAY = True' that default to MM/DD but permit DD/MM when set to False
The default value keep the current behaviour.
While the learn guide could be updated to take into account this new option, it is not mandatory and does not disturb what is shown in the guide.

moon-phase-clock-for-adafruit-matrixportal: support DD/MM

---

Stream_Deck_Message_Panel/MessagePanel/MessagePanel.ino

- This commit corrects a comment the author explaining if they want to use the Metro Airlift M0 or M4, and so forth.
- There aren't breaking changes in this pull request. It just corrects a typo in the spelling.
- Tests should correctly pass because of a minor correction in the comments of the file in question.

Fix a minor typo in the documentation

---

Pi_Hole_Ad_Blocker/stats.py

Space after IP, before parenthesis looks more correct.
Before:
```
192.168.1.2( pi-hole)
```
After:
```
192.168.1.2 (pi-hole)
```

Minor formatting change in stats.py

---

MagTag_Progress_Displays/year_progress_percent.py

I noticed the example code in the MagTag Year Progress demo uses an incorrect check for leap years. I for one hope both Adafruit and my MagTag are still working in the year 2100, so let's fix the check to account for years that are multiples of 100 and/or 400. 
I chose the order of the conditional checks based on the discussion in the the Answer 12 comment here: https://www.mmbyte.com/article/8959.html .

Include the 100/400 year check for leap years in MagTag Year Progress demo

---

CircuitPython_Essentials/CircuitPython_AnalogIn.py
CircuitPython_Essentials/CircuitPython_AnalogOut.py
CircuitPython_Essentials/CircuitPython_Audio_Out_MP3.py
CircuitPython_Essentials/CircuitPython_Audio_Out_Tone.py
CircuitPython_Essentials/CircuitPython_Audio_Out_Wave.py
CircuitPython_Essentials/CircuitPython_CapTouch.py
CircuitPython_Essentials/CircuitPython_CapTouch_2Pins.py
CircuitPython_Essentials/CircuitPython_Continuous_Servo.py
CircuitPython_Essentials/CircuitPython_Digital_In_Out.py
CircuitPython_Essentials/CircuitPython_DotStar.py
CircuitPython_Essentials/CircuitPython_HID_Keyboard.py
CircuitPython_Essentials/CircuitPython_HID_Mouse.py
CircuitPython_Essentials/CircuitPython_I2C_Scan.py
CircuitPython_Essentials/CircuitPython_I2C_TSL2591.py
CircuitPython_Essentials/CircuitPython_Internal_RGB_LED_colors.py
CircuitPython_Essentials/CircuitPython_Internal_RGB_LED_rainbow.py
CircuitPython_Essentials/CircuitPython_Logger.py
CircuitPython_Essentials/CircuitPython_Logger_Boot.py
CircuitPython_Essentials/CircuitPython_NeoPixel.py
CircuitPython_Essentials/CircuitPython_NeoPixel_RGBW.py
CircuitPython_Essentials/CircuitPython_PWM.py
CircuitPython_Essentials/CircuitPython_PWM_Piezo.py
CircuitPython_Essentials/CircuitPython_PWM_Piezo_simpleio.py
CircuitPython_Essentials/CircuitPython_Servo.py
CircuitPython_Essentials/CircuitPython_UART.py
CircuitPython_Essentials/I2C_Test_Script.py
CircuitPython_Essentials/PWM_Test_Script.py
CircuitPython_Essentials/SPI_Test_Script.py
CircuitPython_Essentials/UART_Test_Script.py

Added docstrings to all the files and did a bit of cleanup as well.
Guide is already updated.

Updating Essentials guide to include QT Py.

---

MagTag_Weather/magtag_weather.py

Minor typo in the `MONTHS` tuple element for August.

Bugfix: Typo in months for `magtag_weather.py`

---

Welcome_to_CircuitPython/QT_Py_blink.py

Significant amount of feedback on the QT Py guide about the blink example not working on QT Py, and requests to resolve it. As this is a due to a hardware limitation, there is no easy resolution to using the exact blink code in the Welcome guide on QT Py. I intend to link to this example on the Creating and Editing Code page of the Welcome to CircuitPython guide, and indicate if you're using QT Py, you can use this example to follow along instead (as the changes suggested are to the `time.sleep()` which is present in both).

Add blink for QT Py.

---

MagTag_Twitter/code.py

Fixes `Http Error: code 401: Authorization Required` caused by multi-line URL split .

Fix MagTag Twitter Example

---

Nunchuck_Ring/nunchuck_ring.py

first commit nunchuck ring code

---

Raspberry_Pi_Braincraft_Radio/setup-kiosk.sh

This reads the important values from /boot/config.txt to determine the rotation and then uses a deque to rotate the arrow keys easily based on the detected rotation.

Lofi radio: Add automatic rotation fix

---

PyPortal_User_Interface/code.py

Updates the PyPortal User Interface code to use the new display_button API which gets rid of the warnings printed.

remove deprecated button api use

---

PyPortal_EZ_Make_Oven/code.py

Fix exception when attempting to access a missing attribute.
The attribute used to be at PyPortal._speaker_enable, but is now
PyPortal.peripherals._speaker_enable.
the code.
strive to not break users of the …

EZ Make: Fixed _speaker_enable.

---

PyPortal_EZ_Make_Oven/codecalibrate.py

Display the following error message if codecalibrate.py
is unable to communicate with the thermocouple amplifier:
No I2C device at address: 0x67
Unable to connect to the thermocouple sensor.
This replaces the standard standard exception stack trace
containing the following message:
ValueError: No I2C device at address: 0x67
Adding the sensor name and eliminating the stack detail should
aid troubleshooting.
the code.
- **Describe any known …

EZ Make cal: Add message upon sensor connection failure.

---

PyPortal_EZ_Make_Oven/code.py

This update fixes the following issues:
- After first reflow and temperature reaches reflow value, oven turns off and starts cool off period instead of entering reflow state
- When stopping a reflow, screen does not clear graph for next reflow
- Reflow oven now waits for cool down temperature of 35 instead of 50 before "ready" state.

EZ Make Oven: fixed issues when reflowing more than once

---

Getting_Started_With_Raspberry_Pi_Pico/data_logger_no_ground_wire_boot.py

Added section at the end that covers removing/renaming boot.py from the REPL to allow for data logging without a ground wire.

Adding shorter boot.py

---

Adafruit_IO_Air_Quality/code.py

Updates code to match updated Adafruit IO CircuitPython library https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/pull/64
Related issue:
https://forums.adafruit.com/viewtopic.php?f=60&t=175772
This can be pulled in after https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/pull/64  is merged and released.

Update Adafruit IO Air Quality Sensor Code

---

Pico_MIDI_Fighter/code.py

Adding CircuitPython code for the Raspberry Pi Pico MIDI Fighter learn guide. Uses 16 arcade buttons to send MIDI note messages. Arcade buttons' LEDs are controlled by the AW9523. Display is the 128x128 greyscale. 5-way switch allows you to navigate the GUI and change MIDI note number assigned to each arcade button on the fly.

Adding CircuitPython code

---

.github/workflows/githubci.yml

The workflow doesn't ask for a specific version of Ubuntu, but when it gets 20.04, ci-arduino causes a failure because it requests installation of a specific version of llvm that is not available in 20.04:
```
E: Version '1:8-3~ubuntu18.04.2' for 'libllvm8' was not found
```
We should decide between this and actually fixing arduino-ci.

workflows: Use 18.04 for arduino-ci

---

CircuitPython_Templates/digital_input.py

My plan here is for template pages that require the author to include code - e.g. it can't be included in the template because there will be board-specific differences - to create example code to work from so there is less effort required in the long run.

Adding digital input template example.

---

Pico_MIDI_Fighter/code.py

Updating integers being pulled for text labels to strings. Throwing an error in the latest release of CP for the Pico.

Updating int to str for Pico MIDI Fighter

---

PyPortal_OpenWeather/openweather_graphics.py

based on guide feedback, increased number of max_glyphs to 9 for time_text 
> When creating the time label the max_glyphs is set to 8. When the time went from 9:59 AM to 10:00 AM, the code threw a warning not enough glyph space for text. After rebooting, the M was loft off time and lower labels did not display. Changing max_glyphs = 9 fixed the problem.

increased max_glyphs to 9 for time_text

---

PowerGlove_BLE_MIDI/code.py

fixed the accelerometer import which changed w 6.0 I think. Also renamed the file to code.py so drag-drop of the bundle doesn't require a rename.

library import fix, renamed to code.py to appease the Bundle Fly

---

Matrix_Portal_Moon_Clock/code.py

Based on Line 283, the LAST_SYNC is in seconds, which means the exception case currently represents 30 hours, not 30 minutes, as the comment indicates it should.

Correct 30 minute calculation in MOON PHASE CLOCK

---

NeoTrinkey_Zoom_Shortcuts/code.py

Adding code for NeoTrinkey Zoom shortcuts. NeoPixels act as visual UI to tell if your mic or camera are muted (red for muted, green for unmuted). Keyboard shortcuts for muting/unmuting are sent by touching either of the two cap touch pads. Holding down both cap touch pads exits the meeting and has the NeoPixels do the rainbow cycle animation

Adding code for NeoTrinkey Zoom shortcuts

---

CircuitPython_Templates/neopixel_blink_one_pixel.py

Multi-pixel boards have their own template, so this can be included in the single-pixel template.

Adding static single-pixel example.

---

FunHouse_HA_Companion/code.py

This is an update to the FunHouse Home Assistant code to reflect the changes made in https://github.com/adafruit/Adafruit_CircuitPython_FunHouse/pull/9
Please merge that PR prior to merging this one.

Updated to use temp/hum/pres inside peripherals

---

CircuitPython_JEplayer_mp3/code.py
Clue_Step_Counter/clue_step_counter.py
MagTag_Covid_Vaccination/code.py
MagTag_Progress_Displays/weblate_translated_percent.py
MagTag_Progress_Displays/year_progress_percent.py
PyPortal_TOTP_Friend/code.py

This updates the progressbar imports to the new syntax. 
These changes go along with this PR: https://github.com/adafruit/Adafruit_CircuitPython_ProgressBar/pull/25

update progress bar imports

---

CircuitPython_Made_Easy_On_CPX/cpx_buttons_1_neopixel.py
CircuitPython_Made_Easy_On_CPX/cpx_buttons_neopixels.py
CircuitPython_Made_Easy_On_CPX/cpx_temperture_plotter.py
Sensor_Plotting_With_Mu_CircuitPython/audio.py
Sensor_Plotting_With_Mu_CircuitPython/color.py
Sensor_Plotting_With_Mu_CircuitPython/temperature.py

These confuse CircuitPython_Library_Screenshot_Maker.
The diff may not show usefully on github, but the byte sequence `b"\xef\xbb\xbf"` is removed from the beginning of each file.
Standard Python, and probably CircuitPython, is not affected by this, but `findimports` does not know how to handle it.

Remove UTF-8 "byte order mark" from Python files

---

.github/workflows/images.yml

This workflow will generate a bunch of images and place them on a branch called "folder-images", which (once enabled via github pages) will appear on adafruit.github.io.
The workflow is triggered:
* on commits to the main branch, including merged pull requests
* daily, after the bundle is updated
* on request via the github web page
Typically, this means that the images will be available (well) within an hour after a pull request is merged, and will be updated daily if required by changes to the requirements of libraries.
There is an HTML index by name, to make it "easier" to find the relevant image.
Here is the site generated under my personal github pages: http://www.unpythonic.net/Adafruit_Learning_System_Guides/
Index:
Typical image (from …

Add a workflow to generate folder images

---

FunHouse_HA_Companion/code.py

Line 87 erroneously referenced "light" rather than "pressure" causing incorrect pressure value to display on screen.
the code. …

Update FunHouse_HA_Companion cody.py file

---

CircuitPython_Touch_Deck/code.py
CircuitPython_Touch_Deck/touch_deck_layers.py

This change adds a new type of action that allow users to make shortcut icons that change to specific layers.

TouchDeck: implementing change_layer action on shortcuts

---

Astrophotography_Tracker/code.py

~~Basically the earth actually takes 23hrs 56mins and 4.1 seconds to make a full rotation.~~
So basically the Earth takes 23hrs 56mins and 4.1 seconds to make one rotation in respect to distant astronomical objects. To be honest, I don't really understand why this is. I think it's got something to do with solar days being affected by the movement of the Earth around the sun but sidereal days not being affected since all the other stars are really far away from us, but the Wikipedia article just made me really confused.
Regardless, this change should allow the astrophotography tracker to be more accurate at longer exposures.

Moved to sidereal days

---

MagTag_Tides/magtag_tides_land_lp.py

Not too surprising, automatic DST determination not supported in CP. So change to just manually setting for now.
Related:
https://forums.adafruit.com/viewtopic.php?f=60&t=179656

Add manual DST setting for MagTag Tides

---

MIDI_CLUE_BLE_Glove/midi_clue_ble_glove.py

Labels expect text to be assigned strings (or crash). Convert the numbers to strings.
Thanks to the user Vault King on discord for raising the issue.

Fix assigning ints to labels in the BLE glove

---

Macropad_Ableton/code.py

Ableton Live clip launcher for Macropad RP2040

first commit Live launcher code

---

Macropad_Ableton/code.py

caught and fixed an error when there were out of range clips in the Live session.

tweaked to ignore out of range clips

---

MagTag_Cat_Fed_Clock/code.py

This is a simple change for the Cat Fed Clock project.
When using 12-hour AM/PM time, hour 12 is called 12 PM.  This changes the hh_mm function code to display it as such.
Tested on our personal cat fed clock at noon - cats are still eating :)

Hour 12 is 12PM; display it as 12p not 12a

---

Macropad_Ableton/code.py

Updated to use adafruit_macropad library for keys, neopixels, rotary encoder, and push encoder. Left midi as adafruit_midi since it does complex things with midi.receive()

refactored for Macropad library

---

CircuitPython_Flying_Toasters/code.py
CircuitPython_Scrolling_Clouds/code.py

Some spelling and tidy-ups for pylint.
Learn Guide:
https://learn.adafruit.com/circuitpython-sprite-animation-pendant-mario-clouds-flying-toasters/software
Changes Needed - maybe?
The page makes reference to CP4 & 5 but I can't see any specific code.

Flying_Toasters + Scrolling_Clouds: Update for CP7

---

CircuitPython_Display_Text/background_color_example.py
CircuitPython_Display_Text/background_tight_example.py
CircuitPython_Display_Text/base_alignment_test.py
CircuitPython_Display_Text/color_example.py
CircuitPython_Display_Text/colormask_example.py
CircuitPython_Display_Text/display_text_anchored_position.py
CircuitPython_Display_Text/font_example.py
CircuitPython_Display_Text/line_spacing_example.py
CircuitPython_Display_Text/padding_example.py
CircuitPython_Display_Text/scale_example.py

Changes are need in the Learn Guide: https://learn.adafruit.com/circuitpython-display_text-library/overview
Page: https://learn.adafruit.com/circuitpython-display_text-library/types-of-labels
Section: Most of the page
@FoamyGuy This can have the `max_size` related comments removed, but the `max_glyphs` comments need to remain for now. There is a pending PR which will remove `max_glyphs` - https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/pull/154

CircuitPython_Display_Text: Update for CP7

---

Macropad_MIDI_Tester/code.py

This is a demo of basic MIDI functionality on Macropad using `adafruit_macropad` library for keys, LEDs, knob, knob switch, display, and MIDI. Sends noteon/noteoff, program change, cc, pitchbend.

first commit

---

CircuitPython_RPN_Calculator/code.py

Remove unused imports
Remove usage of max_size from displayio.Group
Remove usage of max_glyphs from Label
Learn Guide:
https://learn.adafruit.com/diy-rpn-desktop-calculator-with-circuitpython/overview
Changes Needed: *nothing apparent*

RPN Calculator: Update for CP7

---

Circuit_Playground_Sailor_Moon_Star_Locket/code.py

Changes are need in the Learn Guide: https://learn.adafruit.com/sailor-moon-star-locket/overview
Page: https://learn.adafruit.com/sailor-moon-star-locket/circuitpython-code-walkthrough
Section: `Graphics: Groups`
Asset Link: https://learn.adafruit.com/pages/21957/elements/3086998/download
New version:
```
jewel_splash = displayio.Group()
jewel_splash.append(jewel_outline)
jewel_splash.append(jewel)
```

Circuit_Playground_Sailor_Moon_Star_Locket: Update for CP7

---

Buckaroo_Plant_Care_Bot/buckaroo_plant_care_bot.py

Update OnDiskBitmap pixel_shader usage
No apparent changes are need in the Learn Guide:
https://learn.adafruit.com/chauncey-flower-watering-bot-clue/overview

Buckaroo_Plant_Care_Bot: Updates for CP7

---

Baudot_TTY/baudot_tty_GUI.py
Baudot_TTY/baudot_tty_ble.py

No apparent changes are need in the Learn Guide:
https://learn.adafruit.com/clue-teletype-transmitter/overview

Baudot_TTY: Remove max_size usage from displayio.Group

---

CircuitPython_MacroPad_NKRO/boot.py
CircuitPython_MacroPad_NKRO/code.py

This example will be added to the guide "Customizing USB Devices in CircuitPython".
Initially entering as a draft so someone with a macropad (and a non-linux PC:) can test it first.

USB NKRO example for MacroPad

---

Adafruit_MacroPad/MacroPad/code.py

Apparently _pixelbuf no longer has colorwheel in it (https://github.com/adafruit/circuitpython/issues/4992). But it does live in the builtin rainbowio lib,
the code.
Moving colorwheel import to built in rainbowio lib
Simple import change - just makes the code work now
process.
Just opened my adabox019 and started …

fix colorwheel location

---

Macropad_2FA_TOTP/macropad_totp.py

CP 7.0.0 alpha's up to 4 used a different epoch based on the year 2000. CP 7.0.0 alpha 5 reverts back to 1970 base epoch. This changes the code, originally written with CP 7.0.0 alpha 3, to work with latest CP update.
related issue and PR:
https://github.com/adafruit/circuitpython/issues/4893
https://github.com/adafruit/circuitpython/pull/4961

Update Macropad TOTP

---

CLUE_Egg_Drop/clue_egg_drop.py

Update OnDiskBitmap usage for filename string.
Ref: #1603
Learn Guide: https://learn.adafruit.com/egg-drop-clue
*No apparent changes needed*

CLUE Egg Drop: Update for CP7

---

CLUE_Hand_Wash_Timer/clue_hand_wash_timer.py

Update OnDiskBitmap usage with filename string for CP7
Ref: #1603
Learn Guide: https://learn.adafruit.com/no-touch-hand-wash-timer-for-cpx-and-clue
Changes Needed:
Page: https://learn.adafruit.com/no-touch-hand-wash-timer-for-cpx-and-clue/clue-hand-wash-timer
Sections:
* Display and Images: Update the OnDiskBitmap code

CLUE Hand Wash Timer: Update for CP7

---

CLUE_BBQ/clue_bbq.py

Ref: #1603
Learn Guide: https://learn.adafruit.com/circuitpython-multi-temperature-ble-monitoring
Changes needed to Learn Guide:
Page: https://learn.adafruit.com/circuitpython-multi-temperature-ble-monitoring/coding-the-bbqlue
Sections:
* Display Groups - remove `max_size`
* Homescreen - remove `max_glyphs`
* Temperature screen - remove `max_size` and `max_glyphs`

CLUE BBQ: Update for CP7

---

CircuitPython_JEplayer_mp3/code.py
CircuitPython_JEplayer_mp3/icons.py

Update OnDiskBitmap usage for filename string with CP7
Learn Guide:
https://learn.adafruit.com/pygamer-mp3-player-with-circuitpython
Updates needed: maybe
CircuitPython 5 is referred to on the first page and the Install JEplayer page, but nothing else jumps out.

JEplayer MP3: Update for CP7

---

CircuitPython_Pyloton/pyloton.py

Update OnDiskBitmap usage to take a filename string in CP7 
Learn Guide: https://learn.adafruit.com/pyloton
Updates Needed:
Page: https://learn.adafruit.com/pyloton/code-the-pyloton-in-circuitpython-for-clue
* Section: `_label_maker` - remove `max_glyphs`
* Section: `show_splash` -  reworked in `pyloton.py`

Pyloton: Update for CP7

---

CircuitPython_Touch_Deck/code.py

Learn Guide:
https://learn.adafruit.com/touch-deck-diy-tft-customized-control-pad
*No apparent changes needed*

Touch Deck: Update for CP7

---

CircuitPython_Sip_and_Puff/.gitignore
CircuitPython_Sip_and_Puff/code.py
CircuitPython_Sip_and_Puff/puff_detector.py
CircuitPython_Sip_and_Puff/serial_logger.py
CircuitPython_Sip_and_Puff/simple_hid.py

Learn Guide: https://learn.adafruit.com/st-lps33-and-circuitpython-sip-and-puff
*No apparent changes needed*

Sip and puff: Update for CP7

---

PyPortal_Azure_Plant_Monitor/azure_gfx_helper.py
PyPortal_Azure_Plant_Monitor/code.py
azure_gfx_helper.py

Remove max_glyphs usage with Display_Text Label.
Remove old code using position with TileGrid.
Learn Guides:
Unknown for `azure_gfx_helper.py` in the root directory
https://learn.adafruit.com/using-microsoft-azure-iot-with-circuitpython/overview

Azure gfx helper: Update for CP7

---

CircuitPython_RGBMatrix/fruit.py
CircuitPython_RGBMatrix/life.py
CircuitPython_RGBMatrix/scroller.py

Remove usage of max_size from displayio.Group
Learn Guide:
https://learn.adafruit.com/rgb-led-matrices-matrix-panels-with-circuitpython/overview
Changes Needed: *nothing apparent*

RGBMatrix: Update for CP7

---

CircuitPython_PyPaint/code.py

Remove `max_size` usage from `displayio.Group`
Changes are need in the Learn Guide: https://learn.adafruit.com/pypaint/the-code
The code for the `class TouchscreenPoller` section needs updated from `code.py`
https://learn.adafruit.com/pages/16609/elements/3032434/download

Pypaint: Update for CP7

---

AHT20_OLED/code.py

**Question:** Is this directory used? The obvious Learn Guide search for `AHT20` does not use this. It uses the `simpletest` from the library.
https://learn.adafruit.com/adafruit-aht20/python-circuitpython

AHT20-OLED: Remove max_size usage from displayio.Group

---

CircuitPython_SharpDisplay_Displayio/code.py

Remove usage of max_size from displayio.Group and max_glyphs from Label
Learn Guide:
https://learn.adafruit.com/adafruit-sharp-memory-display-breakout/overview
Changes needed to guide? *nothing apparent*

SharpDisplay: Update for CP7

---

CircuitPython_Essentials/CircuitPython_Digital_In_Out.py
CircuitPython_Essentials/CircuitPython_HID_Keyboard.py
CircuitPython_Essentials/CircuitPython_Logger.py
CircuitPython_Essentials/CircuitPython_PWM.py
CircuitPython_Essentials/CircuitPython_UART.py

This updates the led usage to board.LED instead of board.D13.
Learn guide updates are needed to the following pages:
https://learn.adafruit.com/circuitpython-essentials/circuitpython-digital-in-out
https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm
https://learn.adafruit.com/circuitpython-essentials/circuitpython-uart-serial

CircuitPython Essentials: Update board.D13 to board.LED

---

Macropad_Olympic_Hotkeys/mac-olympics-home.py
Macropad_Olympic_Hotkeys/mac-sports-1.py
Macropad_Olympic_Hotkeys/mac-sports-2.py
Macropad_Olympic_Hotkeys/mac-sports-3.py
Macropad_Olympic_Hotkeys/mac-sports-4.py

- Contains 5 pages of macros to be used as shortcuts for viewing the Olympics events, results, scores, schedules and more
- code.py comes from this guide https://learn.adafruit.com/macropad-hotkeys/project-code

Macropad Olympic Hotkeys Macros code

---

Macropad_Hotkeys/macros/mac-adobe-illustrator.py
Macropad_Hotkeys/macros/mac-adobe-photoshop.py
Macropad_Hotkeys/macros/mac-safari.py
Macropad_Hotkeys/macros/win-adobe-illustrator.py
Macropad_Hotkeys/macros/win-adobe-photoshop.py
Macropad_Hotkeys/macros/win-edge.py

Essentially the same three (Adobe Photoshop and Illustrator, and system default browser). Additionally, “Mac” and “Win” have been added to the banner label shown on the display, so users have some extra feedback if they’ve installed the wrong files (e.g. if they just drag-and-drop the lot instead of pick and choose).

Add starter examples for Windows, distinguish Mac/Win in title

---

CircuitPython_Pyloton/pyloton.py

Remove use of `were_pressed()`, and therefore `gamepad`, from Pyloton project. Substitute simple button-push monitoring. Not tested, but looks plausible.
This is to accomodate the removal of `gamepad` in CircuitPython 7.0.0.

Remove gamepad use from Pyloton

---

CLUE_Light_Painter/code.py

Learn Guide: https://learn.adafruit.com/clue-light-paintstick

CLUE Light Painter: Update for CP7

---

CLUE_Metronome/clue_metronome.py

Learn Guide: https://learn.adafruit.com/metronome-clue

CLUE Metronome: Update for CP7

---

CLUE_Rock_Paper_Scissors/advanced/rps_display.py
CLUE_Rock_Paper_Scissors/simple/clue-simple-rpsgame.py

Learn Guide: https://learn.adafruit.com/rock-paper-scissors-circuitpython

CLUE Rock Paper Scissors: Update for CP7

---

CPB_AMS_Gizmo_BLE/cpb_ams_gizmo_ble.py

Learn Guide: https://learn.adafruit.com/now-playing-bluetooth-apple-media-service-display
*No apparent changes needed to guide*

CPB AMS Gizmo BLE: Update for CP7

---

IoT_Party_Parrot/code.py

Learn Guide: https://learn.adafruit.com/iot-twitter-listener-party-parrot

IoT Party Parrot: Update for CP7

---

Macropad_Hotkeys/code.py

Learn Guide: https://learn.adafruit.com/macropad-hotkeys
*No apparent guide updates needed*

Macropad Hotkeys: Update for CP7

---

FunHouse_IOT_Hub/battery_peripheral/code.py
FunHouse_IOT_Hub/code.py

Learn Guide: https://learn.adafruit.com/adafruit-io-hub-with-the-adafruit-funhouse
Guide update needed:
Page: https://learn.adafruit.com/adafruit-io-hub-with-the-adafruit-funhouse/code-run-through
Section: https://learn.adafruit.com/pages/22252/elements/3096373/download - Remove max_size

FunHouse IOT Hub: Update for CP7

---

EInk_CircuitPython_Quickstart/213_tricolor_eink_fw_badge.py
EInk_CircuitPython_Quickstart/213_tricolor_eink_fw_text.py
EInk_CircuitPython_Quickstart/27_tricolor_eink_shield_badge.py
EInk_CircuitPython_Quickstart/27_tricolor_eink_shield_text.py

Learn Guide: https://learn.adafruit.com/quickstart-using-adafruit-eink-epaper-displays-with-circuitpython
*No apparent changes needed to guide*

EInk CircuitPython QuickStart: Update for CP7

---

CPB_ANCS/code.py

Learn Guide: https://learn.adafruit.com/ancs-gizmo
*No apparent changes needed to the guide*

CPB ANCS: Update for CP7

---

Macropad_Ableton/code.py

Learn Guide: https://learn.adafruit.com/ableton-live-macropad-launcher
*No apparent changes needed to guide*

Macropad Ableton: Update for CP7

---

MagTag_Christmas_Countdown/code.py

Learn Guide: https://learn.adafruit.com/magtag-daily-christmas-countdown
Updates needed:
Page: https://learn.adafruit.com/magtag-daily-christmas-countdown/circuitpython-code-walkthrough
Sections:
* https://learn.adafruit.com/pages/21083/elements/3078956/download
* https://learn.adafruit.com/pages/21083/elements/3078958/download

MagTag Christmas Countdown: Update for CP7

---

Tilemap_Game_With_CircuitPython/code.py

Updates for cp7. Ref #1603 
Also fixed an issue with text getting pushed off the bottom of the screen when some of the longer "minerva" texts come up.
Tested successfully on Edge Badge 7.0.0 alpha5
Guide: https://learn.adafruit.com/creating-your-first-tilemap-game-with-circuitpython/overview
No changes needed.

tilemap game cp7 updates and text location fix

---

pyportal_weather_station/weatherstation_helper.py

Updates for CP 7 Ref: #1603
Also removed a fallback exception catch that seemed to be supporting a very old version of displayio.TileGrid I checked all the way back to 4.x and there was no `position` parameter at that time, I'm not sure when it got removed, but must have been before then.
I don't have the specific sensors needed for testing this project.
Guide: https://learn.adafruit.com/pyportal-iot-weather-station/overview
No apparent changes needed in the guide.

pyportal iot weatherstation cp7 updates

---

Weather_Display_Matrix/openweather_graphics.py

Ref: #1603 
Updates for cp7 in the weather display matrix project.
Tested on Matrix Portal 7.0.0 alpha 5.
Guide: https://learn.adafruit.com/weather-display-matrix/overview 
No apparent changes need.

weather display matrix cp7 updates

---

TFT_Gizmo_Snowglobe/snowglobe_fancy.py
TFT_Gizmo_Snowglobe/snowglobe_simple.py

updates for cp7. Ref: #1603 
Also noticed an issue with using a color in the background causing an `AttributeError` I suspect the type of error raised by the core code was changed and this type was not one the ones that were caught so it caused the code to crash. Fixed by adding it to the types that are caught so the code will successfully move on and set the background color.
Tested with CircuitPlayground Bluefruit 7.0.0 alpha5 + TFT Gizmo
Guide: https://learn.adafruit.com/circuit-playground-tft-gizmo-snow-globe/overview-2
No changes needed in the guide

snowglobe cp7 updates and background fix

---

Ukulele/code.py

These changes update the code to use the latest version of ulab with the renaming that has occurred.
There was 1 instance of usage of `argmax` that needed updating on this page: https://learn.adafruit.com/light-up-reactive-ukulele/software and I've changed it to match the new code from this PR.
I do not have the specific hardware required for testing the full project. But I did run the specific lines of code that were changed in REPL to verify that they work as intended.

update ukulele for ulab renames

---

PyPortal_TOTP_Friend/code.py

Also tweaked progress bar color for better contrast to make it visible.
Tested on PyPortal 7.0.0 apla5
Guide: https://learn.adafruit.com/pyportal-2fa-totp-authentication-friend/overview
There don't appear to be any changes needed in the guide.

pyportal totp cp7 updates

---

PyPortal_User_Interface/code.py

Guide changes needed on these pages:
- max_size remove: https://learn.adafruit.com/making-a-pyportal-user-interface-displayio/groups
- OnDiskBitmap update,max_size remove, and except fallback for very old TileGrid: https://learn.adafruit.com/making-a-pyportal-user-interface-displayio/images-2
- max_glyphs remove: https://learn.adafruit.com/making-a-pyportal-user-interface-displayio/text-box
- this page mentions an update in the works to make positioning text easier. Explanations of anchor point and anchored position could be included now, those have been supported for a while: https://learn.adafruit.com/making-a-pyportal-user-interface-displayio/let-s-make-a-ui
Tested on PyPortal 7.0.0 alpha5

pyportal interface cp7 updates

---

PyPortal_Wakeup_Light/wake_up_light.py

Updates for CP7 Ref: #1603
There are a few instances of `max_glyphs` to remove on this guide page: https://learn.adafruit.com/pyportal-wake-up-light/using-the-wake-up-light#displaying-text-3035445-13
tested on PyPortal 7.0.0 alpha5

pyportal wakeup light cp7 updates

---

PyPortal_AWS_IOT_Planter/aws_gfx_helper.py

Learn Guide: https://learn.adafruit.com/pyportal-iot-plant-monitor-with-aws-iot-and-circuitpython

PyPortal AWS IOT Planter: Update for CP7

---

PyGamer_Improved_Thermal_Camera/code.py

Learn Guide: https://learn.adafruit.com/improved-amg8833-pygamer-thermal-camera
Changes needed: Page: https://learn.adafruit.com/improved-amg8833-pygamer-thermal-camera/display
* Search for `max_size` and `max_glyphs`

PyGamer Improved Thermal Camera: Update for CP7

---

MagTag_Google_Calendar/authenticator.py
MagTag_Google_Calendar/code.py

Learn Guide: https://learn.adafruit.com/magtag-google-calendar-event-display

MagTag Google Calendar: Update for CP7

---

Baudot_TTY/baudot_tty_GUI.py

Learn Guide: https://learn.adafruit.com/clue-teletype-transmitter

Baudot TTY: Update for CP7

---

Say_Their_Names_LEDMatrix/code.py

This updates the code for CP7 breaking changes.
I noticed that the "Black Lives Matter" text was shifted a few pixels too high, the top half of "Black" was off the top edge of the matrix display. And the names text was a few pixels off-center to the right. So I fixed both of those things to get "Black Lives Matter" onto the display, and center the names text.
Tested on MatrixPortal 7.0.0 alpha5
I didn't find any guides that go with this project. It's linked from a blog post here: https://blog.adafruit.com/2020/06/08/how-to-make-python-powered-protest-signs-black-lives-matter-say-their-names/

cp7 updates and text position

---

RGB_Matrix_Slot_Machine/code.py

updates for CP7 ref: #1603
tested on MatrixPortal 7.0.0 alpha5
There is one instance of `max_size` in a code snippet that will need to be updated on this page: https://learn.adafruit.com/rgb-matrix-slot-machine/circuitpython-code-walkthrough

matrix slot machine cp7 updates

---

PyGamer_Thermal_Camera/code.py

Learn Guide: https://learn.adafruit.com/pygamer-thermal-camera-amg8833
Changes Needed: Page: https://learn.adafruit.com/pygamer-thermal-camera-amg8833/display
* Search for `max_size` and `max_glyphs`

PyGamer Thermal Camera: Update for CP7

---

CLUE_Light_Painter/bmp2led.py

These changes update the light painter project to use the newest version of `ulab`
Don't have the hardware setup to test this.

update light painter for ulab renames

---

Ocean_Resin_Lightbox/code.py

These changes update the usages of `ulab` to use the renaming that was done in the latest version.
I have found and updated 3 instances of these changes in code snippets on this guide page: https://learn.adafruit.com/ocean-epoxy-resin-lightbox-with-rgb-led-matrix-image-scroller/code-explanation
I do not have the right hardware to test this specific project.

update ocean resin for ulab renames

---

CLUE_Metal_Detector/clue-metal-detector.py

These changes update CLUE metal detector code to use the latest version of `ulab` which contained extensive renaming.
I tested the updated code successfully on `Adafruit CircuitPython 7.0.0-alpha.5 on 2021-07-21; Adafruit CLUE nRF52840 Express with nRF52840`

update clue metal detector for ulab renames

---

Macropad_Hotkeys/code.py

https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/d5b6ea50f49ef4575a1fbe52259c2dff44bcab2b/adafruit_hid/keyboard.py#L144
In hid, if you press the positive numbers, it won't actually remove them if you pass in negative numbers.

Release keys should work on positive integers

---

PyPortal_Electioncal_US/electioncal_graphics.py

Learn Guide: https://learn.adafruit.com/pyportal-electioncal-us

PyPortal Electioncal US: Update for CP7

---

PyPortal_Remote/code.py

tested on PyPortal 7.0.0 alpha5
There is one instance of `max_size` to remove in a code snippet on this page: https://learn.adafruit.com/pyportal-roku-remote/code-run-through

pyportal remote cp7 updates

---

PyPortal_Smart_Thermometer/thermometer_helper.py

also removed fallback code for very old version of displayio.TileGrid
tested on PyPortal 7.0.0 alpha5
Guide: https://learn.adafruit.com/pyportal-smart-thermometer-with-analog-devices-adt7410-adafruit-io-and-circuitpython/overview
There don't appear to be any changes needed in the guide.

pyportal smart thermometer station cp7 updates

---

Pico_MIDI_Fighter/code.py

Learn Guide: https://learn.adafruit.com/raspberry-pi-pico-led-arcade-button-midi-controller-fighter
Changes Needed: Page https://learn.adafruit.com/raspberry-pi-pico-led-arcade-button-midi-controller-fighter/circuitpython-code-walkthrough
Section:
* Display Setup - https://learn.adafruit.com/pages/21745/elements/3084742/download - Remove `max_size`
* GUI Navigation Setup - https://learn.adafruit.com/pages/21745/elements/3084757/download - `switch_coordinates` has been reformatted

Pico MIDI Fighter: Update for CP7

---

Voice2Json_Edge_Detection/demo.py

Ref: #1603
Updates for cp7 breaking changes.
I don't have the necessary hardware for testing.
Two instances of code snippets will need updated on this page: https://learn.adafruit.com/edge-speech-recognition-with-voice2json/demo-code

Voice2json cp7 updates

---

Matrix_Sprite_Animation_Player/matrix_sprite_animation_player.py

Learn Guide: https://learn.adafruit.com/32x32-square-pixel-display
Changes Needed: Page: https://learn.adafruit.com/32x32-square-pixel-display/code
Section:
* Adjusted Code - https://learn.adafruit.com/pages/22032/elements/3088628/download - Remove max_size

Matrix Sprite Animation Player: Update for CP7

---

PyPortal_Philips_Hue_Controller/code.py

updates for cp7 Ref: #1603
I don't have the hue light for testing.
There is one instance of `max_size` to remove on this guide page: https://learn.adafruit.com/pyportal-philips-hue-lighting-controller/code-walkthrough

pyportal phillips hue cp7 updates

---

pyportal_pet_planter/code.py

updates for cp7 ref: #1603 
I don't have the specific hardware necessary for testing
guide: https://learn.adafruit.com/pyportal-pet-planter-with-adafruit-io/overview
there don't appear to be any changes needed within the guide

pyportal pet planter cp7 updates

---

PyPortal_MQTT_Control/code.py

tested on PyPortal with 7.0.0 alpha5
There are a few instances of `max_size` and `max_glyphs` in code snippets and supporting text on this guide page: https://learn.adafruit.com/pyportal-mqtt-sensor-node-control-pad-home-assistant/code-breakdown

pyportal mqtt control cp7 updates

---

PyPortal_MogwaiClock/mogwai.py

updates for cp7 Ref: #1603
tested on PyPortal 7.0.0 alpha5
I was unable to find a guide that was using this code, this blog post was the only reference I did find: https://blog.adafruit.com/2019/03/10/gremlin-clock-an-iot-wi-fi-alarm-clock-for-mogwai-adafruit-circuitpython-mogwai-gremlins/

pyportal mogwai cp7 updates

---

PyPortal_LIFX_Controller/code.py

updates for cp7 ref: #1603 
I don't have the smart light needed for testing
There is 1 instance of `max_size` to remove in a code snippet on this guide page: https://learn.adafruit.com/pyportal-lifx-lighting-controller/code-walkthrough

pyportal lifx controller cp7 updates

---

PyPortal_Hurricane_Tracker/hurricane_tracker.py

Learn Guide: https://learn.adafruit.com/pyportal-hurricane-tracker

PyPortal Hurricane Tracker: Update for CP7

---

PyPortal_ISS_Tracker/pp_iss_tracker.py

Learn Guide: https://learn.adafruit.com/pyportal-iss-tracker

PyPortal ISS Tracker: Update for CP7

---

CircuitPython_displayio/displayio_ondiskbitmap.py
CircuitPython_displayio/displayio_text.py

Update the Text example to use the variables declared at the start.
Learn Guide: https://learn.adafruit.com/circuitpython-display-support-using-displayio
Updates Needed: Maybe, the learn guide code does not appear to link to Github and may need to be copied over.
Page: https://learn.adafruit.com/circuitpython-display-support-using-displayio/display-a-bitmap
Section: OnDiskBitmap

CircuitPython_displayio: Update for CP7

---

CircuitPython_RGBMatrix/fruit.py
CircuitPython_RGBMatrix/tiled.py

Learn Guide: https://learn.adafruit.com/rgb-led-matrices-matrix-panels-with-circuitpython

CircuitPython RGBMatrix: Update for CP7

---

Hallowing_Jump_Sound/jump-sound.py
Hallowing_Jump_Sound/stomp-and-roar.py

Update OnDiskBitmap code to take a filename string with CP7
Replace board.A0 with board.SPEAKER
Replace board.A... with board.TOUCH...
Replace busio.I2C(...) with board.I2C()
Learn Guide: https://learn.adafruit.com/last-minute-halloween-accoutrements-with-hallowing

HalloWing Jump Sound: Update for CP7

---

MetroX_CircuitPython/fading_led.py
MetroX_CircuitPython/mib_button_press_pwm.py
MetroX_CircuitPython/mib_motor.py
MetroX_CircuitPython/mib_potentiometer_pwm.py
MetroX_CircuitPython/mib_servo.py
MetroX_CircuitPython/photo_sensor.py
MetroX_CircuitPython/servo.py
MetroX_CircuitPython/squeeze.py

In CP7 PWMOut has been removed from `pulseio` and exists only in `pwmio` now.
MetroX_Circuitpython was the only code I found in this repo that was using the older no longer supported pulsio version.
I was unable to find any guides in the learn system that are referencing this code. My guess is that the main product guides for the Metro M0 and M4 may have referenced this in the past (i.e. pages like these https://learn.adafruit.com/adafruit-metro-m4-express-featuring-atsamd51/circuitpython-essentials) but now these embed the more generic CircuitPython Essentials code which covers largely the same topics.
I tested the fading_led script on a Metro M0 with CircuitPython 7.0.0 alpha5, but did not test any of the other examples.
In fading_led I noticed that the fade goes too fast to see with …

cp7 update for pwmio

---

Kitty_Paw_Keypad/code.py

Ref: #1747 
Updating to CP7 version of OnDiskBitmap usage. Also removed keyword arguments that were set to default values.
Code snippets on this guide page can be updated to reflect these changes: https://learn.adafruit.com/kitty-toe-bean-paw-keypad-color-tct/circuitpython-code-walkthrough

cp7 version of OnDiskBitmap  usage for kittypaw keyboard

---

Magic_Nine_Ball/magic_nine_ball.py

Ref: #1747 
Tested with slight modifications on Hallowing M4. 
Guide: https://learn.adafruit.com/hallowing-magic-9-ball/overview
No apparent changes needed in the guide.

cp7 version of OnDiskBitmap  usage for hallowing magic 9 ball

---

PyGamer_Improved_Thermal_Camera/code.py

Ref: #1747 
Adds the CP7 versin of OnDiskBitmap usage.
There is a code snippet that can be updated with the new usage for when 7 release is stable  near the bottom of this page: https://learn.adafruit.com/improved-amg8833-pygamer-thermal-camera/import-and-initialize

cp7 version of OnDiskBitmap  usage for improved pygamer thermal cam

---

HalloWing_Jump_Scare_Trap/hallowing_jump_scare_trap.py

Update OnDiskBitmap code to take a filename string with CP7
Replace displayio.Sprite with displayio.TileGrid
Replace board.D13 with board.LED
Learn Guide: https://learn.adafruit.com/hallowing-jump-scare-trap

HalloWing Jump Scare Trap: Update for CP7

---

PyGamer_Thermal_Camera/code.py

Ref: #1747 
adding CP7 version of OnDiskBitmap setup
There is a code snippet that contains the section of code that can be changed for CP7 when it's stable at the bottom of this page: https://learn.adafruit.com/pygamer-thermal-camera-amg8833/import-and-initialize

cp7 version of OnDiskBitmap  usage for pygamer thermal cam

---

HalloWing_Tour_Guide/code.py

Update OnDiskBitmap code to take a filename string with CP7
Replace display.Sprite with displayio.TileGrid
Replace board.A0 with board.SPEAKER
Remove out-of-date DISPLAY.wait_for_frame()
Learn Guide: https://learn.adafruit.com/gps-tour-guide
Changes needed:
Page: https://learn.adafruit.com/gps-tour-guide/software
* Section: CircuitPython Libraries - `debouncer.py` should be `adafruit_debouncer.mpy` and it should be included in the sentence `Before continuing make sure your board's lib folder or root filesystem has the adafruit_bus_device, adafruit_debouncer.mpy and adafruit_gps.mpy files copied over.`

HalloWing Tour Guide: Update for CP7

---

Tilemap_Game_With_CircuitPython/code.py

Ref: #1747 
This removes the `with` context for opening the message background image in order to lessen the changes needed for the CP7 version which can how have the filename passed to OnDiskBitmap constructor instead an open file handle.
The changes shown in the github interface look more substantial than they really are since much of is un-indented from the removal of `with` context.
Tested on PyGamer with 7.0.0 alpha5
Guide: https://learn.adafruit.com/creating-your-first-tilemap-game-with-circuitpython/overview
No changes needed in the guide. The only place that references OnDiskBitmap is in the github embed.

cp7 version of OnDiskBitmap  usage for tilemap game

---

PyPortal_Alarm_Clock/code.py

Ref: #1747 
Add cp 7+ compatibility code in comment and remove fallback for very old version of TileGrid with position argument.
There are two code snippets to update on this page: https://learn.adafruit.com/pyportal-alarm-clock/the-time-state

Pyportal alarm clock cp7

---

PyPortal_AWS_IOT_Planter/aws_gfx_helper.py

cp7 OnDiskBitmap and TileGrid updates ref: #1747 
Guide: https://learn.adafruit.com/pyportal-iot-plant-monitor-with-aws-iot-and-circuitpython/overview
The lower level details of the gfx_helper aren't discussed on any of the guide pages. Appears to me that there are no changes needed in the guide.

cp7 version of OnDiskBitmap and TileGrid usage

---

RBG_Matrix/code.py

Learn Guide: *Unknown*
The only guide that I can find that uses a `rbg.bmp` (Ruth Bader Ginsburg) is https://learn.adafruit.com/image-correction-for-rgb-led-matrices but there is no CircuitPython code in that.

RBG Matrix: Update for CP7

---

PyPortal_Calculator/code.py
PyPortal_Calculator/titano_code.py

Learn Guide: https://learn.adafruit.com/pyportal-calculator-using-the-displayio-ui-elements
Changes needed:
Page: https://learn.adafruit.com/pyportal-calculator-using-the-displayio-ui-elements/ui-quickstart
* Section: Groups - remove `max_size`
Page: https://learn.adafruit.com/pyportal-calculator-using-the-displayio-ui-elements/circuitpython-code
* https://learn.adafruit.com/pages/16651/elements/3033366/download - Remove `max_size`
* https://learn.adafruit.com/pages/16651/elements/3033375/download - Remove `max_glyphs`

PyPortal Calculator: Update for CP7

---

PyPortal_Titano_Weather_Station/openweather_graphics.py

also removed fallback for very old version of displayio.TileGrid
I don't have the hardware device needed for testing.
There are references to `max_size` and `max_glyphs` as well as the OnDiskBitmap / pixel_shader within code snippets on this guide page: https://learn.adafruit.com/pyportal-titano-weather-station/code-walkthrough-openweather-graphics-py

pyportal titano weather station cp7 updates

---

Matrix_On_Air/matrix_on_air.py

Learn Guide: https://learn.adafruit.com/rgb-matrix-automatic-youtube-on-air-sign
*No apparent changes needed to guide*

Matrix On Air: Update for CP7

---

PyPortal_Hurricane_Tracker/hurricane_tracker.py

For #1778.
Restructures the network stuff to use more lower level funcs and prevent some of the automated (but not needed) stuff that was kicking in when using the higher level funcs. The automated stuff is what was exceeding available memory and was probably not part of the library when guide code was originally written.

Update PyPortal Hurricane Tracker

---

CircuitPython_qrio/repl/.circuitpython.skip
CircuitPython_qrio/repl/code.py
CircuitPython_qrio/usb_hid/.circuitpython.skip
CircuitPython_qrio/usb_hid/code.py

These errors were exposed with #1772 but hidden again by the addition of skip files.

Fix pylint errors in qrio guide code

---

CircuitPython_displayio/displayio_display_driver.py
CircuitPython_displayio/displayio_display_manual.py
CircuitPython_displayio/displayio_font.py
CircuitPython_displayio/displayio_parallelbus.py
CircuitPython_displayio/displayio_pixels.py
CircuitPython_displayio/displayio_text.py
CircuitPython_displayio/displayio_tilegrids.py

These examples are used in the main displayio guide here: https://learn.adafruit.com/circuitpython-display-support-using-displayio/introduction
Many of them were missing main loops so if you attempted to run them they would technically work but you would not be able to see the result on the display since the program would end immediately afterward.
This adds main loops to the ones that were missing it so that you can actually see the result on the display.

add main loop in displayio examples

---

CircuitPy_OTP/code.py
Macropad_2FA_TOTP/code.py
PyPortal_TOTP_Friend/code.py

The following comment was posted to the [MacroPad 2FA TOTP guide](https://learn.adafruit.com/macropad-2fa-totp-authentication-friend/overview):
> A secret length of anything other than 16 characters seems to cause the code to fail. Is there any way to support longer secrets?
Can use this stand alone code to test the actual TOTP generation:
```python
import adafruit_hashlib as hashlib
def HMAC(k, m):
"""# HMAC implementation, as hashlib/hmac wouldn't fit
From https://en.wikipedia.org/wiki/Hash-based_message_authentication_code
"""
SHA1_BLOCK_SIZE = 64
KEY_BLOCK = k + (b'\0' * (SHA1_BLOCK_SIZE - len(k)))
KEY_INNER = bytes((x ^ 0x36) for x in KEY_BLOCK)
KEY_OUTER = bytes((x ^ 0x5C) for x in KEY_BLOCK)
inner_message = KEY_INNER + m
outer_message = KEY_OUTER + …
```

Fix TOTP Code

---

Adafruit_Proximity_Trinkey/Proximity_Trinkey_MIDI/code.py

midi code example for proximity trinkey, sends CC or pitchbend depending on mode. mode is selected w touch pads.

added MIDI code

---

.github/workflows/githubci.yml

.. to create a release from a tag, and upload the desired artifacts to it. This is the next step towards producing automatic, *nightly* releases with useful artifacts.
Here's a release created with this CI: https://github.com/jepler/Adafruit_Learning_System_Guides/releases/tag/v0.0%2B1633967579
To cause releases to be made nightly, we can add a "cron" job either in this repo or (as is done for learn) in the adabot repo. My understanding is that this job would simply create & push a new tag.
Other rough edges:
* The build isn't identified in any way inside the zip files
* the release notes attached to the release are not meaningful

use actions-gh-release

---

Pumpkin_Goblin_CPB_Ornament/code.py

adding code for Pumpkin Goblin CPB Ornament @TheKitty

adding code for Pumpkin Goblin CPB Ornament

---

AIO_Environmental_Monitor/code.py

- Adding Python code referenced in the guide, https://learn.adafruit.com/adafruit-io-air-quality-monitor/python-code
- Fixes issue with updated BME280 Library: https://forums.adafruit.com/viewtopic.php?f=60&t=184730&p=896310#p896310
- After this Pull Request is merged in, the guide will be updated to point to code within the ALS Guides directory instead of the Adafruit_IO Python examples repo. The code within the examples repo (https://github.com/adafruit/Adafruit_IO_Python/blob/master/examples/basics/environmental_monitor.py) will be swept and I'll remove it, point to this code instead.

Add Adafruit IO Environmental Monitor Code

---

MagTag_Weather/code.py

Instead of waking up at midnight, sleep for a few extra hours to
account for the 2 days in the year where daylight savings change the
clock.
@dherrada wdyt? :)

MagTag_Weather: sleep until 3:15 am to account for daylight adjustments

---

Trinket_M0_Message_Crown/README.md
Trinket_M0_Message_Crown/code.py

As part of the project for adding author and license information, the author and license text has been added to the file in this PR.
https://learn.adafruit.com/customizable-glowy-message-crown/overview

Code for guide "Glowy Message Crown"

---

CircuitPython_Essentials/CircuitPython_I2C_Scan/code.py
CircuitPython_Templates/i2c_scan/code.py

An attempt to update code example to show creating I2C bus manually. QT Py 2040 and Pi Pico are two good examples where existing code does not work and lot's of users end up running into this.

Update CP I2C Scan Example

---

NeoPixel_Menorah/code.py

code for NeoPixel Menorah learn guide

code for NeoPixel Menorah

---

NeoPixel_Menorah/code.py

Adding the code for the NeoPixel Menorah Learn Guide. Adding a button to turn on each neopixel candle one by one

Adding code for NeoPixel Menorah

---

Circuit_Playground_Express_MIDI_Stomping_Pads/code.py

Adding code for MIDI stomping pads Learn Guide. Uses a CPX and four inputs. On input NeoPixels change color and MIDI note is sent

Adding code for midi stomping pads

---

CircuitPython_MacroPad_NKRO/boot.py

There were some leftovers from the previous HID API, where you had to give the Report ID position, not the ID itself.

Redo constants in NRKO example

---

MagTag_Sports_Schedule/code.py
MagTag_Tides/code.py

Resolves: #1945 
@caternuson These are the fixes that we discussed on Discord.
Tide texts were not getting `hidden = False` previously. I think one or more of the libraries got updated at some point and it made this behavior different than it was originally. I ran the Tides project a few months back and the text was visible at that time.
This PR also scoots the bottom line of text a little bit higher in the sports schedule project. Previously the bottom 1 or 2 pixels was partially off the screen.
Also ran black formatting which added a few spaces that were otherwise unrelated to these fixes.
Both changes tested successfully on MagTag with 7.1.0 Beta 1.
Tides Before:
Tides with this change:
Sports Schedule Before:
Sports Schedule with this change:

Magtag project fixes

---

Macropad_Hotkeys/code.py

The Macropad Hotkeys script silently ignores errors in `macros/*.py`. This makes it more robust, but also makes debugging user-provided macro definitions more difficult.
@Neradoc suggested adding a traceback print (thanks!). The new behavior is that the errors will be printed to serial output, but the script will still run.

print out traceback for errors in Macropad Hotkeys macro files

---

Adafruit_NeoSlider/CircuitPython_Rainbow_Slider/code.py

The default out-of-the-bag I2C address for a NeoSlider is `0x30`, but the CircuitPython example is using `0x31.` Changed to `0x30`.
(Noticed this while testing NeoSlider for a customer problem.)

Use default I2C address for NeoSlider CircuitPython example

---

.github/workflows/githubci.yml
.github/workflows/images.yml

`runs-on: ubuntu-18.04` is (temporarily) broken and is breaking CI builds.
Update to `ubuntu-latest`. Also update to Python `"3.x"` to avoid getting behind on Python dependencies.

Use ubuntu-latest and Python 3.x for CI runs

---

PyPortal_Discord/code.py

The issue that this resolves was raised here: https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/issues/57
This project fetches an SVG file and then parses it as text. 
At some point the PyPortal library got improved features for handling more content types and it started relying on content_type returned by the server. 
In the case of this project it broke because the server is using image/svg type, but we want to ignore image and parse it as text.
This uses the fix introduced with: https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/pull/120
I tested this fix successfully on a PyPortal with 7.1.0

use forced content type for pyportal discord

---

Welcome_to_CircuitPython/code.py

Max supported line length in Mu (the recommended editor) is 88 charecters. Several lines in the comments section were longer than this. Changed so it may be copy-pasted as directed in tutorial.

Reformatted to reduce each line length.

---

CircuitPython_Neko_Cat/code.py

Neko cat project was using a feature of displayio.TileGrid that was added after `7.1.1`.
This swaps out it's usage for hardcoded variables because it is a static value for this project, which allows it to run on devices using CircuitPython 7.1.1

fix neko cat for 7.1.1

---

Seesaw_QT_Rotary_Encoder_Multiples/code.py

in response to https://github.com/adafruit/Adafruit_CircuitPython_seesaw/issues/93 adding an example of using multiple rotary encoder QT boards to add to [learn guide](https://learn.adafruit.com/adafruit-i2c-qt-rotary-encoder/python-circuitpython)

adding an example of multiple I2C QT Rotary Encoders

---

CircuitPython_Templates/status_led_one_dotstar_rainbow/code.py
CircuitPython_Templates/status_led_one_dotstar_rgb/code.py
CircuitPython_Templates/status_led_one_neopixel_rainbow/code.py

Add/update DotStar single LED template code

---

IS31FL3741_DisplayIO/scrolling_text/code.py
IS31FL3741_DisplayIO/sports_glasses/code.py

Two new examples for the [EyeLights ](https://learn.adafruit.com/adafruit-eyelights-led-glasses-and-driver) guide. These demonstrate the new native DisplayIO support and two new guide pages will be written to explain how it works.

Added IS31FL3741 DisplayIO Examples

---

Party_Parrot_Zoetrope/code.py

Adding CircuitPython code for the Party Parrot Zoetrope Learn Guide. Uses the Crickit.

Adding code for Party Parrot Zoetrope

---

Adafruit_ESP32_Arduino_Demos/SerialESPPassthrough/SerialESPPassthrough.ino

Just a one line change to allow PyGamer to be recognized when defining the pins needed to run the passthru.
I ran it with my PyGamer and AirLift feather wing, went from v1.2.2 -> v1.7.4
** Note, my PyGamer doesn't work with the ESP32 if I have an SD card inserted.  There is another thread open for this, but so far no progress.  Flashing the ESP32 wing was my latest attempt to fix this issue.

add pygamer to esp32 passthru code

---

NeoPixie_Dust_Bag/code.py

Fixed the button detection to only act on rising edges.
Removed the debounce code (the loop already has a time.sleep in the animation anyway).
The guide uses a Standalone Momentary Capacitive Touch Sensor Breakout ([product 1374](https://www.adafruit.com/product/1374)). Which is active high. So the input pin is pulled down. And not using `touchio` (not without changes to the guide).

Fix the button code in the NeoPixie_Dust_Bag

---

MIDI_for_Makers/BLE_MIDI_Sequencer/code.py
MIDI_for_Makers/Basic_MIDI_Keyboard/code.py
MIDI_for_Makers/Control_Motors_with_MIDI/code.py
MIDI_for_Makers/MIDI_CC_Control_with_Pots/code.py
MIDI_for_Makers/Receive_MIDI_Over_UART_and_Send_Over_USB/code.py
MIDI_for_Makers/Receive_and_Display_MIDI_Messages/code.py

Adding six examples for the MIDI for Makers guide. Three MIDI out (basic keyboard, BLE sequencer, CC pots) and three MIDI in (UART to USB, display MIDI messages and control motors).

Adding code for MIDI for Makers guide

---

CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py
CircuitPython_Templates/lc709203_simple_data/code.py

Adafruit IO example was reviewed by Brent (much appreciated!).
Both examples are destined for their own templates.

LC709203 simple data and Adafruit IO send/receive examples

---

Macropad_MIDI_Tester/code.py

Code was lagging when four notes were played in rapid succession. Added 'while macropad.keys.events:' loop and turned off display auto refresh, instead refreshing once per loop. Note, 5-6 note polyphony still can lag, due probably to hitting the macropad max key event queue. This can probably be solved by using keypad instead of macropad, but that is beyond the scope of the MacroPad main guide examples.

reduced polyphony lag

---

CircuitPython_Knob_Sketcher/feather_sketcher/code.py

Oops. Fixes bug hitting "pixel out of bounds" error when at screen limits.

Fix for Feather Knob Sketcher

---

CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py

Code crashes if `microcontroller.cpu.temperature` is called in the main loop. This update puts it into the 10 second delay block, which resolves the issue.

Update where temp is called.

---

CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py

`microcontroller.cpu.temperature` is still causing a consistent hang, albeit after a longer interval than before. Regardless, it's not usable at the moment.
Switching the Adafruit IO value sent to a random integer. Will revisit later.

Switch to randint() for data sending value.

---

MIDI_for_Makers/Receive_and_Display_MIDI_Messages/code.py

Updating the code for the MIDI display messages example in the MIDI for Makers guide
updating display height, x coord for text and added a comment for new `board.STEMMA_I2C()` option in CP 7.2

Updating display MIDI messages example

---

Adafruit_QT_Py_ESP32-S2/digital_input/code.py

Removed a file that shouldn't have been removed. QT Py does not have a built-in red LED.

Fix digital input example to use NeoPixel.

---

PyPortal_Quarantine_Clock/code.py

* Removes deprecated `default_bg` parameter
* Removes code block involving `esp` connection, pyportal's network connection is performed automatically within `get_local_time()`

Fix PyPortal Quarantine Clock code

---

MagTag_Google_Calendar/authenticator.py
MagTag_Google_Calendar/code.py

This fixes the learn guide code so it no longer fails in CircuitPython 7 by making better use of the MagTag library, which avoids duplicate conflicting network objects.

Updated Google Calendar example to make better use of MagTag library

---

PyBadge_Conference_Badge/code.py

Removes `gamepadshift` from PyBadge Conference Badge example and replaces it with `keypad` library so it will be viable after `gamepadshift` is removed in CircuitPython 8.0.0
No changes to functionality, intended to function as it does prior to this change
Ran successfully on PyBadge with CircuitPython 7.1.1, previous behavior retained.  Learn Guide will need to be updated accordingly, as it explains the code.

Remove gampadshift from PyBadge_Conference_Badge example

---

PyBadge_Blinka_Jump_Game/code.py

Removes `gamepadshift` from the example and replaces it with equivalent usage of `keypad` so code is viable in CircuitPython 8.x.x
No chages to functionality, code is intended to run identically to previous implementation
Code ran successfully on PyBadge with CircuitPython 7.1.1 and demonstrated equivalent performance and behavior.  After briefly checking, Learn Guide will likely need touchups as it explains the project code.

Remove gamepadshift from PyBadge jump game example

---

FunHouse_Arduino_Demos/selftest/selftest.ino
FunHouse_Arduino_Demos/shipping_demo/shipping_demo.ino

A hardcoded value of 0x808080 was in the code for a mid-level grey. This is an RGB888 value, but the ST77XX library uses RGB565 values. A mid-grey in RGB565 is 0x8410. A local define was done to define this as ST77XX_GREY and the new value placed in the calls previously using 0x808080. This solves a compiler integer overflow warning preventing CI from completing.

Update local color mid-grey to RGB565

---

CircuitPython_Templates/asyncio/code.py

I tried this before submitting the code the first time, and it didn't work, but that turned out to be because I was doing it wrong. Returning the `blink` code back to being more understandable.

Simplify blink block.

---

BLE_ANO_Rotary_Encoder_Remote/code.py

Adding the code for the BLE ANO Rotary Encoder remote learn guide. Uses a Feather nRF52840 and the ANO rotary encoder.

Adding code for BLE rotary Learn Guide

---

ESP32S2_TFT_AdBlocker/ESP32S2_TFT_AdBlocker.ino

- changed on-screen text to read "Checking" instead of "Blocking"
- changed on-screen text to "Nahs!"
- increased size of Nahs! count text and re-positioned it lower
- removed un-used import of adblock web page

changed text to 'Checking' and 'Nahs!'

---

QT_Py_RP2040_USB_to_Serial_MIDI_Friends/code.py

Adding code for the USB to Serial midi friends learn guide. Using a pylint ignore for unused-import because the midi libraries are used to recognize the incoming midi messages over USB to send over UART

Adding code for midi friends learn guide

---

PyPortal_Azure_Plant_Monitor/code.py
PyPortal_TOTP_Friend/code.py

The NTP library is changing to support native sockets and this API will break.
Needed before https://github.com/adafruit/Adafruit_CircuitPython_NTP/pull/20

Use ESP32SPI directly instead of NTP

---

Macropad_Hotkeys/code.py

of the code were modified.**  
This change limited the scope of MacroPad Hotkeys to not look at the hidden filenames created by macOS (e.g. macOS will create a file named `._mac-safari.py` for a file named `mac-safari.py`
- **Describe any known limitations with your change.** 
I only tested this on macOS but this should not do any harm on any other platforms.
- **Please run any tests or examples that can exercise your modified code.** 
This works well on my mac. Without this change the serial console will display error messages about malformed macro format for these `._` files.

Ignored hidden filenames created by macOS.

---

CircuitPython_displayio/displayio_ondiskbitmap/code.py

This changes the ondiskbitmap code example embedded on this guide page: https://learn.adafruit.com/circuitpython-display-support-using-displayio/display-a-bitmap to use the newer circuitpython version 7+ method for creating the OnDiskBitmap. 
The <=6 fallback version has been removed. 
I also updated the one reference to similar code on this page: https://learn.adafruit.com/circuitpython-display-support-using-displayio/ui-quickstart

update ondiskbitmap usage for circuitpython 7+, remove fallback for 6

---

MagTag_Arduino_Demos/quotes/quotes.ino

The connection to the server consistently fails. Adding
`  client.setInsecure();'
before the request causes it to always succeed.
Above this code some certificate methods are commented out. They can't just be uncommented with the code as is.

Fix for consistent server connection failures

---

Adafruit_QT_Py_ESP32-S3/analog_in/code.py
Adafruit_QT_Py_ESP32-S3/cap_touch_one_pin/code.py
Adafruit_QT_Py_ESP32-S3/cap_touch_two_pins/code.py
Adafruit_QT_Py_ESP32-S3/digital_input/code.py
Adafruit_QT_Py_ESP32-S3/storage/boot.py

adding code examples for the qt py esp32-s3 guide

adding examples for qt py s3

---

NeoTrellis_MIDI_Feedback_Controller/code.py

changed the addresses for I2C to the "default" from the multitrellis guide photo.

default neotrellis addresses

---

Matrix_Portal_Eyes/code.py

Don't try to set the height property of Sprite, because [it now inherits it from displayio.TileGrid](https://github.com/adafruit/circuitpython/pull/5749).
Without that change we get the following error in CP 7.2.0 and later:
```py
Traceback (most recent call last):
File "code.py", line 68, in <module>
File "code.py", line 56, in __init__
AttributeError: 'Sprite' object has no attribute 'height'
```

Portal eyes: TileGrid has its own height property now

---

Walkmellotron/code.py

QT Py RP2040 + MCP4728 Quad DAC over STEMMA QT converts USB MIDI notes to control voltage for cassette player.

first commit walkmellotron code

---

GitHub_Actions_Status_Tower_Light/actions_status.py

Realised while testing that there was no contingency for cancelled Actions runs, and in fact the status light for queued/in progress would continue after the run was cancelled. Chose red blink for the light status for cancelled runs.

Added completed - cancelled code.

---

RGB_LED_Strips/code.py

The comment says that `FADE_SLEEP` is the time in milliseconds, but it's passed directly to `time.sleep`, which takes the time in seconds.
With a delay of 10 seconds it doesn't look like anything's happening – it'll take 15 minutes the first colour to fully fade in, This surely isn't what was intended.

RGB_LED_Strips: Change sleep from 10 seconds to 10 milliseconds

---

MetroX_CircuitPython/fading_led/code.py

This code was updated previously to use `pwmio` instead of `pulseio` but the comment remained mentioning `pulseio`
This change updates the comment to reflect the current version of the code.

update comment to reference pwmio instead of pulseio

---

ulab_Crunch_Numbers_Fast/waterfall/code.py

In 8.0, the TIleGrid adds its own "bitmap" property. This interfered, causing the exception reported in guide feedback:
```
Traceback (most recent call last):
File "code.py", line 59, in
File "code.py", line 40, in __init__
NotImplementedError: Call super().__init__() before accessing native object.
```

Don't use "bitmap" property of TileGrid objects

---

Hallowing_Jump_Sound/jump-sound/code.py
Hallowing_Jump_Sound/stomp-and-roar/code.py
PyPortal_MQTT_Control/code.py
PyPortal_Smart_Thermometer/code.py
PyPortal_User_Interface/code.py

CircuitPython 8 builds have dropped support for `Display.auto_brightness` (https://github.com/adafruit/circuitpython/pull/6734). These changes handle the attribute no longer being available in 8.x.x, while still working on 7.x.x.
We can't just simply remove the `board.DISPLAY.auto_brightness = False` lines, because then `board.DISPLAY.brightness = something` would not work, because `.brightness` changes are ignored when `.auto_brightness `is `True`.

handle no Display.auto_brightness

---

UART-Between-Boards/code.py

On Circuitpython before 8, UART.read() on NRF52 return `b''` instead of `None` if no byte was read.

update UART-Between-Boards guide to work around NRF52 bug before CP8

---

CircuitPython_Tandy1000Keyboard_QTPy_RP2040/code.py

This code will accompany the upcoming guide on using CircuitPython and an Adafruit QT Py RP2040  to hook a vintage Tandy 1000 keyboard to a modern computer over USB.

Tandy1000 keyboard

---

.github/workflows/images.yml

This change restricts the folder images workflow to only run in the adafruit fork of this repo so that they won't be generated / committed for other forks.

limit images workflow to adafruit fork

---

.github/workflows/githubci.yml

Addresses an issue where current release of ArduinoHttpClient fails Arduino CI due to syntax. Appears to be fixed in library’s main branch but not yet an updated release…when that occurs, this edit can be removed.

Override ArduinoHttpClient library

---

Mini_GIF_Players/Mini_GIF_Players.ino

This example was failing; I think it might be due to a new SdFat version, and that this might be the fix.

speculative fix for example build failure

---

.github/workflows/githubci.yml
.github/workflows/images.yml

The following warning is fixed:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

bump version of setup-python to fix deprecation warning

---

Mini_GIF_Players/Mini_GIF_Players.ino

SPIFlash v4 has updated to better support dynamic flash layout from Arduino IDE. The fixed CPY compatible is supported by new subclass `Adafruit_FlashTransport_RP2040_CPY`
related issue: https://forums.adafruit.com/viewtopic.php?p=946379#p946379

change default layout to use cpy compatible format for rp2040

---

.github/workflows/githubci.yml
.github/workflows/images.yml

.. the other one is haunted.  Closes #2327.
Also upgrades actions/checkout to one that doesn't warn
```
Warning: The `save-state` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Use a different concurrency group name

---

STEMMA_IR_LED_Emitter/code.py

Adding basic IR transmit example for the STEMMA IR LED emitter product guide.

adding basic IR CP example

---

PicoW_CircuitPython_HTTP_Server/code.py

This PR: https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/pull/25 changed the way imports for this library need to be coded. This PR changes to the new import syntax for the only current Learn project that uses the library. 
I've also added a print statement to print errors if they are caught so that they won't be silently consumed. This can make it easier to troubleshoot if something has gone wrong.

fix httpserver imports. print errors if they occur

---

CircuitPython_NeXT_Keyboard_RP2040/code.py
CircuitPython_NeXT_Keyboard_RP2040/next_keycode.py

In 2012, Lady Ada wrote a Learn project to convert a NeXT keyboard to USB with an Arduino Micro.
Now, ten years later, the keyboard is still as awesome as ever!  So awesome that for the anniversary we re-did the project with our favorite environment (CircuitPython) and an awesome microcontroller (RP2040)
In draft state for the moment, as I'm going to move the project from the Adafruit Feather RP2040 to the Adafruit QT Py RP2040 instead! It also doesn't handle sending vertical bar or backslash keys as those are in non-standard shifted locations.
This pull request text was typed on the NeXT keyboard!

Add NeXT to USB adapter with CircuitPython & RP2040

---

EYESPI/Arduino/Color/EYESPI_Test/EYESPI_Test.ino

Two different display drivers (ST7789, ILI9341) are currently used by EYESPI products, and perhaps more in the future. Rather than add same example to both display libraries (which would inevitably diverge), this creates a single example for _all_ color EYESPI products, selectable with a product ID #define at the top of the code. The naming of directories is such that other display types (mono OLED, eink, etc.) could get their own folders if those products get EYESPIified later.

Add EYESPI graphics example for Arduino

---

EYESPI/Arduino/Color/EYESPI_Test/EYESPI_Test.ino

Pins changed to match guide Fritz, and also swap two numbers that were in wrong spots, oops.

EYESPI: change default pins, fix corner radii

---

Mini_GIF_Players/Mini_GIF_Players.ino

- TFT_DC and TFT_CS pin numbers corrected for Arduino use. The incorrect CircuitPython numbers had been referenced (top side vs bottom side of RP2040 silkscreens).
- Resolves a known issue tof nothing appearing on TFT hat multiple forum users have run into.

updated TFT_CS / TFT_DC to Arduino pins

---

CircuitPython_Mastodon_API_Examples/Read_From_Mastodon/code.py
CircuitPython_Mastodon_API_Examples/Send_To_Mastodon/code.py
Scrolling_Alphanumeric_Countdown_Clock/code.py

Update some code comments that referred to `.env` so that they instead refer to `settings.toml`.
Reviewed solicited from either of you. Both not necessary.

update .env references to settings.toml

---

CPX_Simple_Simon/code.py

This makes the code for the Circuit Playground Simple Simon compatible with the CPB.
I don't think there is another version of it that already works ?
https://learn.adafruit.com/circuit-playground-simple-simon/code-walk-through
- use `cp` not `cpx` from the `adafruit_circuitplayground` library
- do not read the analog pin A7 (not available on CPB)
- reference `cp.touch_TX` (available on both) instead of `cp.touch_A7`
Also:
- fix the call to `game_lost()` which takes a step and not a sequence[setp]
- use a context manager to setup and deinit the analog pins
- some spaces at the end of lines

Make the CPX Simple Simon compatible with CPB

---

M4_Eyes/file.cpp

I noticed a failure during the overnight build.  It seems that `is<char *>` was deprecated and now removed. `is<const char *>` seems to be the new way. Only compile-tested. See https://arduinojson.org/v6/api/jsonvariant/is/

Fix for compatibility with arduinojson 6200

---

CircuitPython_SharpDisplay_Displayio/code.py

https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/82 Has been fixed and closed, this code is no longer necessary.

Remove unnecessary anchoring code

---

IoT_Button_BFF_Examples/CircuitPython_Basic_Example/code.py
IoT_Button_BFF_Examples/CircuitPython_Simple_IO_Example/code.py
IoT_Button_BFF_Examples/adafruitIO_iotButtonNeoPixelBFF/adafruitIO_iotButtonNeoPixelBFF.ino
IoT_Button_BFF_Examples/adafruitIO_iotButtonNeoPixelBFF/config.h
IoT_Button_BFF_Examples/basic_IoTButtonExample/basic_IoTButtonExample.ino

Adding CP and Arduino demo code for the IoT button BFF

adding demo code for IoT button BFF

---

Clue_Scale/clue_scale_calibrator.py
Clue_Scale/code.py

Changes to `code.py` and `clue_scale_calibrator.py`:
- Reduced sample average count because the driver now optimizes each acquisition cycle
- Replaced the statement used for checking Cycle Ready. It was calling an unset variable instead of the driver's bound method: `if nau7802.available:` changed to `if nau7802.available():`
Successfully tested on a Clue with the Adafruit NAU7802 Stemma breakout.
Will update the learning guide after this PR is approved.

Update to be compatible with latest version of NAU7802 driver

---

Pi_Hole_Ad_Blocker/mini_pitft_stats.py
Pi_Hole_Ad_Blocker/stats.py

The Pi-Hole server recently added authentication requirements for accessing info via their API:
https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required
This broke things for the older version of the Python scripts which were simply trying to access without authorizing:
https://forums.adafruit.com/viewtopic.php?t=197708
These code changes will go along with Learn Guide changes that will discuss how to find the `YOUR_API_TOKEN_HERE` value and update the code.
Tested with `stats.py` and a Pi OLED. Did *not* test the TFT version, but it uses the exact same API query.

Update to use API key in Pi-Hole Python scripts

---

MAX17048_and_LC709203F_Battery_Monitor_Test/MAX17048_and_LC709203F_Battery_Monitor_Test.ino

Adding a new battery monitor test code. Code determines whether or not the board has a MAX17048 or LC709203F chip.

Adding battery test code

---

README.md
pylint_check.sh

.. this allows a user to install the specific version of pylint required, under the specific name:
```
pipx install --suffix=-learn pylint==2.7.1
```
and run pylint_check more easily locally.

Use pylint-learn as the pylint version, if installed

---

pylint_check.sh

If you ran the pylint_check script not from the top directory, the correct pylintrc file wouldn't be used. This change adds the correct pylintrc file explicitly when running pylint.

Specify the right pylintrc file no matter where pylint_check is run

---

PicoW_CircuitPython_HTTP_Server/code.py

Fix for the latest releast of adafruit_httpserver library. 
I don't have all hardware needed to test the full project. But did run this code on a PicoW with the components I do have and confirmed it executes successfully with the latest version of the library once these changes are made. 
Might be worth waiting until tomorrow (04/25/23) so that the new bundle will be released that includes the new library. Until then the bundle currently includes the old version of the library which would require the current version of this project code rather than the edited one here in the PR. 
After tomorrow the bundle will contain the updated library and from then moving forward this modified code from this PR will be required.

add root_path argument to server init

---

Hexpad/code.py

A user found an error where note off messages were being sent for the wrong value -- `note` instead of `note_num` -- resulting in stuck notes. I fixed this and tested it, all should be right in the world of hexpad midi now.

fixed held note error in mono note mode

---

Canary_Nightlight/code.py

There's an issue with `time.monotonic()` on CircuitPython boards, where the float value loses precision over time, and eventually the time of "one" second begins increasing. If this project was running long enough, this would start to cause odd behavior. As well, the precision of the float (e.g. needing partial second values) is not necessary for this demo. Therefore, I switched from using `time.monotonic()` to using `time.time()` which is an int value, and therefore cannot lose precision. This should resolve any possibility of the odd behavior.

Switch type of time used

---

Meowsic_MIDI/code.py
TrellisM4_Simple_MIDI_UART/code.py

added `timeout=0.001` to UART MIDI examples, without it some systems (e.g., Metro M7) can exhibit long delays when receiving messages.

added UART timeouts

---

NeoKey_MX_and_CHOC_Breakouts/CircuitPython/HID/code.py

Before it meant that a key release would turn off both LEDs, even if the other key was still pressed. Now the release event only turns off the LED associated with that key.

Fix key release pixel effect.

---

Purple_Air_Display/code.py

Previous URL was discontinued (see https://community.purpleair.com/t/discontinuation-of-the-json-and-data-json-urls/713), so this fixes the code.

Update Purple Air Display to use new API

---

FunHouse_IOT_Hub/neopixel_remote/code.py

The if statement: 
```
if colors[index]:
```
Will evaluate to `False` for the color `BLACK` because it has a numerical value of `0` and zero is treated as "falsy" by python interpretation.  Due to that evaluating as false, it means that when the user clicks on the black square it will appear as if "nothing happens" because this if statement is preventing it from taking action. 
This change addresses that issue by checking against `None` specifically, which allows the case for `BLACK` or `0` to work as expected, while still filtering out any of the ones that are actually `None` 
I tested this change successfully with a PyPortal Titano `8.2.0-beta.0 `

Fix black square in the neopixel remote

---

Matrix_Portal_Moon_Clock/code.py

- Update for MET sun/moon API 3.0 (2.0 was deprecated and this project’s been broken for a while).
- Now uses Adafruit IO for time sync, and does so more frequently (~3 hr interval).
- User's secrets.py file requires additional entries with time zone and Adafruit IO credentials; I’ll document in the Learn guide after this is merged.

Matrix Portal Moon Clock update

---

Matrix_Portal_Learn_Stats/code.py

I noticed the guide count number was getting overlapped slightly with the scrolling names of recent guides. 
This change moves it up a few pixels in order to remove the overlap.

move the guide count text up slightly

---

CircuitPython_Templates/power_management_measuring_battery/code.py

Tested successfully on Feather ESP32-S2.

Add print to identify monitor type.

---

.github/workflows/arduino_cron.yml

Fixes #2559
Since adabot handles the actualy cron, the scheduling event type is not needed and instead the push event is.

Fix releases

---

.github/workflows/arduino_cron.yml

Since the cron is actually triggered by adabot and is a "push" event, this fixes the CI to trigger on said events.

Fix check for adabot scheduled release

---

CircuitPython_RGBMatrix/scroller/code.py

A forum user was seeing the following error with the CircuitPython_RGBMatrix two line scroller color scroller.
https://forums.adafruit.com/viewtopic.php?t=203685
```
ValueError: Tile height must exactly divide bitmap height
```
I was able to reproduce the same error on a MatrixPortal m4 with 64x32 display and found the fix was to change the tile_height from 14 --> 12.
```
def tilegrid(palette):
return displayio.TileGrid(
bitmap=terminalio.FONT.bitmap, pixel_shader=palette,
width=1, height=1, tile_width=6, tile_height=12, default_tile=32)
```
The forum user Azzura was also able to confirm this worked on their setup.

tile_height error changing from 14 to 12 for font

---

ESP32_S2_WiFi_Tests/CPy_Native_WiFi_Test/code.py
ESP32_S2_WiFi_Tests/CPy_Native_WiFi_Test/settings.toml

Since the settings.toml in this test is used in guide pages to represent the default setting.toml, it should use the correct names of the settings. See https://docs.circuitpython.org/en/latest/docs/environment.html#environment-variables. @kattni, since you last updated this file, I'll just tag you to ensure it doesn't break something.

Update settings.toml to use cp expected name

---

FunHouse_Motion_Outlet/code.py

While updating the code, I realized the guide expects this value should be set to True by default to make it easier for users and somehow it was changed to False along the way (probably while testing something).

Set Fan Motion Outlet code to use MQTT by default

---

ESP32_S2_WiFi_Tests/CPy_Native_WiFi_Test/code.py

- Fixed the code to properly handle timeout, as `ping()` returns `None` under that scenario and code throws an exception trying to multiply it by 1000 (converting s to ms). 
Also added a couple comments for further understanding of the code.
- This should preserve the logic,except for:
- Not running into exceptions
- Explicit message when (if) we timeout twice, could maybe add a loop for more retries...

[Small bugfix] ESP32 WiFi example

---

Factory_Tests/Qualia_ESP32S3_RGB666_FactoryTest/Qualia_ESP32S3_RGB666_FactoryTest.ino

Add Qualia S3 Factory Reset Source

---

Super_Nintendo_USB_Controller/boot.py
Super_Nintendo_USB_Controller/code.py

For Super Nintendo USB Controller guide: https://learn.adafruit.com/super-nintendo-usb-controller/overview
- Adds MIT licenses identifier to boot.py file.
- Adds default state for unused analog values.
- Comment correction for HID descriptor size.

adds small correction to Super Nintendo USB controller guide

---

Adafruit_Prop_Maker_FeatherWing/Prop_Maker_LED_Simpletest/Prop_Maker_LED_Simpletest.ino
FunHouse_Arduino_Demos/rainbow/rainbow.ino
FunHouse_Arduino_Demos/selftest/selftest.ino
FunHouse_Arduino_Demos/shipping_demo/shipping_demo.ino

Updates several Arduino examples to latest (3.x) ESP32 BSP that has a different API for LEDC. Older code left in place with new code added and surrounded with preproc logic.
All examples tested.

Update ESP32 Arduino examples for LEDC usage

---

Grand_Central_MIDI_Knobs/code.py

I had named the midi object the same as a library, oops! changed object name to `midi_usb` along w `midi_uart` for the other.

fixed  name to avoid confusion

---

Feather_RP2040_Prop-Maker_Lightsaber/code.py

Accelerometer range is basically hit detection sensitivity.  Had a beginner in Discord that didn't know how to change it because it's not documented in the learn guide.  Need a better way to make this parameter configurable and easy to use. Please also add something into the learn guide about using this for lowering sensitivity.  By default the lightsaber is set to 2G which is its most sensitive setting. Setting it to RANGE_4_G will decrease the sensitivity which is what they needed.

Add code comment for Accel Range (sensitivity)

---

Slider_Trinkey/MIDI_CC_Cross_Fader/code.py

There is likely a copy and paste mistake.
It is not visible because in the main loop it is likely overwritten.
There is also a "show" that is not needed as default is auto update.
Not tested because I don't have install midi library, but I saw the problem by copying the initialisation only... and noticing both LED were red despite different hue.
UPDATE: Tested without the midi code, and my version works.

Slider_Trinked MIDI: Typo for initial 2nd neopixel and show not needed.

---

CircuitPython_Zorque_Text_Game_openai/code.py

The underlying issue was resolved:
* https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/183

remove unneeded workaround

---

CircuitPython_Essentials/CircuitPython_I2C_Scan/code.py

A maybe better CircuitPython I2C scanner? Tries to be more automagic and *not* require user modification of source code to configure for different bus scenarios.
Example on a QT PY RP2040 with something on both header I2C and STEMMA QT I2C:
```python
Adafruit CircuitPython 8.2.6 on 2023-09-12; Adafruit QT Py RP2040 with rp2040
>>> import test
Checking board.I2C()...ADDED.
Checking board.STEMMA_I2C()...ADDED.
Checking busio.I2C(board.GP1, board.GP0)...SKIPPED.
----------------------------------------
I2C SCAN
----------------------------------------
board.I2C() addresses found: ['0x76']
board.STEMMA_I2C() addresses found: ['0x23']
board.I2C() addresses found: ['0x76']
board.STEMMA_I2C() addresses found: ['0x23']
board.I2C() addresses found: ['0x76']
board.STEMMA_I2C() addresses found: …
```

Update CircuitPython I2C scanner

---

CircuitPython_Essentials/CircuitPython_I2C_Scan/code.py
I2C_Scanners/arduino/i2c_scanner/i2c_scanner.ino
I2C_Scanners/circuitpython/code.py

This PR does several things:
* Reverts the code change from #2677 and moves it to a new location. This way the original simple scanner code can still be used for the Essentials guide and the new version, for use in the I2C Scanner guide, will live in its own location.
* Adds the new CP scanner code to the new location.
* Also adds the Arduino scanner code used in the I2C Scanner guide. This code is currently being hosted directly on the Learn page. So adding here to allow embedding.
The CP scanner code is also updated relative to the #2677 version. It now captures the exception and prints it so the reason the specific I2C bus is being skipped is shown. Here is an example of the new code with nothing attached:
```python
Adafruit CircuitPython 8.2.6 on 2023-09-12; Adafruit QT Py RP2040 with …
```

I2C Scanner Code Updates

---

CLUE_Light_Painter/boot.py
CircuitPython_Essentials/CircuitPython_Logger/boot.py
Crickits/flying_trapeze/boot.py
Crickits/yanny_or_laurel/boot.py
EInk_Autostereograms/boot.py
Introducing_Gemma_M0/Gemma_Logger_boot/code.py
Web_Workflow_Quickstart/env.py

Clarify calls to `storage.remount()` when `readonly` arg is given by always giving the `readonly` keyword. This is a tricky argument to get right. I'll tweak the guide pages after it's merged.

add readonly= keyword to storage.remount where not already present

---

NeoPixel_Fidget_Spinner/code.py

adding neopixel fidget spinner code for neopixel ring and seesaw ANO encoder

adding neopixel fidget spinner code

---

MatrixPortal_S3_Flight_Proximity_Tracker/code.py

`AREO_API_KEY` -> `AERO_API_KEY`
Noted by https://forums.adafruit.com/viewtopic.php?t=207064

MatrixPortal_S3_Flight_Proximity_Tracker: fix AERO_API_KEY typo

---

CircuitPython_ESP32_Camera/esp32-kaluga-onionskin-gif/code.py
CircuitPython_ESP32_Camera/esp32-s3-eye-adafruitio-and-lcd/code.py
CircuitPython_ESP32_Camera/esp32-s3-eye-adafruitio/code.py
CircuitPython_ESP32_Camera/esp32-s3-eye-lcdview/code.py
CircuitPython_ESP32_Camera/esp32-s3-eye-qrio-repl/code.py

This was renamed during the development of 8.x but examples weren't fixed.

Correct references to "esp32_camera"

---

MEMENTO/PyCamera_External_Shutter_Button/code.py

Adding code to adapt the memento camera library fancy example to use an external shutter button

Adding code for the external shutter button

---

MEMENTO/Wireless_Remote/code.py

MEMENTO code for Wireless Remote using TouchOSC

first commit wireless osc remote for memento

---

Walkmp3rson/code.py

there was a memory problem a forum user caught due to mp3 stream method being called repeatedly. tested the fix on hardware, works great.

fix to mp3 streaming code

---

PiCowbell_Adalogger_Examples/CircuitPython_Datalogger/code.py
PiCowbell_Adalogger_Examples/CircuitPython_Real_Time_Clock/code.py

Re this thread:
https://forums.adafruit.com/viewtopic.php?t=207734
The PCF8523 library made breaking changes at the 2.0.0 release:
https://github.com/adafruit/Adafruit_CircuitPython_PCF8523/releases/tag/2.0.0
This PR updates the PiCowbell examples to use the new syntax for importing and creating the rtc instance.
**NOT TESTED** dont have HW, relying on forum poster saying this fixed it

Update PiCowbell examples for new PCF8523 library layout

---

CircuitPython_Commodore_16_KB2040/advanced/code.py

... per https://github.com/adafruit/circuitpython/issues/8412 Otherwise this is incompatible with both 8.x and 9.

Update async keyboard code

---

NeoRGB_Stemma_Examples/arduino_rainbow_neorgb/arduino_rainbow_neorgb.ino
NeoRGB_Stemma_Examples/circuitpython/code.py

adding arduino and CP examples for the neorgb stemma breakout. CP example checks for raspberry pi

adding examples for the neorgb stemma breakout

---

Adafruit_IO_Power_Relay/code.py
Adafruit_IO_Power_Relay/code_light_sensor/code.py
Adafruit_IO_Schedule_Trigger/code.py
Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_wifi/code.py
CircuitPython_Zorque_Text_Game_openai/code.py
FunHouse_IOT_Hub/battery_peripheral/code.py
FunHouse_IOT_Hub/door_peripheral/code.py
FunHouse_IOT_Hub/neopixel_remote/feather_code/code.py
FunHouse_IOT_Hub/relay_heatindex_peripheral/code.py
FunHouse_IOT_Hub/relay_peripheral/code.py
MagTag/MagTag_Webb_Telescope_Status/code.py
MagTag/MagTag_Webb_Telescope_Status/deprecated_original_version/code.py
Metro_M7_Examples/WiFi/code.py
PyPortal/PyPortal_AWS_IOT_Planter/code.py
PyPortal/PyPortal_GCP_IOT_Planter/code.py
PyPortal/PyPortal_MQTT_Control/code.py
PyPortal/PyPortal_Quarantine_Clock/code.py
PyPortal/PyPortal_Quarantine_Clock/month_clock/code.py
PyPortal/PyPortal_Smart_Switch/code.py
PyPortal/pyportal_pet_planter/code.py
Webhook_Plant_Sensor/code.py
oshwa_magtag_display/code.py

Remove legacy `requests.set_socket` and replace with new `pool` and `ssl_context` helpers from [ConnectionManager](https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/)

Remove legacy requests.set_socket

---

Adafruit_IO_Power_Relay/code.py
Adafruit_IO_Power_Relay/code_light_sensor/code.py
Adafruit_IO_Schedule_Trigger/code.py
Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_wifi/code.py
CircuitPython_Zorque_Text_Game_openai/code.py
FunHouse_IOT_Hub/battery_peripheral/code.py
FunHouse_IOT_Hub/door_peripheral/code.py
FunHouse_IOT_Hub/neopixel_remote/feather_code/code.py
FunHouse_IOT_Hub/relay_heatindex_peripheral/code.py
FunHouse_IOT_Hub/relay_peripheral/code.py
Metro_M7_Examples/WiFi/code.py
PyPortal/PyPortal_AWS_IOT_Planter/code.py
PyPortal/PyPortal_GCP_IOT_Planter/code.py
PyPortal/PyPortal_MQTT_Control/code.py
PyPortal/PyPortal_Quarantine_Clock/code.py
PyPortal/PyPortal_Quarantine_Clock/month_clock/code.py
PyPortal/PyPortal_Smart_Switch/code.py
PyPortal/pyportal_pet_planter/code.py
Webhook_Plant_Sensor/code.py

Correct my mistake of using:
```
ssl_context = adafruit_connection_manager.create_fake_ssl_context(pool, esp)
```
to the right helpers:
```
pool = adafruit_connection_manager.get_radio_socketpool(esp)
ssl_context = adafruit_connection_manager.get_radio_ssl_context(esp)
```

Fix get_radio_ssl_context

---

.github/workflows/arduino_cron.yml
.github/workflows/githubci.yml
.github/workflows/images.yml

Update actions to remove warnings about needing to update to actions that use Node.js 20.
Also remove one redundant line.
Not sure about the reference to `softprops/action-gh-release`. That action hasn't been updated since November 2022.

update actions to use node.js 20

---

CircuitPython_sdcardio_sdioio/benchmark/code.py
CircuitPython_sdcardio_sdioio/list_files/code.py
CircuitPython_sdcardio_sdioio/log_temperature/code.py
CircuitPython_sdcardio_sdioio/play_mp3s/code.py

this import line was removed without checking, because it caused a pylint message. (24dacb7fe6c5d4702b8b81c59cfcea0a7b7ce416) -- the guide may need to be reviewed as well, to make sure usage of mount.py is explained (I'll tackle this next)

User must provide a mount_sd.py script

---

LTC4316_Examples/LTC4316_Arduino_Example/LTC4316_Arduino_Example.ino
LTC4316_Examples/LTC4316_CircuitPython_Example/code.py

Adding Arduino and CircuitPython examples using two AHT20 sensors with one translated to 0x68 with an LTC4316

adding ltc4316 examples with the aht20

---

PyPortal/PyPortal_AirQuality/code.py

I'm revising PyPortal guides to use `settings.toml`.

PyPortal_AirQuality: use settings.toml for AIRNOW_TOKEN

---

PyPortal/PyPortal_TOTP_Friend/secrets.py

This is part of updating the TOTP_Friend project to settings.toml. The wifi settings are now in settings.toml, but the keys reamain in secrets.py, because they are in a hierarchical structure.
By mistake, I committed the code.py changes directly instead of making a PR.
Guide already updated.

Update TOTP_Friend secrets.py

---

CPB_Keybutton_BLE/code.py

This code snippet threw me for a loop trying to understand what "961" meant. After a good amount of digging I found the appearance numbers in the bluetooth spec, to see that 961 is 0x03C1 or "keyboard".
Add a comment to hopefully guide future readers.
of the code were modified.**  
- This change simply adds a clarifying comment, the code is not changed at all
- **Describe any known limitations with your change.** 
- Just a comment, only limitation is the reader's literacy level 
- **Please run any tests or examples that can exercise your modified code.** 
- No tests to run, I assume the compiler will strip comments before executing the code

Explain magic number in BLE advertisement

---

FeatherCAN_CircuitPython/listener-ack/code.py
FeatherCAN_CircuitPython/sender-ack/code.py

the code.
Avoids the issue in https://github.com/adafruit/circuitpython/issues/3644
The STM32F405 Feather differes from the other adafruit CAN friendly boards because it has 3 "transmit mailboxes". The other boards seem to have only 1 tx buffer (not 100% sure about this). The current ack example does not work well on the stm boards after bus errors because it assumes the next received message will be after the most recent sent message, which is not the case because of these 3 transmit mailboxes. For example:
1. send 1, receive 1
2. send 2, receive 2
3. *can bus disconnection*
4. send 3, buffer (tx mailbox0)
5. resend 3, buffer …

make feather can ack example work with stm32f405

---

Keypad_Examples/macropad_simple/code.py

This code is the code that is meant to be in this example: https://learn.adafruit.com/key-pad-matrix-scanning-in-circuitpython/keys-one-key-per-pin#macropad-example-3099041. By mistake, the code at that example links to the HID example code (which is the example below).
I'll fix the code link when this is merged.

Add simple keypad macropad example

---

Macropad_Hotkeys/code.py
Macropad_Hotkeys/macros/zzz_blank.py

The MacroPad stays active including screen and lights even when the computer it is attached to, goes to sleep. 
This change provides a blank screen, sets all RGB lights to black and disables the bright background of the title bar when the title is empty (as on the blank screen).

Add blank screen usable when idle

---

Macropad_Hotkeys/macros/zzz_blank.py

We added the SPDX requirement after that PR was submitted, so the PR run only failed after the merge.

add spdx to recently merged file

---

Macropad_Hotkeys/code.py

of the code were modified.**
For the MacroPad Hotkeys project the "app name" is touching the top of the header bar.
As there is "enough" space this change makes the header bar one pixel higher and moves the text 2 pixels down.
This tiny changes improves the vertical aligment of the "app name". 
- **Describe any known limitations with your change.**
Applies only to the "MacroPad Hotkeys project / code".

Move app name a few pixel down for better vertical alignment

---

PiCowbell_Camera_Demos/TFT_Viewer/code.py

Adding a try/except for picowbell camera demo in case a memory allocation issue occurs with the pico w.

adding try/except for picowbell camera

---

QT_Py_Media_Controller/code.py

Adding code for media controller project using a qt py and stemma rotary encoder to send media consumer control messages

Adding code for media controller

---

Tripler_PiCowbell_Demos/Arduino_PiCowbell_Tripler_Demo/Arduino_PiCowbell_Tripler_Demo.ino
Tripler_PiCowbell_Demos/CircuitPython/code.py

CircuitPython and Arduino demos for the PiCowbell Tripler

picowbell tripler demos

---

TRRS_Trinkey_Demos/CircuitPython_Analog_Mouse/code.py
TRRS_Trinkey_Demos/CircuitPython_Analog_Mouse/settings.py

analog mouse demo from ATMakers for TRRS Trinkey

analog mouse demo

---

Drum_Track_Sequencer/code.py

optical sensor drum track sequencer

first commit drum track sequencer

---

TSMP96000_Demo/TSMP96000_Demo.ino

Demo code for the TSMP96000 code learner ir receiver

adding demo for the TSMP96000

---

CircuitPython_Sound_Box_2/code.py

adding ability for multiple "shake" activated sound effects

update for sound box

---

SHT4x_Trinkey_Demos/CircuitPython/sht4x_temp_humidity/code.py

guide feedback for sht4x trinkey guide said error was being thrown for the main CP demo. seems that sht41 sensors have an overflow when calling the serial_number while sht45 sensors do not. commenting out the line for now for the guide and opening an issue in the library.

Update SHT4x trinkey demo

---

Feather_RP2040_Adalogger/Arduino_RP2040_Adalogger_microSD/Arduino_RP2040_Adalogger_microSD.ino
Feather_RP2040_Adalogger/CircuitPython_SD_Card_Read/code.py
Feather_RP2040_Adalogger/CircuitPython_SD_Card_Write/code.py

Adding sd card demos for the RP2040 Adalogger

adding sd card demos

---

LED_Bullwhip/code.py

The Feather Sense used in this project has two different versions. The LSM6DS changed in January 2024 from the LSM6DS33 to the LSM6DS3TR-C. They have slightly different initialization. The guide code.py has been modified to support both versions. 
This has been tested on two of the new versions of the Feather Sense (new models) by two people and shown to run.

LED Bullwhip update for Feather Sense LSM6DS

---

CLUE_Light_Painter/bmp2led.py

Single line change to accommodate different behavior with ulab processing arrays in CircuitPython 9.x. The example guide code had been failing after CP8.x.
```
BLE:Reconnecting | code.py | 9.0.5\Traceback (most recent call last):
File "code.py", line 555, in <module>
File "code.py", line 546, in run
File "code.py", line 245, in load_image
File "bmp2led.py", line 342, in process
OverflowError: value must fit in 1 byte(s)
BLE:Reconnecting | 342@bmp2led.py OverflowError | 9.0.5\
```
This has been tested with a CLUE nRF52840 on CP 9.0.5. Also with a CPB. Both myself and [adafruit forum user JayPi](https://forums.adafruit.com/viewtopic.php?t=211550) have verified this stops the crashing and the code runs as expected. 
```
err = [int(min(max(0, e), 255)) for e in err]
```

CLUE Light Painter ::  bmp2led.py

---

CNC_MacroPad/code.py

cnc macropad code update

---

Soundboard_Scooter_Bike/code.py

The [Soundboard Speaker for Bikes & Scooters](https://learn.adafruit.com/soundboard-speaker-for-bikes-scooters) has a discrepancy between the Circuit Diagram and the Code. 
This small code.py change from:
`audio = audiobusio.I2SOut(board.RX, board.TX, board.D9)
`
to:
`audio = audiobusio.I2SOut(board.TX, board.RX, board.D9)
`
swaps the bit clock and word select pins so the Circuit Diagram is correct. 
This came up in a [lengthy forum issue](https://forums.adafruit.com/viewtopic.php?t=212333) and resolved the problem.

Soundboard Speaker I2S fix

---

CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py

As reported in Slack, JP found the IO site doesn't match the code in the boards learn guides for using Circuitpython with Adafruit IO.
This updates the code in line with the newest version of the field name

Correct field names for Adafruit IO to match website

---

PyPortal/PyPortal_Wheres_My_Friend/code.py

Fixes: 
- Resolve edge case: Bootup with no data on a feed is now signaled to the user correctly and tested
- Fix typo: `SLEEP_DELAY_SECONDS`->`SLEEP_DELAY_MINUTES`
- Remove debug `text` for label `text_area_location`

Fix: Where's my friend

---

CircuitPython_Day_2024_Projects/Blinka_NeoPixel_Countdown/code.py

adding Blinka NeoPixel countdown code. time is fetched from IO. when 16 or less days are remaining until the event, the neopixels light up one by one

adding Blinka NeoPixel countdown code

---

CircuitPython_Day_2024_Projects/Qualia_820x320_IO_Countdown/code.py

This changes the demo minorly to still restart the code safely and get the user back online. There's a comment to explain why and I'll change the code back to microcontroller.reset once the bug is fixed (https://github.com/adafruit/circuitpython/issues/9496)

Use supervisor.reload instead of microcontroller.reset as it's broken for Qualia in 9.1.1 with tinyUF2 0.18.2

---

USB_Host_BFF_Examples/CircuitPython_DeviceInfo_FeatherWing/code.py

Adding device info circuitpython example for usb host featherwing

adding usb host featherwing example

---

USB_C_Power_Deliverer/code.py

first commit guide code for power deliverer

first commit guide code for power deliverer

---

BLE_RS232_Controller/code.py

CircuitPython code for the ESP32-S3 BLE RS232 controller

code for BLE RS232 controller

---

Feather_DVI_Arduino_Video_Synth/Feather_DVI_Arduino_Video_Synth/Feather_DVI_Arduino_Video_Synth.ino

Adding test onlys as a patch for espressif bsp rc and error from picodvi library

adding test onlys as workarounds

---

Feather_TFT_Blinka_Says/code.py

Code for the guide that I am working on.

Blinka Says Game

---

DOOM_Keeb/code.py

first commit doom keyboard code

first commit doom keyboard code

---

Qualia/Qualia_S3_iOS_Photo_Frame/code.py

Uses MQTT with Adafruit IO to decode and display base64 encoded photos

code for Qualia iOS Photo display

---

HID_Reporter/USB_Host_HID_Reporter/.theia/launch.json
HID_Reporter/USB_Host_HID_Reporter/USB_Host_HID_Reporter.ino
HID_Reporter/USB_Host_HID_Reporter/usbh_helper.h

first commit hid reporter code

Hid reporter

---

Matrix_Portal_itsaSNAP_Apple_Health_Display/code.py

Added code.py file for itsaSNAP Apple Health Learn guide

itsaSNAP Apple Health Learn guide

---

Zelda_Tri_Rod_Prop/code.py

minor updates for zelda prop code. number of neopixels and vertical detection time

updates for zelda prop

---

USB_Host_Turbo_Button_Gamepad/Arduino_USB_Host_Turbo_Button_Gamepad/Arduino_USB_Host_Turbo_Button_Gamepad.ino
USB_Host_Turbo_Button_Gamepad/Arduino_USB_Host_Turbo_Button_Gamepad/gamepad_reports.h

updating code so that it's easier for folks to set custom combos. also improved multi button press detection

easier combo setting

---

Haunt_Air_Blaster/code.py

first commit  code for Haunt Air Blaster Learn Guide

first commit air blaster code

---

TFT_Spirit_Board/esp32s3_s2_tft_featherwing_480x320/spirit_board.py
TFT_Spirit_Board/pyportal/spirit_board.py
TFT_Spirit_Board/pyportal_titano/spirit_board.py

After some further testing and recording an introduction video for the project I found a few more tweaks to make:
- add `delay` argument to `write_message()` that gets passed through to `slide_planchette()`
- catch an additional possible type of exception that can be raised by the AdafruitIO fetch attempt

Spirit Board Tweaks

---

TFT_Spirit_Board/esp32s3_s2_tft_featherwing_480x320/spirit_board.py
TFT_Spirit_Board/esp32s3_s2_tft_featherwing_480x320/spirit_messages.txt
TFT_Spirit_Board/pyportal/spirit_board.py
TFT_Spirit_Board/pyportal/spirit_messages.txt
TFT_Spirit_Board/pyportal_titano/spirit_board.py
TFT_Spirit_Board/pyportal_titano/spirit_messages.txt

A few more improvements based on feedback from JP.
- Included the `spirit_messages.txt` file in the project so the user can modify an existing file instead of having to create it. This should make it also appear on the drive structure screenshots as well I believe.
- Handle uppercase characters in the message by moving everything to lowercase before looking up the location in the dictionary map (which has all lowercase keys)
- More gracefully handle invalid characters that aren't on the spirit board. Previously the code would raise an exception when it attempts to lookup the character in the locations dictionary. Now it will print out a message in the serial output and skip the invalid character moving on to the next character in the message.

Spirit Board Improvements

---

EInk_Bonnet_Weather_Station/code.py

Minor changes to [EInk Bonnet 2.13 Weather example](https://learn.adafruit.com/raspberry-pi-e-ink-weather-station-using-python/weather-station-code) code to work with latest display ssd1680z update. Hardware change in August of 2024 required an [ssd1680z subclass addition to library](https://github.com/adafruit/Adafruit_CircuitPython_EPD/pull/83). 
Forum user @luisrh01 who initially pointed this out has [tested code as well as myself on a Pi 5's](https://forums.adafruit.com/viewtopic.php?t=213959) running Bookworm and it is working as expected.

adding ssd1680z to Eink Weather Example

---

ESP32-S2_TFT_Color_Detection/code.py
itsaSNAP Color Detection/code.py

This is a program for a color detection project using the APD-9960 and Feather ESP32-S2 & S3

ESP32-s2 tft color detection with itsaSNAP

---

CircuitPython_Karel_The_Robot/karel/circuitpythonkarel.py

I accidentally tested with `karel/` in the wrong location on my device at first and missed this. The code can be simplified and fix the sprite loading by hardcoding the directory to match the structure of the project code.

Fix for Karel

---

TMC2209_Examples/Arduino_TMC2209/Arduino_TMC2209.ino
TMC2209_Examples/CircuitPython_TMC2209/code.py

cc @BlitzCityDIY 
Almost the same as A4988 ones, but different default microstep value.

tmc2209 examples

---

Sparkle_Motion_Mini_Examples/CircuitPython_Sparkle_Motion_Mini_Neopixel_Animation/code.py

two neopixel animations running on each of the outputs.

sparkle motion mini example

---

Custom_LED_Animations/conways/conways.py

Change based on learn guide feedback.
I confirmed this version runs successfully on a feather rp2040 + dotstar featherwing.

fix grid x/y access

---

MEMENTO/IoT_Bird_Feeder/code.py

The `encoded_data` is now converted explicitly, rather than implicitly - which seems to not work on the latest CircuitPython build, to a string.

Fix: IoT Bird Feeder 

---

Hallowing_Jump_Sound/jump-sound/code.py
Hallowing_Jump_Sound/stomp-and-roar/code.py

Updates code from this guide:
https://learn.adafruit.com/last-minute-halloween-accoutrements-with-hallowing
* Update imports for new MSA3xx library name
* Support both MSA301 and MSA311 Hallowing M4's
Re this thread:
https://forums.adafruit.com/viewtopic.php?t=216212
Tested with both a MSA301 and MSA311 HalloWing M4.

Update HalloWing jump sound

---

Sparkle_Motion_Examples/CircuitPython_Sparkle_Motion_IR_Remote/code.py

While working on the rest of the page this belongs to I realized the pin and LED count were incorrect, this corrects them.

sparkle motion IR remote corrected neopixel pin & count

---

Adafruit_ESP32_Arduino_Demos/ESP32_sleeptest/ESP32_sleeptest.ino

Tiny fix of a comment about turning OFF the I2C power.

docs: fix comment when turning off I2C power

---

ESP32-S2_TFT_AS7341_Color_Detection/code.py

This is a program for a color detection project using the AS7341 and Feather ESP32-S2 & S3

Added code.py for AS7341 Color detection

---

Daily_Cheer_Automaton/CircuitPython/code.py
Macropad_2FA_TOTP/code.py
Macropad_2FA_TOTP/rtc_setter.py
Pulse_Oximeter_Logger/code.py
blahaj/code.py

Several example files incorrectly `import adafruit_pcf8523` and do `rtc = adafruit_pcf8523.PCF8523(I2C)` when they should `from adafruit_pcf8523.pcf8523 import PCF8523` and `rtc = PCF8523(I2C)`. This PR corrects these imports and makes no other changes. I don't own the various bits of hardware necessary to test these examples, but my changes here *should* have no other impact.

quick fix broken imports/calls of pcf8523

---

Espresso_Water_Meter/code.py

updated to power down sensor during deep sleep

updated espresso code to power down sensor

---

Pico_W_CircuitPython_WiFi_Examples/Pico_W_Adafruit_IO/code.py
Pico_W_CircuitPython_WiFi_Examples/Pico_W_Azure_IoT_Central/code.py
Pico_W_CircuitPython_WiFi_Examples/Pico_W_Basic_WiFi_Test/code.py
Pico_W_CircuitPython_WiFi_Examples/Pico_W_JSON_Feed/code.py
Pico_W_CircuitPython_WiFi_Examples/Pico_W_Requests/code.py

Adding error handling for settings.toml to pico w wifi examples. if a settings.toml entry is not found/incorrect then a type error is raised but it isn't very descriptive, especially for beginners

adding error handling for settings.toml

---

Feather_RP2040_USB_Host/CircuitPython_GamePad_ReadData/code.py

Example for reading data from a generic USB game pad on the Feather RP2040 USB Host

USB Host gamepad read data example

---

Adafruit_Feather_ESP32-S2/BME280_LC709203_Adafruit_IO/code.py
Adafruit_Feather_ESP32-S2/BME280_LC709203_Simple_Data/code.py
Adafruit_Feather_TFT_ESP32-S2/LC709203_Adafruit_IO/code.py
Adafruit_Feather_TFT_ESP32-S2/TFT_GitHub_Stars/code.py
Adafruit_IO_Air_Quality/code.py
Adafruit_IO_Power_Relay/code.py
Adafruit_IO_Power_Relay/code_light_sensor/code.py
Adafruit_IO_Schedule_Trigger/code.py
Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_wifi/code.py
Azure_Food_Scale/code.py

Round of removing secrets from learn guides
- /BME280_LC709203_Adafruit_IO/code.py
- found on https://learn.adafruit.com/adafruit-esp32-s2-feather/i2c-on-board-sensors
- shows example of `secrets.py `
- no changes needed from code updates
- /BME280_LC709203_Simple_Data/code.py
- found on https://learn.adafruit.com/adafruit-esp32-s2-feather/i2c-on-board-sensors
- shows example of `secrets.py `
- no changes needed from code updates
- LC709203_Adafruit_IO/code.py
- **CAN NOT FIND** 
- TFT_GitHub_Stars/code.py
- found on https://learn.adafruit.com/adafruit-esp32-s2-tft-feather/tft-github-stars-wifi-demo
- shows example of `secrets.py `
- no changes needed from code updates
- found on https://learn.adafruit.com/diy-air-quality-monitor/
- shows example of `secrets.py `
- walks through `from …

Secrets Cleanup: A

---

Metro/Metro_RP2350_Snake/code.py

With these changes both capital and lower case will for work all key bindings that the game uses, no matter whether the user has defined the mapping variables with upper or lowercase character strings.

Update snake game key inputs

---

Two_Way_Servo_Telegraph/code.py

When creating feeds, also add the first value to avoid an error at the start. The problem is that the following error is raised at line 76:
```
Zurückverfolgung (jüngste Aufforderung zuletzt): Datei "code.py", 
Zeile 74, in <module> Datei "adafruit_io/adafruit_io.py", 
Zeile 707, in receive_data Datei "adafruit_io/adafruit_io.py", 
Zeile 588, in _get Datei "adafruit_io/adafruit_io.py", 
Zeile 554, in _handle_error AdafruitIO_RequestError: Adafruit IO Error 404: not found - API documentation can be found at https://io.adafruit.com/api/docs
```
if the feed is there but no values. I just took the average value and push it directly when creating the feeds.
Tested under the same hardware configuration as described in the instructions: …

When creating feeds, also add the first value

---

Matrix_Portal/Matrix_Portal_Learn_Stats/code.py

This pull request includes updates to the `Matrix_Portal/Matrix_Portal_Learn_Stats/code.py` file to adjust the data source URL and modify the JSON traversal key for guide information.
Learn Feedback
```
https://learn.adafruit.com/api/guides/new.json?count=5 display 1181 learn guide, but https://learn.adafruit.com/guides/latest say there are "2942 tutorials in group"
So it seems that the json file is stuck in 2020.
```

Update Matrix Portal New Guide Scroller Code.py

---

Adafruit_IO_Stepper_Control/code.py

Updates `isAlive` to `is_alive`, reflecting the Adafruit_CircuitPython_MotorKit library

Fix - Adafruit IO Stepper Control Guide

---

USB_SNES_Gamepad/CircuitPython_USB_Host/code.py

I think the `USB_SNES_Gamepad` folder that I put this inside of was originally meant for a single guide rather than a collection of them like `Metro` and other top level category folders.  But I figured there is no harm in making this one a subdirectory inside of there since the name still fits perfectly and this allows us to save a directory at the top level github limit.
I can move it instead though out to the root directory or somewhere else if there is somewhere more appropriate.

adding circuitpython example for USB Host with SNES like gamepad

---

Metro/Metro_RP2350_Minesweeper/code.py
Metro/Metro_RP2350_Minesweeper/gamelogic.py
Metro/Metro_RP2350_Minesweeper/menu.py

This improves minesweeper by adding some checks to avoid getting into an error state as well as showing the selected difficulty menu item.

Minesweeper improvements

---

Adafruit_IO_Reed_Switch/rpi-pico-w112213141.json

Adafruit IO devices wippersnapper config exported as JSON for easy import.
https://learn.adafruit.com/iot-open-door-detector-using-notifications-with-adafruit-io

Add exported Magic config for IOT Door sensor

---

Metro/Metro_RP2350_CircuitPython_Matrix/code.py
Metro/Metro_RP2350_Match3/match3_game/code.py
Metro/Metro_RP2350_Match3/match3_game/match3_game_helpers.py
Metro/Metro_RP2350_Match3/tilepalettemapper_demo/code.py

update code for the new TilePaletteMapper API from https://github.com/adafruit/circuitpython/pull/10318
Also updated the CircuitPython Matrix code to request the smaller display resolution so that it draws fewer total characters and refreshes faster.

Tilepalettemapper api update

---

Factory_Tests/Adafruit_Sparkle_Motion_Stick_FactoryTest/Adafruit_Sparkle_Motion_Stick_FactoryTest.ino

adding factory reset for sparkle motion stick

factory reset for sparkle motion stick

---

Sparkle_Motion_Examples/Arduino_Sparkle_Motion_Multi_NeoPixels/Arduino_Sparkle_Motion_Multi_NeoPixels.ino
Sparkle_Motion_Mini_Examples/Arduino_Sparkle_Motion_Mini_Multi_NeoPixels/Arduino_Sparkle_Motion_Mini_Multi_NeoPixels.ino

I believe this change should resolve this actions failure resulting from a warning about comparing signed with unsigned types: https://github.com/adafruit/Adafruit_Learning_System_Guides/actions/runs/15316694255/job/43091814706#step:7:902
The issue boils down to `Adafruit_Neopixel.numPixels()` returning an unsigned value, but `int i = 0` from the loop variable being signed. 
I tested the modified version successfully on the sparkle motion mini with two 1x8 NeoPixel strips.

fix for sparkle motion mini warning

---

LED_Matrix_Clock/code.py

move audio playback call so that it isn't cut off and add a state to turn alarm functionality on/off

update for led matrix clock

---

Pi_Hole_Ad_Blocker/mini_pitft_stats.py
Pi_Hole_Ad_Blocker/stats.py

A lot has changed since this guide was released.
Pi Hole 6.x had a major update around March 2025 which dramatically changed the API.
This code was tested and work with a MiniPiTFt on a Pi 4. I'd like to update the guide to support accommodate the software updates.
```
+-------------------------------------------------------+
|                   Summary of Changes                  |
+-------------------------------------------------------+
| Updated API endpoint to /api/stats/summary            |
| Modified ST7789 constructor signature                  |
| Adjusted PIL buffer size to 240×135                    |
| Removed extra rotation argument in disp.image call     |
| Changed JSON keys to data["queries"]["…"] and ["clients"] |
| Expanded exception handling for network/JSON errors …
```

pi-hole / bookworm / st7789 changes

---

Metro/Metro_RP2350_Matching_Game/code.py
Metro/Metro_RP2350_Matching_Game/gamelogic.py

This fixes quite a few mouse-related bugs and privatizes a bunch of functions that didn't need to be public.

Fix many bugs

---

MEMENTO/Memento_Face_Detect_Recognize/memento_platformio_camera/lib/Adafruit_PyCamera/Adafruit_PyCamera.cpp
MEMENTO/Memento_Face_Detect_Recognize/memento_platformio_camera/lib/Adafruit_PyCamera/Adafruit_PyCamera.h
MEMENTO/Memento_Shoulder_Robot/platformio_memento_shoulder_camera/lib/Adafruit_PyCamera/Adafruit_PyCamera.cpp

cardSize() is removed from upstream, although we enabled backward-compatible (up coming release). It is still better to use sectorCount() instead
also include SdFat_Adafruit_Fork.h instead of SdFat.h

replace cardSize() with sectorCount()

---

Metro_RP2350_Examples/CircuitPython_SDCard_ListFiles/code-cp10x.py
Metro_RP2350_Examples/CircuitPython_SDCard_ListFiles/code.py
Metro_RP2350_Examples/CircuitPython_SDCard_Write/code-cp10x.py
Metro_RP2350_Examples/CircuitPython_SDCard_Write/code.py

Demo code for CircuitPython 10.x SD card list and write. The 9.x examples are not compatible.
Addresses CircuitPython Issue # [10419](https://github.com/adafruit/circuitpython/issues/10419)
Addresses Forum Issue: [SD Card on Metro RP2350 Setup](https://forums.adafruit.com/viewtopic.php?p=1058272#p1058272)
CircuitPython 10.x introduces automounting of /sd. The Metro RP2350 no detects and automounts a /sd card using SDIO. No initialization is required in the example code. Example code for 9.x and 10.x will need to be in place for some time to prevent mass hysteria. 
Tested on both 10.x read / write scripts with:
```
+------------------------+-------------------------+
| Component              | Details                 |
+------------------------+-------------------------+
| Board …
```

Metro RP2350 CP 10.x /sd

---

AS5600_Magnetic_Encoder/code.py

CircuitPython code to control CC volume with a magnet and AS5600 sensor

code for AS5600 encoder project

---

ESP-NOW_basics/espnow_transceiver.py

fixed status_label looping and error message timing

---

Fruit_Jam/Larsio_Paint_Music/sound_manager.py
Fruit_Jam/Larsio_Paint_Music/sprite_manager.py
Metro/Metro_RP2350_Chips_Challenge/code.py
Metro/Metro_RP2350_Chips_Challenge/game.py
Metro/Metro_RP2350_Chips_Challenge/savestate.py

This pull request addresses the issues identified in https://github.com/adafruit/Fruit-Jam-OS/issues/32.
1) The "Fonts" and "Sounds" files were accessed using an absolute path from the root directory, this PR modifies that so the files are accessed from a relative path from the directory the code.py file is executed from. This should not have any impact on running the standalone code file as described in the learn guide but will also allow the code to be run from a sub folder as is done in Fruit Jam OS.
2) The original code used specific pins wired to the TLV320DAC3100 I2S audio breakout. This PR first attempts to initialize the DAC using typical pin names for boards that have built in I2S boards and only if that fails, falls back to the original pins defined in the learn guide.
3) The …

Generalizations on Metro_RP2350_Chips_Challenge  for Fruit Jam

---

Metro/Metro_RP2350_Minesweeper/code.py

When both a USB keyboard and a USB mouse are connected to a Fruit Jam, "most" times, the mouse did not work. If you removed the USB keyboard then the mouse always worked, however in order to start the game in this mode you need to have a serial connection to a host computer running the terminal.
I believe the issue was that the loop that searched for the mouse hardware stopped on the first device it found (EDIT: actually it always assigns the last device found as a mouse... either way, this should fix it). I've taken the test from Larsio_Paint_Music and used it in that loop to allow the program to skip over devices that don't appear to be mice.
This change allows the Minesweeper game to be run on the Fruit Jam when it's not connected to a host computer.

Add check to skip over keyboard
