adafruit/Adafruit_Learning_System_Guides

Piano_In_The_Key_Of_Lime/PianoInTheKeyOfLime.py
Code is explained in detail in guide.
=> Comments removed

Gordon_Cole_MP3_Player/Gordon_Cole_MP3_Player.ino, Gordon_Cole_MP3_Player/LICENSE, Gordon_Cole_MP3_Player/README.md
=> re-added Godron Cole MP3 Player 

Gordon_Cole_MP3_Player/Gordon_Cole_MP3_Player.ino
added some filtering to deal with so pot. much noise. wow.
=> volume fix for Gordon Cole MP3 Player

Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_AudioFiles_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_AudioSine_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_Blinky_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_CapTouch_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_DigitalIO_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_DigitalIO_example1_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_DigitalIO_example2_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_LightSensor_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_Neopixel_cpx.py, Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_Temperature_cpx.py
These are examples of the same code in the Intro to Circuit Playground Express learn guide Circuit Python section using the `cpx` API.
=> Examples from Intro Guide using cpx express API

CircuitPython_Hardware_SD_Cards/hello.py, CircuitPython_Hardware_SD_Cards/sdmount.py, CircuitPython_Hardware_SD_Cards/sdmount_lib.py
These files are examples of how to  execute code or store library modules on the SDCard
=>  add files for SD Card Guide

Digital_Sand_Dotstar_Circuitpython_Edition/README.md, Digital_Sand_Dotstar_Circuitpython_Edition/digitalsand.py
Code to accompany this tutorial:
https://learn.adafruit.com/digital-sand-dotstar-circuitpython-edition
=> https://learn.adafruit.com/digital-sand-dotstar-circuitpython-edition

Digital_Sand_Dotstar_Circuitpython_Edition/digitalsand.py
Updated code to reflect change in driver.
=> Refactored to follow driver update

CircuitPython_Quick_Starts/CircuitPython_Digital_In_Out.py
Created CircuitPython_Quick_Starts folder in Learn repo for all the updated code. Updated DigitalIO example.
=> CP quick start DigitalIO update

CircuitPython_Quick_Starts/CircuitPython_PWM_Piezo.py, CircuitPython_Quick_Starts/CircuitPython_PWM_Piezo_simpleio.py
=> adding PWM piezo examples

CircuitPython_Quick_Starts/CircuitPython_DotStar.py, CircuitPython_Quick_Starts/CircuitPython_NeoPixel.py, CircuitPython_Quick_Starts/CircuitPython_NeoPixel_RGBW.py
Added `rainbow_cycle` into DotStar example. Set `auto_write=False` to speed up `rainbow_cycle`. Added all necessary `pixels.show()`.
=> Updates to rainbow_cycle

CircuitPython_TVBGone/cpx_main.py
=> move frequency set to later

Arduino_Ethernet_SD_Card/README.md, Arduino_Ethernet_SD_Card/SDWebBrowse/SDWebBrowse.ino, Arduino_Ethernet_SD_Card/SDcardTest/SDcardTest.ino, Arduino_Ethernet_SD_Card/SDfileList/SDfileList.ino
Yes, he can use Github. This is the code for the revised tutorial from ladyada.net to the Adafruit Learning System.
=> Add files for Adafruit Ethernet SD Card Tutorial

Arduino_Ethernet_SD_Card/SDWebBrowse/SDWebBrowse.ino
The new code behaves better but does not implement a true recursive clickable directory tree. See the ls capability in the SD library which does iterate over all files. This code will not recurse to further depth than one. Cleaver coders who wish to fiddle with this are welcome to get the code and submit a request with your edits.
=> Update code to show subdirectories

PMS5003_Air_Quality_Sensor/PMS5003_CircuitPython/main.py
tested on a metro m4 w/cpy 3a6
=> fix possible overrun & add circuitpy3 compatibility

Arduino_Ethernet_SD_Card/SDWebBrowse/SDWebBrowse.ino
Code by Ladyada to serve web files including multiple levels of subdirectory.
Default is fixed IP address specified by user but can change to a router-served DHCP address.
=> Full recursion in directory browse

motorized-turntable/turntable.py
Code that accompanies the motorized turntable guide in the Adafruit Learning System.
=> Code for the guide Motorized Turntable

EPROM_Emulator/LICENSE.md, EPROM_Emulator/README.md, EPROM_Emulator/debouncer.py, EPROM_Emulator/directory_node.py, EPROM_Emulator/emulator.py, EPROM_Emulator/main.py
In support of an upcoming guide.
=> Add code for Astels' "Digital Circuits 6: EPROM Emulator" project guide

Starry_Night/starry_night.py
CircuitPython code for Circuit Playground Express and Crickit for the Adafruit Learning System Guide Starry Night by Dano
=> Code for Starry Night Guide

Crickits/trash_panda/code.py
=> trash panda party

Trash_Panda/code.py
This code accompanies the Adafruit Learning Guide for the Trash Panda. An Adafruit Crickit robotics board is teamed up with a Circuit Playground Express to create a fun cardboard robot.
=> Initial post for the Trash Panda CircuitPython code

CircuitPython_Made_Easy_On_CPX/cpx_slide_switch.py, CircuitPython_Made_Easy_On_CPX/cpx_slide_switch_red_led.py, CircuitPython_Made_Easy_On_CPX/cpx_temperature_neopixels.py
=> Updated and added new code

CircuitPython_Made_Easy_On_CPX/cpx_tap.py, CircuitPython_Made_Easy_On_CPX/cpx_tap_red_led.py
=> Changed print in tap code

Crickit_Stumblebot/code.py
This code accompanies the Adafruit Learning System tutorial for the Stumble Bot. Go to learn.adafruit.com to find all of Adafruit's learning guides.
=> Initial code commit

CircuitPython_Made_Easy_On_CPX/cpx_neopixel_0_1.py
=> One pixel two pixel red pixel blue pixel

Introducing_Feather_M0_Express/battery_voltage.py
=> CircuitPython battery voltage code

Stumblebot/code.py
Add the code for the Stumblebot - by Dano
=> Initial commit

Crickits/cpx-1701/code.py
=> the voyages of the CPX-1701

Crickits/dannybot/code.py, Twitch_On_Air_Sign/ESP8266_OnAirSign/ESP8266_OnAirSign.ino
API now requires a authenication token woo
=> update to mention token!

Crickit_Sparky_Automaton/code.py
************* Module code
Crickit_Sparky_Automaton/code.py 13: Unnecessary semicolon (unnecessary-semicolon)
Crickit_Sparky_Automaton/code.py 5: Unused Pull imported from digitalio (unused-import)
=> Update to ensure code.py meets Travis-CI linting

seesaw/seesaw_blink.py
Learn Guide page https://learn.adafruit.com/adafruit-seesaw-atsamd09-breakout#circuitpython-wiring-test had an example based on an older version of the library.
I'll update the page once this is in the repo.
=> update Learn Guide seesaw blink example and put it in this repo

Crickit_Sparky_Automaton/code.py
files that begin with an underscore can cause issues.
=> Eliminate finding mac specific files

Nightlight/cpx_nightlight.py, Nightlight/gemma_nightlight.py
=> CircuitPython Nightlight programs

Tightrope_Unicycle_Bot/tightrope_unicycle_bot.py
now with just the crickit library
=> simplify code for unicycle

CircuitPython_Essentials/CircuitPython_AnalogIn.py, CircuitPython_Essentials/CircuitPython_AnalogOut.py, CircuitPython_Essentials/CircuitPython_Audio_Out_Tone.py, CircuitPython_Essentials/CircuitPython_Audio_Out_Wave.py, CircuitPython_Essentials/CircuitPython_Digital_In_Out.py
Audio code plus some of the M4 updates. (Unintentionally combined, but it's needed anyway so I'm leaving it together.)
=> Audio out essentials

Circuit_Playground_Express_and_IR/CPX_IR_CPX_transmit.py
Added newline to print statement so serial output matches the 2 line serial output in the receive code. This way if you place them side by side, the output matches.
=> Added newline

Screaming_Painting/screaming_painting.py
first commit Screaming Painting code for learn guide
=> first commit Screaming Painting code

IFTTT_Door_Detector/IFTTT_Door_Detector.ino, IFTTT_Door_Detector/config.h
Guide: https://learn.adafruit.com/using-ifttt-with-adafruit-io
=> Add AIO Door Detector Guide

CircuitPython_Essentials/CircuitPython_Audio_Out_Tone.py
Suggested changes to reduce distortion at high volume and clarify the method for filling the array.
=> Reduce distortion at higher volume levels

HAL-9000/code.py
For Dano for guide https://learn.adafruit.com/hal-9000-replica
=> Initial CircuitPython HAL-9000 code

Hallowing_Lightsaber/lightsaber_standard.py, Hallowing_Lightsaber/lightsaber_unicorn.py
both standard and unicorn modes
=> first commit hallowing lightsaber code

MIDI Solenoid Drummer/Crickit_Drummer.ino, MIDI_Solenoid_Drummer/MIDI_Solenoid_Drummer.ino
Code for new ALS guide. pls review :)
=> added MIDI Solenoid Drummer code

Trinket_Modded_Stuffed_Animal/README.md, Trinket_Modded_Stuffed_Animal/Trinket_Modded_Stuffed_Animal.ino, Trinket_Modded_Stuffed_Animal/Trinket_Modded_Stuffed_Animal.py
ported, runs on CP, no pin changes, linted
=> Trinket modded stuffed animal

Trinket_Gemma_Servo_Control/Trinket_Gemma_Servo_Control.py
@dhalbert - adafruit_motor code has been tested and works. simpleio has been removed. I'll update the guide page after this PR is approved.
=> removed simpleio, replaced with adafruit_motor

TheThingsNetwork_Feather/ttn-featherm0-dht/ttn-featherm0-dht.ino
Moving TTN code to learn repo, removed regression testing, updated sketch to incl. LED tx/rx blink
=> Adding TTN Feather M0 Sketch

Mini_Chair_Swing_Ride/code.py
Initial commit - edited for lint passage
=> Add code.py for guide

Pumpkin_Theremin/code.py
=> remove unneeded code

Munny_Lamp/Munny_Lamp.ino
Maintainers, pull request for John Park's review, please don't merge yet.
Per https://3.basecamp.com/3732686/buckets/4383362/todos/1319808931#__recording_1402164150
John, I took the check to see if the acceleration was positive and put that check directly in the if statement. Then the code to set tilt is not needed and the variable declaration is unneeded. Please review & try and then if this PR or your edits are good, we can look to merge.
=> Changes to remove temp global variable

Motion_Gift_Box/code.py
Code for the tutorial https://learn.adafruit.com/motion-gift-box
=> Create project code

Resin_table_circuitplayground_modes/Resin_table_circuitplayground_modes.ino
Arduino code for Resin Table guide
=> Resin River Table

ABC_Soundboards_for_NeoTrellis/code.py
Code for the guide ABC Soundboards with NeoTrellis
=> Initial Code

Interactive_Map_with_CPX/code.py
Initial code for Dano Wall's Interactive Map with Circuit Playground Express tutorial
=> Initial code for Dano Wall's Interactive Map with Circuit Playground Express tutorial

Interactive_Map_with_CPX/code.py
use defined colors to color NeoPixels while sound is playing per Limor
=> Add color while playing

Bluetooth_Remote_for_Lego_Droid_Kit/code.py
transfer from code block to repo
=> Initial commit of code.py

Color_touch_pendant2/Color_touch_pendant2.ino, color_touch_pendant/color_touch_pendant.ino, color_touch_pendant/color_touch_pendant/color_touch_pendant.ino
Correct code for the color touch pendant guide
=> Color Touch Pendant

Make_It_Talk/say-temp.py
Added fahrenheit to button b, added numbers for -299 to 299 (way more than an atmospheric thermometer). The wav files have been added to go into the thousands and millions although the read_temp function is limited to 299.
=> update for general numbers and fahrenheit

NeoTrellis_M4_Sand/code.py
Added a 'Grains of Sand' Demo with a variety of color options for the NeoTrellis M4
=> NeoTrellisM4 Grains of Sand Demo

CircuitPython_Knob_Sketcher/bigger_sketcher.py, CircuitPython_Knob_Sketcher/pixel_play.py, CircuitPython_Knob_Sketcher/pixel_simple.py, CircuitPython_Knob_Sketcher/tiny_sketcher.py
=> Add CP code for Knob Sketcher

Gemma_Nano_Ring/NanoRing.ino
This project may be coded in _either_: CircuitPythoin, Arduino, or Microsoft MakeCode Maker. This is the Arduino code. It uses the Adafruit_NeoPixel library.
=> create arduino code for ring

.travis.yml, Buzzing_Mindfulness_Bracelet/Buzzing_Mindfulness_Bracelet.ino, README.md, arduino_libinstall, arduino_library_install
Depends on https://github.com/adafruit/travis-ci-arduino/pull/36
This is a work-in-progress branch for adding tests to code for individual guides.  It will need `.[platform].test` files added to individual subfolders, and corresponding libraries installed in `.travis.yml`.
=> add travis-ci-arduino

Grand_Central_Soundboard/code.py
Initial code for the Grand Central Soundboard
=> Initial code for the Grand Central Soundboard

Music_Box_with_Crickit/code.py
=> Update to one while loop

Ada_remoteFXTrigger_NeoTrellis_FastLED_RX/Ada_remoteFXTrigger_NeoTrellis_FastLED_RX.ino, Ada_remoteFXTrigger_NeoTrellis_FastLED_TX/Ada_remoteFXTrigger_NeoTrellis_FastLED_TX.ino
RX & TX code for NeoTrellis Remote FX Controller
=> NeoTrellis Remote FX Controller 

Music_Box_with_Crickit/code.py
Code updated by Limor to respond to light/dark more quickly
=> Changes by Limor

pi_radio/radio_rfm9x.py
* Button A sends 'Button A!' to other radio
* Button B sends 'Button B!' to other radio
* Button C sends 'Button C!' to other radio
* Both radios listen for new packets as default behavior
=> Update Raspberry Pi LoRa Example

pi_radio/radio_rfm69.py, pi_radio/radio_rfm9x.py
* Simplify rfm69 example to match rfm9x example
* Update rfm9x example to use utf-8 decoding
=> Add RFM69 Pi Radio Example

CircusPython_BLE/circus.py
=> CircusPython BLE demo guide code

home-assistant-io/feather_bme280.yaml
Add directory for HomeAssistant. 
Add YAML firmware configuration file for ESPHomeYAML configuration a Feather Huzzah ESP8266 with a BME Sensor, HomeAssistant, and Adafruit IO.
=> Add HomeAssistant/ESPHome

Pi_Hole_Ad_Blocker/stats.py
Pi-Hole version of stats.py updated to CircuitPython SSD1306 library (from old python ssd1306 library)
Tested on a 128x32 i2c OLED and Pi 3B+.
=> add updated pi hole code

pi_radio/radio_lorawan.py
D25 is RESET. Change to D22 (DIO/IRQ)
=> Pi Radio: Change IRQ Pin to D22

PyPortal_AdafruitIO_Logger/pyportal_adafruit_io_logger.py
=> PyPortal IoT Logger

pyportal_weather_station/weatherstation_helper.py
Updating to work with display_text v2.0.0 breaking. Tested on a PyPortal running CPY 4.0.0 beta
https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/releases/tag/2.0.0
=> Updating PyPortal Weather Station to display_text labels

PyPortal_Youtube/youtube.py
i had left in some offset value calculations, for example (200+20) which is now just (220).
=> fixed text position tweak values

PyPortal_OpenWeather/openweather.py
Just fixing some copy pasta someone pointed out.
=> Update openweather.py banner text

PyPortal_ObliqueStrategies/oblique.py
All revisions made, passed travis :)
=> Pyportal Oblique Strategies

PyPortal_IOT_Scale/code.py, PyPortal_IOT_Scale/pyportal_scale.py
=> PyPortal IOT Scale Guide

PyPortal_AdafruitIO_Logger/pyportal_adafruit_io_logger.py
Updating Adafruit IO entry to reflect the updated `secrets.py`
=> Updating secrets.py information

PyPortal_Quotes/quote.py
https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/21#issuecomment-480043786
=> catch json parsing errors too

PropMaker_KeyBlade/code.py
Adding credit to Kattni in keyblade code
=> Kattni credit to keyblade code

Adafruit_X2_Time_Ball/Arduino/LEDtest/LEDtest.ino
Copy of repo https://github.com/adafruit/Adafruit-X2-Time-Ball
=> Initial commit tests for Adafruit X2 Time Ball

Adafruit_IoT_Camera_EyeFi/Adafruit_EyeFi/Adafruit_EyeFi.ino
New location, previously https://github.com/adafruit/Adafruit-IoT-Camera-with-EyeFi-Sketch/blob/master/Adafruit_EyeFi.pde
Accompanies guide http://www.ladyada.net/make/IoTcamera/ which was never ported to learn.adafruit.com.
=> Moving and validating the Adafruit_EyeFi sketch

SD_Basic_GPS_Logger/SD_GPSLogger/GPSconfig.h
Mirroring https://github.com/adafruit/SD-Basic-GPS-logger to Adafruit Guides repo per Limor
=> Create new repo from older repo code

Flora_Brakelight_Backpack/Flora_Brakelight_Backpack/Flora_Brakelight_Backpack.ino
From https://github.com/adafruit/Flora-Brakelight-Backpack
=> Create new repo

LED_Ampli_Tie/Ampli_Tie_Dynamic/Ampli_Tie_Dynamic.ino
Previously at https://github.com/adafruit/LED-Ampli-Tie-with-Flora
=> Migrate Ampli_Tie code

CircuitPython_Essentials/CircuitPython_Continuous_Servo.py
New example for continuous servo
=> New example for continuous servo

Feather_ePaper_Quotes/adafruit_feather_quote/adafruit_feather_quote.ino
Replaced ESPHTTPCLient.h with HTTPClient.h.
Updated code to work with ArduinoJSON version 6
=> Fixes to ESPHTTPClient and ArduinoJSON

pyportal_weather_station/code.py
Changed `adafruit_IO` -> `aio_` to reflect `secrets.py` file in guide. 
re: https://forums.adafruit.com/viewtopic.php?f=60&t=152489&p=753214#p753214
=> Patch Weatherstation Guide

Smart_Toilet_Light/Smart_Toilet_Light_ESP8266/Smart_Toilet_Light_ESP8266.ino
Smart Toilet Light
Smart toilet bowl light using Adafruit IO & a Feather Huzzah ESP8266. See the guide at: https://learn.adafruit.com/smart-toilet-light/overview
was at https://github.com/adafruit/Smart_Toilet_Light
=> Check Migrated code

PyPortal_ArduinoSelfTest/PyPortal_ArduinoSelfTest.ino
Updated to reflect latest QSPI library, v3.0.0
https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/724
=> Update PyPortal Self-Test

Crank_USB_HID/code.py
=> media dial code

PyPortal_Tides/admiralty_tides.py, PyPortal_Tides/admiralty_tides_graphical.py
Files to use UK Admiralty data
=> UK Admiralty tide data

Tilt_Controlled_Servo_Driver/tiltdemo.py
This is for the MagPi article I'm writing. If you'd rather me place it somewhere else, that's fine. It was the best place I could think of though.
=> Adding Tilt Demo using BNO055 and PCA9685 for MagPi

Slideshows_Soundtrack/slideshows_soundtrack.py
This fix comes curtesy of this forum thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=153679&p=758379#p758379
by way of 
https://learn.adafruit.com/hallowing-mac?view=all#overview
I tested it and it's working with the Mac demo on my HalloWing.
=> updating slideshow_display.py to work with displayio updates

CircuitPython_Simple_Wordclock/code.py
=> Add DST switch capability

PyGamer_NeoPixel_Strip_Control/code.py
Adding CircuitPython version of the PyGamer NeoPixel Strip Controller
=> Add PyGamer NeoPixel Controller

Minesweep/code.py
Also backward compatible with CP 4.1.0
Tested on PyPortal with CP4.1.0 and current master 5.0.0-alpha.0-154-gbe52025d02
=> fix audio calls to be compatible with CP5.0 audiocore

PyRuler_Simon_Game/code.py
=> PyRuler Simon Game

EInk_Autostereograms/code.py
=> Added code.py

Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_AnalogIn.py
Updated docstring to be more general. Updated import to not use `from` as we try to avoid that format due to memory issues in larger programs - wouldn't affect this, but could affect someone expanding on this example to do something else. Requires one change to guide, and update of screenshot (screenshot is currently incorrect anyway and will need to be updated, so I included this change in the code as it's not really making more work in this case).
=> Update docstring, import

Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_SoundMeter.py
Removed 2.x compatibility and mention of 3.x usage. Various cosmetic updates.
=> Update sound meter code.

Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_HIDKeyboard.py
Clarified a couple of other comments as well.
=> Update docstring to generalise for Circuit Playgrounds

Hallowing_Jump_Sound/jump-sound.py
Tested on HalloWing M4 with CP 5 Alpha 4, HalloWing M0 with CP 5 Alpha 4 and CP 4.1.
Fixes #847.
=> Fixed HalloWing_Jump_Sound example to work on M4 and M0

Glowing_Scale_Armor/code.py
Erin is having a strange GitHub issue, I'll try to add the code.
=> Add tutorial code per basecamp

M4_Eyes/user_touchneopixels.cpp
https://github.com/jonsampson/Adafruit_Learning_System_Guides/blob/master/M4_Eyes/user.cpp
use arcada for button presses, change some gradients and orders
=> adaptation of @jonsampson/

PyPortal_AWS_IOT_Planter/code.py
Patch for this code, reflects https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/pull/4
=> Patch AWS IoT Planter Code

PyPortal_OpenWeather/openweather_graphics.py
tested on cp4.1.0 and CP5.0alpha4
=>  PyPortal_Openweather - remove calls to refresh_soon and wait_for_frame for CP5.0 compatibility

PyPortal_AWS_IOT_Planter/aws_gfx_helper.py
Fixes https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/891
* remove unnecessary `appends` and calls to `refresh_soon` and `wait_for_frame`
=> Patch PyPortal AWS IoT Planter GFX Helper

PyPortal_Azure_Plant_Monitor/azure_gfx_helper.py
Fixes https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/891
* remove unnecessary `appends` and calls to `refresh_soon` and `wait_for_frame`
=> Patch Azure IoT Planter GFX Helper

CircuitPython_Scrolling_Clouds/code.py
Fixes issue 910. (removing link to not auto-close issue).
=> Fixed Scrolling clouds example on CP5

TFT_Gizmo_Snowglobe/snowglobe_fancy.py, TFT_Gizmo_Snowglobe/snowglobe_simple.py
Nothing screams Halloween like a festive snowglobe!
=> Add code for TFT Gizmo Snowglobe

TFT_Gizmo_Turtle_Graphics/turtle_snowflakes.py
=> Added snowflake

TFT_Gizmo_Snowglobe/snowglobe_fancy.py, TFT_Gizmo_Snowglobe/snowglobe_simple.py
Updating WIDTH and HEIGHT to display.width and display.height also made those variables unnecessary.
=> Update snowglobe to use Gizmo Library

TFT_Sidekick_With_FT232H/tft_sidekick_basic.py, TFT_Sidekick_With_FT232H/tft_sidekick_cpu.py, TFT_Sidekick_With_FT232H/tft_sidekick_mem.py, TFT_Sidekick_With_FT232H/tft_sidekick_net.py
=> Add code for TFT Sidekick

Snow_Globe_BLE_CPB/ble_snowglobe.py
Code for JP's BLE CPB Snowtastic Globery.
=> Add BLE CPB snow globe

Track_Your_Treats/Track_Your_Treats_FONA808/Track_Your_Treats_FONA808.ino
Treat tracker `Adafruit_MQTT_Publish` updated to reflect a valid Adafruit IO topic. 
https://forums.adafruit.com/viewtopic.php?f=56&t=157305
=> Update Treat Tracker Code for valid Adafruit IO Publish

Circuit_Playground_Bluefruit_Pumpkin/code.py
- Update to new BLE API
- Turn on SPEAKER_ENABLE -- no sound otherwise
=> Update Bluefruit Pumpkin to CircuitPython 5.0.0-beta.0 BLE API

Turtle_BLE_CPB_Crickit_Rover/turtle_ble_cpb_crickit_rover.py
This is the CPB Rover, not the Feather Rover.
=> Update CPB Rover to CircuitPython 5.0.0-beta.0 BLE API

Circuit_Playground_Bluefruit_NeoPixel_Controller/Controller.py
This was requested on the receiver code. Assuming it is desired in the controller code as well.
=> Expand if/else.

Circuit_Playground_Bluefruit_NeoPixel_Controller/NeoPixel_Animator.py, Circuit_Playground_Bluefruit_NeoPixel_Controller/Remote_Control.py
Changed what I'm calling each Bluefruit in the guide, updating filenames and docstrings to match.
=> Updating file and project name.

Pi_Hole_Ad_Blocker/mini_pitft_stats.py
PR to update Pi-Hole adblocker guide for [Adafruit Mini PiTFT](https://www.adafruit.com/product/4393).
=> Add update to Pi-Hole guide for mini PiTFT

TFT_Gizmo_Dreidel/dreidel.py
Default shake threshold seems a bit stiff:
https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/964#issuecomment-564966052
This makes it changeable and defaults to a lower value.
=> Add dreidel shake threshold

CPB_ANCS/code.py
Inspired by https://github.com/kickstarter/rack-attack/pull/181
=> Use Blocklist instead of blacklist

CPB_NeoPixel_Wooden_Xmas_Tree/code.py
CP code for Wooden NeoPixel Xmas Tree Learn guide. Using Circuit Playground Bluefruit to control NeoPixels with FancyLED library.
=> CircuitPython code for Wooden NeoPixel Xmas Tree Learn Guide

GemmaM0_Headband/README.md, GemmaM0_Headband/code.py
https://learn.adafruit.com/TwinklyEarwarmer/circuitpython-chill-sensor
=> Add code for the guide "Twinkly Earwarmer Headband"

AutoSunglasses/code.py
changed from using simpleio.Servo to pulseio & adafruit_motor servo
=> AutoSunglasses updated for current libs

ItsyBitsy_Infinity_Cube/code.py
=> code for Infinity Cube

Google_Sheet_Sensor_Logging/bme280_logger.py, Google_Sheet_Sensor_Logging/max31855_logger.py
Code for Google Sheet sensor logging guide.
=> Add code for sensor logging

.gitignore, CPB_Volume_BLE/cpb_volume_ble.py
.python-version is there because of Catalina and pylint shenanigans
=> first commit CPB Volume BLE, added .python-version to .gitignore

PyPortal_Titano_Weather_Station/openweather_graphics.py
edit for update_date() function
=> Updating openweather_graphics.py

PropMaker_Lightsaber/code.py
=> PropMaker Lightsaber Code

BLE_Synth/cpb_amp_code.py, BLE_Synth/feather_keyboard_code.py
Adding code files for the BLE synth project. One file is for the Feather nRF52840 (keyboard) and the other is for the Circuit Playground Bluefruit (amp). They're named for clarity so that there aren't two code.py files- this is noted in the Learn guide
=> Adding code files for BLE synth Learn Guide

TFT_Gizmo_Candy_Hearts/candy_heart_ble.py
```
________           ________
/  ______  \       /  ______  \
/  /        \  \   /  /        \  \
/  /            \  "  /            \  \
|  |               \ /               |  |
|  |                "                |  |
|  |                                 |  |
|  |              I <3             |  |
|  |             BLE             |  |
|  |                         |  |
|  |                     |  |
|  |                 |  |
|  |             |  |
|  |         |  |
|  |     |  |
|  | |  |
| | |
| |
|
```
=> Add BLE candy hearts code

ItsyBitsy_Heart_Necklace/code.py
Code for ItsyBitsy Heart Necklace
=> Code for ItsyBitsy Heart Necklace

TFT_Gizmo_Candy_Hearts/clue_heart_ble.py, TFT_Gizmo_Candy_Hearts/clue_hearts.py
Surprisingly trivial change to get both versions to work on Clue. So here they are FWIW. Not sure where else they could live?
=> Add Clue versions of TFT Candy Hearts

CircuitPython_WeatherCloud/code.py, CircuitPython_WeatherCloud/secrets.py
openweather based animated cloud
=> init sketch

Propmaker_Master_Sword/code.py
Also updated to use I2C singleton.
=> Update for CircuitPython 5.0.0

MX MIDI Guitar/code.py, MX_MIDI_Guitar/code.py
Code for MX MIDI Guitar learn guide
=> Uploading MIDI guitar code

CircuitPython_RGBMatrix/simple_scroller.py
=> Suggest scrolling text left to right

PyPortal_Quarantine_Clock/month_clock.py
Adding bonus months clock code resource for guide.
=> Quarantine Clock, months

PyPortal_User_Interface/code.py
To avoid loosing precision the rounding should take place after the conversion from Centigrade to Fahrenheit.
I also believe that this conversion is present in one or some CP library, so it could be reused.
WARNING: code not tested
(well I compared the math on another board)
=> rounding temperature as last operation

Baudot_TTY/baudot_tty.py, Baudot_TTY/baudot_tty_ble.py
Not sure if the ```global char_count, current_mode``` line is a problem in these?
=> first commit

CircuitPython_Essentials/CircuitPython_Audio_Out_Tone.py, CircuitPython_Essentials/CircuitPython_Audio_Out_Wave.py
Tested on CPB/CPX by me. Tested successfully with proper wiring by JP.
=> Update AudioOut examples.

PyPortal_Quarantine_Clock/code.py, PyPortal_Quarantine_Clock/month_clock.py
The Exception is passed as "error" but the print statement uses "e"
=>  fix try/except in PyPortal Quarantine Clock

CLUE_Metal_Detector/clue-metal-detector.py
A very minor update:
- Fixing a bug when running on a CPB (CLUE is the main platform).
- Consistency on case on the intro `Button Guide` screen.
I think @cogliano approved last one, actually I see @ladyada did it for #1100
=> CLUE Metal Detector in CircuitPython - minor code update

BLE_Buzzy_Box/code.py
Code for BLE Buzzy Box Learn Guide. Feather NRF52840 with a DRV2605 haptic motor driver. When a notification arrives from ANCS it vibrates & onboard NeoPixel flashes. Also vibrates and flashes on the hour for mindfulness reminder
=> Adding code for BLE Buzzy Box

BLE_Vibration_Bracelet/code.py
Updated code for the BLE Vibration Bracelet Learn Guide:
-Uses adafruit_led_animation library now for NeoPixel colors
-also fixing the double ".py.py" file name
=> updated BLE vibration bracelet

Daily_Cheer_Automaton/Arduino/autocheer.ino, Daily_Cheer_Automaton/CircuitPython/code.py
different commands for different RTC hardware, corrected to match the Learn Guide.
=> fixed RTC type mismatch

ItsyBitsy_Keybow/itsybitsy_keybow.py
ItsyBitsy M4/M0 + Pimoroni Keybow mechanical keyswitch board = USB HID keyboard pad in CircuitPython
=> first commit itsybitsy keybow

CircuitPython_Essentials/CircuitPython_PWM_Piezo.py
=> Fix duty_cycle range.

ItsyBitsy_Keybow/ItsyBitsy_Keybow_04.brd, ItsyBitsy_Keybow/ItsyBitsy_Keybow_04.sch
Added the Eagle schematic and board files for ItsyBitsy M4-to-Raspberry Pi pin adapter.
=> added board files

Circuit_Playground_Brake_Light/code.py
Works best with CPB because it's faster, but it still works fine on the CPX
=> Circuit Playground auto bike brake light

RGB_Matrix_Slot_Machine/code.py
Code for the fruit machine guide
=> Add code for the guide

Circuit_Playground_Bluefruit_NeoPixel_Controller/NeoPixel_Animator.py
LED Animations library API was changed, code needed to be updated to match. Tested thoroughly, as bugs were found in the LED Animation lib while updating this code. (Those bugs have been resolved.)
=> Update to match lib API change.

ST_Combo_Boards/lis3mdl_lsm6ds_test/lis3mdl_lsm6ds_test.ino
=> Update to include ISM330DHCX

Lucio_Blaster_2020/lucio_blaster_2020.py
=> fist commit

Temperature_GIF_Player/Temperature_GIF_Player.ino
=> Fix GifDecoder Header name

EInk_Bonnet_Weather_Station/weather.py
=> Removed unused library, made editable field clearer

EInk_Bonnet_Event_Calendar/event_calendar.py
This version has the fonts looking better and gets events from all calendars.
=> Added EInk Bonnet Event Calendar

Bluetooth_Restroom_Keys/README.md, Bluetooth_Restroom_Keys/code.py
=> Code for Restroom Keys Guide

PyPortal_CircuitPython_2020/code.py
Code for the CircuitPython Day 2020 countdown timer
the code.
process.
Thank you again for contributing!  We will try to test …
=> Code for the CircuitPython Day 2020 on PyPortal guide

CircuitPython_sdcardio_sdioio/list_files.py, CircuitPython_sdcardio_sdioio/log_temperature.py, CircuitPython_sdcardio_sdioio/play_mp3s.py, CircuitPython_sdcardio_sdioio/show_bitmaps.py
all demos tested on an adafruit pygamer, though some will work on other boards as well.  Assumes the user creates a "mount_sd.py" file, which will be detailed in the guide.  Typical content for pygamer:
```
import board
import busio
import sdcardio
import storage
spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
cs = board.SD_CS
sdcard = sdcardio.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")
```
=> New files for upcoming guide

Pixel_Chase_Game/code.py
Adding the code for the Pixel Chase Game Learn Guide.
Using 61 NeoPixels in a circle, a "chaser" pixel flies around. A "target" pixel is setup randomly in the circle and using a push button, you try and hit the target with the chaser. The colors change and speed increases with each level up. If you press the button without being on target, the game resets. Once you win all the levels, the NeoPixels go into rainbow_cycle for a bit and then a new game begins.
=> pixel chase game code

Adafruit_ESP32_Arduino_Demos/SerialESPPassthrough/SerialESPPassthrough.ino
Similar to https://github.com/adafruit/WiFiNINA/pull/6, this pull request updates the SerialESPPassthrough sketch for the ItsybitsyM0 and NRF52 Itsybitsy
=> Update External ESP32 Passthrough Sketch

MP3_Tap_Player/mp3_tap_player.py
updated comment to be accurate to running on M4 board
=> comment fix for M4 board

CLUE_Altimeter/clue_altimeter.py
Slight oversight on my part. Didn't think about dealing with initial condition for NVM. Simple fix.
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=65&t=167847
=> CLUE altimeter update

BusyBox_Sign/code.py
howdy @TheKitty code for this week's 3D project is ready for review. Thanks!
=> busybox code

DYP_ultrasonics/me007ys.py, DYP_ultrasonics/me007ys/me007ys.ino, DYP_ultrasonics/me007ys_OLED/me007ys_OLED.ino
=> some tests

Matrix_Portal_Moon_Clock/code.py
Bug in the rotation setting has been corrected
=> Fix startup rotation math

VOTE_Keyboard/code.py
Changes made from guide feedback.
=> updated for new libraries

Mask_Efficacy/process_run.py, Mask_Efficacy/take_video.py
Python code to go along with mask efficacy guide.
=> Add mask test python code

QT_Py_NeoPixels/QT_Py_NeoPixel_Animations.py
Tested successfully by @jedgarpark.
=> Basic animations for NeoPixels on QT Py.

QT_Py_Bracelet/README.md, QT_Py_Bracelet/code.py
=> Code for QT Py Bracelet tutorial

Matrix_Portal_Scoreboard/matrix_portal_scoreboard.py
Matrix Portal scoreboard w AIO code, first commit.
=> first commit scoreboard code

EInk_Bonnet_Weather_Station/weather_graphics.py
Suggested by a user where this fixed an issue for them. I tested and it worked for me either way.
=> eInk Bonnet Weather Station improvement

QT_Py_Timer/QT_Py_Activity_Timer.py, QT_Py_Timer/QT_Py_Hydration_Reminder.py
Removed time function per feedback as it was only used in three places in one project, and two in the other. I included it assuming I would need it more than I ended up needing it.
=> Remove function, move time math inline.

BLE_Host_Computer/ble_eval_client.py, BLE_Host_Computer/ble_eval_server.py
Example programs for adafruit-blinka-bleio guide.
=> ble_eval examples

Circuit_Playground_Classic_Fruit_Drums/CapTouchBasic/CapTouchBasic.ino, Circuit_Playground_Classic_Fruit_Drums/CapTouchKeyboard/CapTouchKeyboard.ino, Circuit_Playground_Classic_Fruit_Drums/CapTouchMIDIDrums/CapTouchMIDIDrums.ino, Circuit_Playground_Classic_Fruit_Drums/CapTouchTones/CapTouchTones.ino, Circuit_Playground_Classic_Fruit_Drums/HelloCapTouch1/HelloCapTouch1.ino, Circuit_Playground_Classic_Fruit_Drums/HelloCapTouch2/HelloCapTouch2.ino
This code predates steel, so you can't get it wet...
Doing some guide cleanup. Adding this old CPC code here so can change guide to have embedded links.
=> Adding old CPC fruit drum code

CircuitPython_Sip_and_Puff/simple_hid.py
The API for HID appears to have changed! This fixes it
=> updating sip & puff to fix the hid example

FeatherCAN_CircuitPython/listener-ack.py, FeatherCAN_CircuitPython/listener.py, FeatherCAN_CircuitPython/sender-ack.py, FeatherCAN_CircuitPython/sender.py
This covers the basic use cases we discussed:
* sender and receiver
* reliable transmission (also demonstrates send and receive in same program)
=> Add examples for upcoming Adafruit Feather M4 CAN guide

Matrix_Portal_Flow_Viewer/flow.py, Matrix_Portal_Flow_Viewer/flow_runner.py, Matrix_Portal_Flow_Viewer/flow_viewer.py
Code for Matrix Portal Flow Viewer guide.
=> Add flow viewer code

MagTag_Arduino_Demos/quotes/quotes.ino, MagTag_Arduino_Demos/shipping_demo/shipping_demo.ino
=> update esp32s2 quotes demo

MagTag_SimpleClock/code.py
=> fix leading zero in minutes for bigclock

MagTag_CountdownCelebration/code.py
recent changes to libraries caused some of the text to be shifted off the screen.
changed setting to recenter on the left side.
also ran "black" -- resulted in reformatting several lines
=>  MagTag_CountdownCelebration - fix text position 

OSHWA_Submitter/submitter.py
I decided to leave the script filled out so it'd be easier for people to tell what the variables mean.
=> Added code for OSHWA submitter script

Magtag_Slideshow/magtag_slideshow.py
the error handling was moved to magtag library.
=> removed audiocore error code

MagTag_CircuitPython_Smart_Holiday_Lights/MagTag_Smart_Holiday_Lights.py
I intend to add displaying an image on the display once I've sorted out images. It adds 6 lines of code, so it's not a significant change. Submitting code as-is to get it into the system.
=> Adding initial guide code.

MagTag_SpaceX/README.md
=> Update README.md with font information

Neopixel_Aquarium/Neopixel_Aquarium.ino
hopefully with tiki file delete issue fixed!
=> NeoPixel Aquarium Code

MagTag_SpaceX/code.py
Limor had suggestions. Plus adjust text for Details using the latest data from the JSON feed formatting font text handling
=> Update code per discussion with Limor

MagTag_SpaceX/README.md
=> Update README.md to include the guide info. No code change

MagTag_Progress_Displays/weblate_translated_percent.py, MagTag_Progress_Displays/year_progress_percent.py
@FoamyGuy removed some unused variables, etc. please try
=> light cleanup

MagTag_Tides/magtag_tides_land_lp.py
Tested with 6.1.0 beta 2 and MagTag 1.2.0. Made this update yesterday and it ran as expected overnight, triggering at 3AM.
=> Update sleep to use MagTag API

MagTag_Seasonal_Produce/code.py, MagTag_Seasonal_Produce/produce.py, MagTag_SpaceX/code.py
@TheKitty please review for code edits
=> refactor & deep sleep 

MagTag_Tides/magtag_tides_land_lp.py
The existing version works fine, but the forever doesn't really ever loop since code just reruns on wake. This PR removes the loop. Tested overnight and works as expected.
=> Remove forever loop from MagTag Tides w/ deep sleep

FeatherCAN_CircuitPython/listener-ack.py, FeatherCAN_CircuitPython/listener.py, FeatherCAN_CircuitPython/sender-ack.py, FeatherCAN_CircuitPython/sender.py, Raspberry_Pi_Braincraft_Radio/setup-kiosk.sh
This adds the script for an upcoming guide.  I accidentally included an unrelated commit which adds comments to an earlier canbus guide for users with esp32s2 microcontroller boards, but this change is good too :)
=> Raspberry pi braincraft radio

MagTag_Christmas_Countdown/code.py
This variate the ball colors between white, light grey and dark grey.
Not a very complex change, and I feel it give a nice effect by showing the grey scale capability of the MagTag.
=> Give "colors" to the balls on MagTag_Christmas

IoT_NeoPixel_Sign/code.py
adding code for the IoT neopixel sign project.
=> IoT neopixel sign code

MagTag_Cheerlights_LED_Animations/MagTag_Cheerlights_LED_Animations.py
Noticed the number of sparkles was backwards. Fixed.
=> Fix sparkle number.

ulab_Crunch_Numbers_Fast/cluepulse.py, ulab_Crunch_Numbers_Fast/waterfall.py
Several fixes to learn system code based on feedback
=> Learn system fixes

MagTag_Kitchen_Timer/code.py
=> less blasty output

Adafruit_MAX98357/CircuitPython_I2S_Tone.py, Adafruit_MAX98357/CircuitPython_I2S_Wave.py
This updates some imports to use the new ones from `audiocore` instead of `audioio`
Untested, don't have hardware for it.
=> change to new audiocore imports

PyPortal_Tides/pp_tides.py, PyPortal_Tides/pp_tides_graphical.py
Fixes issues brought up in this forum post:
https://forums.adafruit.com/viewtopic.php?f=60&t=174180
I could not recreate the memory allocation issue mentioned.
=> Update PyPortal Tides Code

NeoPixel_Crystal_Chandelier/code.py, NeoPixel_Crystal_Chandelier/code_simple.py
full version and simplified version
=> Chandelier code

CircuitPython_Darksaber/code.py
=> Adding code for non-BLE darksaber

Visualizer_Touch_Control/visualizer_touch_control.py
Cap touch control board MPR121 w QT Py for controlling Animus visualizer
=> first commit cap touch viz control

PyPortal_Calculator/code.py, PyPortal_Calculator/titano_code.py
Apparently the group property of button is deprecated and not really needed anyways. :)
=> Updated PyPortal Calculator to fix deperecated button feature

Home_Assistant_Sensor/code.py
Code for my Home Assistant guide
=> Added Home Assistant Sensor project code

Home_Assistant_Sensor/code.py
This is the final version. For some reason the I2C issue appears to be gone with this code, so I have it using Deep Sleep by default.
=> Remove duplicate secrets import and reorganize

ItsyBitsy_Infinity_Collar/code.py
https://learn.adafruit.com/admin/guides/3223/editor/21466
=> Code for new guide Infinity Mirror Collar

PyPortal_EZ_Make_Oven/codecalibrate.py
Postfix temperatures with "C", in codecalibrate.py, to indicate
units (and make clear the number is temperature). Also, limit
temperature value to two significant digits.
the code.
strive to not break users …
=> EZ Make cal: Added Celsius temperature units.

PyPortal_EZ_Make_Oven/codecalibrate.py
Print 10 messages, one second apart, instead of a single
message for 10 seconds.
Instead of a single message, with a 10 second pause:
Calibration will start in 10 seconds...
codecalibrate.py will now display:
Calibration will start in 10 seconds...
Calibration will start in 9 seconds...
Calibration will start in 8 seconds...
Calibration will start in 7 seconds...
Calibration will start in 6 seconds...
Calibration will start in 5 seconds...
Calibration will start in 4 seconds...
Calibration will start in 3 seconds...
Calibration will start in 2 seconds...
Calibration will start in 1 seconds...
- …
=> EZ Make cal: Converted "start in..." message to countdown.

PyPortal_EZ_Make_Oven/code.py
Bumped version # for recent code updates.
=> EZ Make Oven - bumped version #

PyPortal_Tides/pp_tides.py, PyPortal_Tides/pp_tides_graphical.py
For #1442 
Updates just the main ones for now, which the guide references. Can take a look at the admiralty ones later if it comes up. Those were user submitted.
=> Update PyPortal Tides

QTPy_Heart/code.py
=> Adding code for QTPy Heart

CircuitPython_Essentials/CircuitPython_Audio_Out_Tone.py, CircuitPython_Essentials/CircuitPython_Audio_Out_Wave.py
Updates code for CircuitPython 6.x.
=> Remove old import.

CircuitPython_Essentials/CircuitPython_Logger.py, Getting_Started_With_Raspberry_Pi_Pico/data_logger.py, Getting_Started_With_Raspberry_Pi_Pico/data_logger_boot.py
Added comment to original data logging example, and added examples for Pico guide.
=> Adding and updating data logging examples.

Pico_RP2040_Servo/pico-servo.py
Basic servo demo on Pico. Uses button to switch between modes (smooth vs. direct)
=> Pico servo code

Pico_RP2040_Stepper/pico-stepper.py
Demo code for running stepper on Pico
=> Pico RP2040 stepper demo code

Pico_RP2040_Motor_Party/pico_rp2040_motor_party.py
combines all the motor code in one fun place
=> full Pico motor party

MagTag_Sports_Schedule/magtag_sports_schedule.py
=> Sports is all up in your MagTag

CircuitPython_Pico_PIO_Neopixel/code.py, CircuitPython_Pico_PIO_Neopixel/neopio.py
This code will be part of the upcoming guide "NeoPIO: Drive lots of LEDs with Raspberry Pi Pico"
=> Code for new guide

MagTag_Sports_Schedule/magtag_sports_schedule.py
Uses the datetime library which fixes an issue with timezone conversion getting the date wrong.
=> Now uses datetime library

MetroX_CircuitPython/mib_colorful_light.py
Addresses:
https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/1464
Reflects:
https://github.com/adafruit/METROX-CircuitPython/pull/6
=> Update MetroX example to pwmio

TFT_Gizmo_Candy_Hearts/candy_hearts.py, TFT_Gizmo_Candy_Hearts/clue_hearts.py
Fix typo noted in Guide Feedback.
=> Typo Fix - Candy Hearts

Black_Lives_Matter_Kit/Capacitive_Touch_and_NeoPixels.py, Black_Lives_Matter_Kit/Sound_Reactive_NeoPixels.py
Sound reactive LED example and cap touch LED example.
=> Adding BLM CircuitPython code.

Pico_MIDI_Fighter/code.py
Forgot one pin in the code- didn't realize until fully assembled. Adding GP26 and moving two arrays lower in the code for easier understanding.
=> Updating Pico MIDI Fighter code (minor change)

Grand_Central_MIDI_Knobs/Grand_Central_MIDI_Knobs.py
Fixed this code since to work with things that have changed in adafruit_midi that broke it, also added UART classic midi out over TX/RX
=> updated to work with current library

Chromakey_Light_Ring/chromakey_light_ring.py
QT Py w rotary encoder and 24 pixel ring code for retroreflective chromakey camera rig.
=> first commit chroma light ring code

PyPortal_ISS_Tracker/pp_iss_tracker.py
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=177083
Simple fix to override a new default behavior added since guide was originally written.
=> Update ISS tracker

CircuitPython_Pico_PIO_Neopixel/code.py
.. in response to user feedback
=> Use strand_length variable instead of a literal number

Nightlight/cpx_nightlight.py
Guide feedback requested that this be rewritten to use the newer library conventions.
=> Use more modern CP library conventions.

MIDI_FeatherWing/MIDI_FeatherWing.ino, MIDI_FeatherWing/midi_featherwing.py
An Arduino version and CircuitPython version of MIDI FeatherWing basic note playback demos.
=> first commit MIDI FeatherWind demos

PyPortal_EZ_Make_Oven/code.py
I've made a few changes in the EZ Make Oven code to try to conserve memory in order to hopefully allow it run on a PyPortal Titano as is discussed in this forum post: https://forums.adafruit.com/viewtopic.php?f=60&t=177110&p=863371#p863371
I did successfully replicate the same memory error on the regular PyPortal by hardcoding the Titano's screen size.
The primary things I changed are: 
- change `label` to `bitmap_label`
- remove the calls to `load_glyphs` on all 3 fonts. These are good for speeding up changes to the text that is showing by pre-loading all of the possibly used glyphs but do consume some memory. This app was not using the full set of glyphs so many of the pre-loaded ones were using space with no real benefit. There is ongoing work in the core bitmap.readinto that will get …
=> reduce memory usage in ez make oven

Matrix_Quote_Board/matrix_quote_board.py
Reported here: https://forums.adafruit.com/viewtopic.php?f=60&t=177252&p=864129#p863442
I didn't test but should be right.
=> Fix raising exception

CircuitPython_Templates/neopixel_blink.py, CircuitPython_Templates/touch_input.py
And update docstring in NeoPixel blink template code.
=> Add touch input template example code.

Terrako_Robot/code.py
Code for Terrako Guardian Egg Robot
=> Code for Terrako

Circuit_Playground_Sailor_Moon_Star_Locket/code.py
Updated code to use the adafruit_circuitplayground helper library for audio and the buttons
=> Changing code to use circuitplayground helper lib

FunHouse_HA_Companion/code.py
Fixes an issue with the brightness response and general code improvements for the guide.
=> FunHouse Companion guide changes

Funhouse_Door_Alert/code.py
Now using REST instead of MQTT for better reliability. Also using debouncer.
=> switched to use REST

Funhouse_Door_Alert/code.py
fixes for last_door and i2c that isn't needed
=> fixed unused variable and i2c

QT_Py_RP2040_Lemon_Keypad/code.py
=> Code for Lemon Keypad

FunHouse_LIFX/code.py
FunHouse + PIR sensor motion trips color change on LIFX bulb
=> first commit FunHouse LIFX code

CPX_Simple_Simon/code.py
retro adding some ancient code that's currently only embedded in guide:
https://learn.adafruit.com/circuit-playground-simple-simon/circuitpython-version
=> add CPX Simple Simon

FunHouse_Motion_Outlet/code.py
I also decided to move USE_MQTT to its own variable for guide purposes.
=> FunHouse Motion Controlled Outlet MQTT loop Bug fix

CircuitPython_Templates/cap_touch_one_pad.py, CircuitPython_Templates/cap_touch_one_pin.py, CircuitPython_Templates/cap_touch_pin_script/code.py, CircuitPython_Templates/cap_touch_two_pad.py, CircuitPython_Templates/cap_touch_two_pin.py, CircuitPython_Templates/storage_boot.py, CircuitPython_Templates/storage_code.py, CircuitPython_Templates/storage_neopixel_code.py
Examples for Storage include boot.py, code.py using the built-in LED, and code.py using a NeoPixel.
Examples for Cap Touch include one- and two-pad, and one- and two-pin examples, and a script for identifying touch-capable pins on a board. At the moment, the script is for me only as I intend to include an image in each template page indicating the pins, but it could be useful in the future, so I'm including it here.
=> Code for Storage and Cap Touch templates.

Data_Logging_with_Feather_and_CircuitPython/DataLogger.py
1. Change busio references to board.I2C
2. Change the import order to be plynt compliant
=> changing_board.I2C_reference and changing import_order

RasPi_Low_Light_Camera/lowlight.py
Code for the new guide Low Light Long Exposure Photography
https://learn.adafruit.com/low-light-long-exposure-photography/
=> Codfe for new guide 

FunHouse_HA_Companion/code.py
=> Fix units for FunHouse Assistant

Welcome_to_CircuitPython/neopixel_blink.py
This is linked in the Welcome to CircuitPython: Creating and Editing Code page, and was specific to QT Py, but the Trinkeys will need it too. Generalised the example.
=> Generalise NeoPixel Blink example.

FunHouse_Parking/code.py
Parking assistant w ultrasonic sensor
=> first commit funhouse parking

Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_blink.py, Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_button.py, Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_mic.py, Arduino_Nano_RP2040_Connect/arduino_nano_rp2040_connect_wifi.py
Adding example code for the Arduino Nano RP2040 Connect: blinking onboard LED, digital input, PDM mic and wifi.
=> Adding examples for Arduino RP2040

FunHouse_HA_Companion/code.py
I had a guide feedback request to add some more comments to explain this section better.
=> Update FunHouse Home Assistant code with more comments

Pico_RP2040_Mech_Keyboard/code.py
some code cleanup and changed name to code.py for easy project bundle use
=> Cleaned code, switched list to tuple, renamed to code.py

MIDI_Modal_Keyboard/code.py
code cleanup, some lists to tuples
=> code cleanup, some lists to tuples

NeoKey_Emoji_Keyboard/macOS_code.py, NeoKey_Emoji_Keyboard/windows_code.py
Code for both macOS and Windows for the NeoKey Emoji Keyboard Learn Guide. Each NeoKey is assigned to an emoji. Emojis can be customized with the arrays right before the loop. NeoPixels also light up when NeoKey is pressed.
=> Code for NeoKey emojis

CLUE_Altimeter/clue_altimeter.py
Remove usage of max_size with displayio.Group
Ref: #1603
Learn Guide:
https://learn.adafruit.com/clue-altimeter
*No apparent changes needed*
=> CLUE Altimeter: Update for CP7

CircuitPython_Slider/code.py
Ran black
Learn Guide: https://learn.adafruit.com/circuitpython-motorized-camera-slider
Updates needed:
Page: https://learn.adafruit.com/circuitpython-motorized-camera-slider/code-walkthrough
* Section: https://learn.adafruit.com/pages/18162/elements/3048963/download - Search for 'max_size'
=> Slider: Update for CP7

Macropad_Olympic_Hotkeys/mac-olympics-home.py, Macropad_Olympic_Hotkeys/mac-sports-1.py, Macropad_Olympic_Hotkeys/mac-sports-2.py, Macropad_Olympic_Hotkeys/mac-sports-3.py, Macropad_Olympic_Hotkeys/mac-sports-4.py
- Kattni helped me disable the "line too long" on pylint
- All links now functional
- Edited some comments
=> line too long pylint disabled

Macropad_Hotkeys/code.py
Just a good way to unstick keys just in case.
the code.
process.
Thank you again for contributing!  We will try to test and …
=> Release keys when switching layers

CLUE_Milk_Checker/code.py
Learn Guide: https://learn.adafruit.com/digital-nose-gas-sensor-milk-freshness-checker
=> CLUE Milk Detector: Update for CP7

I_Voted_Pin/code.py
Learn Guide: https://learn.adafruit.com/i-vote-d-pin
=> I Voted Pin: Update for CP7

LED_Matrix_Scoreboard/code.py
Learn Guide: https://learn.adafruit.com/led-matrix-scoreboard
Update needed: Page: https://learn.adafruit.com/led-matrix-scoreboard/led-matrix-scoreboard-code-walkthrough
* Section: https://learn.adafruit.com/pages/19820/elements/3067250/download
=> LED Matrix Scoreboard: Update for CP7

Clue_Step_Counter/clue_step_counter.py
Update OnDiskBitmap with filename string usage for CP7
Learn Guide: https://learn.adafruit.com/clue-step-counter-st-lsm6ds33
Some changes are needed to the page: https://learn.adafruit.com/clue-step-counter-st-lsm6ds33/circuitpython-code-walkthrough
Sections:
* https://learn.adafruit.com/pages/19211/elements/3061045/download
* https://learn.adafruit.com/pages/19211/elements/3061047/download
=> CLUE Step Counter: Update for CP7

MagTag_Weather/magtag_weather.py
Learn Guide: https://learn.adafruit.com/magtag-weather
=> MagTag Weather: Update for CP7

MagTag_Tides/magtag_tides_land_lp.py
Learn Guide: https://learn.adafruit.com/magtag-tides-viewer
=> MagTag TIdes: Update for CP7

MagTag_Dishwasher_Status/wake_on_button.py, MagTag_Dishwasher_Status/wake_on_flip.py
Learn Guide: https://learn.adafruit.com/magtag-dishwasher-status
=> MagTag Dishwasher Status: Update for CP7

MagTag_Project_Selector/code.py
Learn Guide: https://learn.adafruit.com/adafruit-magtag-project-selector
Changes Needed: Page: https://learn.adafruit.com/adafruit-magtag-project-selector/code-run-through
* https://learn.adafruit.com/pages/21306/elements/3080544/download - Remove max_size
=> MagTag Project Selector: Update for CP7

PyBadge_Blinka_Jump_Game/code.py
Learn Guide: https://learn.adafruit.com/blinka-jump-pybadge-game
=> PyBadge Blinka Jump Game: Update for CP7

PyBadge_Conference_Badge/code.py
Learn Guide: https://learn.adafruit.com/pybadge-conference-badge-multi-language-unicode-fonts
=> PyBadge Conference Badge: Update for CP7

PyGamer_NeoPixel_Strip_Control/code.py
Learn Guide: https://learn.adafruit.com/pygamer-neopixel-controller
=> PyGamer Neopixel Strip Control: Update for CP7

Smart_Alarm_Clock/code.py
updates for cp7 ref: #1603 
Don't have the necessary hardware for testing.
I think the guide that goes along with this is not live yet, I was unable to locate any published guides that are using this code.
=> smart alarm clock cp7 updates

Minecraft_Turbopad/code.py
Learn Guide: Unknown - the code is only 4 days old
@TheKitty and @jedgarpark for review
=> Minecraft Turbopad: Update for CP7

PyPortal_Trivia_Time/code.py
updates for cp7 Ref: #1603
also tweaked a few text positions that I noticed were overlapping a little bit.
Guide: https://learn.adafruit.com/pyportal-trivia-time-open-trivia-database/overview
there don't appear to be any updates needed in the guide.
Tested on PyPortal 7.0.0 alpha 5
=> pyportal trivia cp7 updates

CircuitStonks/code.py
Learn Guide:  Unknown
The commits were by @ladyada and @jerryneedell 
=> CircuitStonks: Update for CP7

AHT20_OLED/code.py
=> AHT20 OLED: Update for CP7

PyPortal_UV_Index/code.py
Updates for CP7 Ref: #1603 
Tested on PyPortal 7.0.0 alpha5
This guide page contains a code snippet and text section that will need to be updated: https://learn.adafruit.com/pyportal-uv-index/code
=> pyportal uv index cp7 updates

Buckaroo_Plant_Care_Bot/buckaroo_plant_care_bot.py
Learn Guide: https://learn.adafruit.com/chauncey-flower-watering-bot-clue
=> Buckaroo Plant Care Bot: Update for CP7

Metro_Matrix_Clock/metro_matrix_clock.py
Learn Guide: https://learn.adafruit.com/network-connected-metro-rgb-matrix-clock
=> Metro Matrix Clock: Update for CP7

MIDI_CLUE_BLE_Glove/midi_clue_ble_glove.py
Learn Guide: https://learn.adafruit.com/clue-midi-glove
=> MIDI Clue BLE Glove: Update for CP7

Macropad_Dragon_Drop/code.py
Tiny change, sorry about that.
=> Dragon game: oops, change when speaker is disabled

PyPortal_EZ_Make_Oven/code.py
Learn Guide: https://learn.adafruit.com/ez-make-oven
=> PyPortal EZ Make Oven: Update for CP7

Minesweep/code.py
Learn Guide: https://learn.adafruit.com/circuitpython-pyportal-minesweeper-game
Changes needed: Page: https://learn.adafruit.com/circuitpython-pyportal-minesweeper-game/the-board
Section:
* The Board - https://learn.adafruit.com/pages/16937/elements/3036178/download - Remove max_size
=> Minesweep: Update for CP7

MIDI_Melody_Maker/code.py
Learn Guide: https://learn.adafruit.com/midi-melody-maker
Changes Needed: Page: https://learn.adafruit.com/midi-melody-maker/circuitpython-code-walkthrough
Section:
* Setup the STEMMA OLED - https://learn.adafruit.com/pages/20405/elements/3073011/download - Remove max_size
=> MIDI Melody Maker: Update for CP7

Matrix_Portal_Moon_Clock/code.py
Learn Guide: https://learn.adafruit.com/moon-phase-clock-for-adafruit-matrixportal
=> Matrix Portal Moon Clock: Update for CP7

PyPortal_OpenWeather/openweather_graphics.py
updates for cp7 Ref: #1603
tested on PyPortal with 7.0.0 alpha5
Guide: https://learn.adafruit.com/pyportal-weather-station/overview
there don't appear to be any changes needed in the guide.
=> pyportal openweather cp7 updates

PyPortal_Halloween_Countdown/code.py
Learn Guide: https://learn.adafruit.com/pyportal-halloween-countdown
=> PyPortal Halloween Countdown: Update for CP7

PyPortal_IOT_Scale/pyportal_scale.py
Learn Guide: https://learn.adafruit.com/data-logging-iot-weight-scale
=> PyPortal IOT Scale: Update for CP7

MacroPad_RPC_Home_Assistant/code.py, MacroPad_RPC_Home_Assistant/rpc.py, MacroPad_RPC_Home_Assistant/rpc_ha_server.py
Guide is still in progress, but this is working code with a component to run on MacroPad, one to run on the computer, and a shared rpc library to be added to both MacroPad and Computer.
=> Added MacroPad RPC Home Assistant code

MacroPad_RPC_Home_Assistant/boot.py, MacroPad_RPC_Home_Assistant/code.py, MacroPad_RPC_Home_Assistant/rpc.py, MacroPad_RPC_Home_Assistant/rpc_ha_server.py
I noticed this error when testing my code again.
=> Last minute fixes for MacroPad RPC Home Assistant Code

MacroPad_RPC_Home_Assistant/code.py
One last second change. This is more of a sanity check on the value.
=> Check that key_number is usable for RPC MacroPad guide

HalloWing_Cat_Toy/code.py
Update OnDiskBitmap code to take a filename string with CP7
Replace displayio.Sprite with displayio.TileGrid
Replace board.A0 with board.SPEAKER
Replace busio.I2C(...) with board.I2C()
Correct the spelling of indices
Learn Guide: https://learn.adafruit.com/hallowing-cat-toy
Guide Changes needed:
Page: https://learn.adafruit.com/hallowing-cat-toy/code
* Section: As is audio: https://learn.adafruit.com/pages/13817/elements/3005336/download
* Section: Displaying Images:  Replace `Sprite` with `TileGrid`. and https://learn.adafruit.com/pages/13817/elements/3005344/download
* Section: NeoPixel Effects: https://learn.adafruit.com/pages/13817/elements/3005348/download - correct spelling of indices
=> HalloWing Cat Toy: Update for CP7

Pathfinder/pathfinder_auto.py, Pathfinder/pathfinder_touch.py
Learn Guide: https://learn.adafruit.com/pathfinder
=> Pathfinder: Update for CP7

CircuitPython_sdcardio_sdioio/show_bitmaps.py
Learn Guide: https://learn.adafruit.com/adafruit-microsd-spi-sdio
=> CircuitPython sdcardio sdioio: Update for CP7

PyLeap_NeoPixel_demo/code.py
I've updated the code.py file that is used for the PyLeap demo. This was updated so that the pixelbuf library isn't needed to run this demo. This app will only require the neoPixel.mpy file.
=> Updated PyLeap Demo Code

Ratcatcher_CPX/code.py
adding code for ratcatcher device
=> code for ratcatcher device

MacroPad_Scramble_Lock/code.py
Code for guide https://learn.adafruit.com/scrambled-number-security-keypad/overview
=> Create code.py for new guide

BLE_Gesture_Mouse/code.py
Adding code for BLE Gesture Mouse Learn Guide. Uses the Feather Sense to act as a BLE mouse. Accelerometer readings act as x and y movements, onboard button is left click and proximity sensor enables scrolling combined with tilting up/down
=> Adding code for BLE gesture mouse guide

BLE_Gesture_Mouse/code.py
Updating code with edits from Basecamp. Using map_range() for accelerometer to mouse movements rather than a bunch of if statements.
=> Updating code for BLE gesture mouse

CircuitPython_Templates/audio_find_pins/code.py, CircuitPython_Templates/cap_touch_pin_script/.circuitpython.skip, CircuitPython_Templates/cap_touch_pin_script/code.py, CircuitPython_Templates/i2c_find_pins/code.py, CircuitPython_Templates/i2s_find_pins/code.py
My Pylint caught the issue with the cap touch script (since it doesn't ignore the skip file), so I fixed it and removed the skip file.
There are more files incoming, but they need to document the I2S pin script, so I need the URL to be valid, so I'm submitting it separately.
=> Add I2S pin script, fix cap-touch script

CircuitPython_Templates/i2s_mp3_playback/code.py, CircuitPython_Templates/i2s_wav_playback/code.py, MP3_Playback_RP2040/Pico_I2S_WAV/code.py
Per @dhalbert's request, I have simplified the WAV playback code. We can show the pause/resume function in a different template.
=> Simplify WAV example.

PyLeap_CPB_NeoPixel_Blinky_demo/code.py, PyLeap_NeoPixel_Blinky_demo/code.py
Created a Blink demo for our device enabled guides that works with Circuit Playground Bluefruit. This snippet of code will be part of the "PyLeap device enabled - Blinky!" learn guide.
=> Created a Blink demo for PyLeap Learn guide

EyeLights_Accelerometer_Rings/code.py
First demo for LED glasses + driver board. Simple thing to get folks started. Establishing the “EyeLights_” prefix for related projects.
=> Add EyeLights accel input demo

Raspberry_Pi_Animated_Gif_Player/animatedgif.py, Raspberry_Pi_Animated_Gif_Player/code.py, Raspberry_Pi_Animated_Gif_Player/mini_pitft_player.py, Raspberry_Pi_Animated_Gif_Player/pygame_player.py
=> Add Rotary Gif Players

Feather_Sense_Audio_Visualizer_13x9_RGB_LED_Matrix/code.py
Adding code for the RGB Matrix QT audio visualizer. Uses a Feather Sense to sample audio that is visualized with the RGB LEDs with ulab.
=> Adding code for the RGB Matrix QT audio visualizer

.github/workflows/githubci.yml
=> re-add trinket

ABC_Soundboards_for_NeoTrellis/code.py
This is proof of concept for @TheKitty to work on a fork and local branch using git and making a PR.
Sorry it is only the one change.
=> Updated ABCs code.py with license

3D_Printed_Bionic_Eye/3D_Printed_Bionic_Eye.ino, 3D_Printed_Bionic_Eye/code.py, 3D_Printed_Daft_Punk_Helmet/3D_Printed_Daft_Punk_Helmet-Front-Animation/3D_Printed_Daft_Punk_Helmet-Front-Animation.ino, 3D_Printed_Daft_Punk_Helmet/3D_Printed_Daft_Punk_Helmet-Front-Animation/code.py, 3D_Printed_Daft_Punk_Helmet/3D_Printed_Daft_Punk_Helmet-Side-Animation/3D_Printed_Daft_Punk_Helmet-Side-Animation.ino, 3D_Printed_Daft_Punk_Helmet/3D_Printed_Daft_Punk_Helmet-Side-Animation/code.py, 3D_Printed_Guardian_Sword/3D_Printed_Guardian_Sword.ino, 3D_Printed_LED_Fire_Horns/3D_Printed_LED_Fire_Horns.ino, 3D_Printed_LED_Fire_Horns/code.py
First PR with using local Git for file editing
=> First batch of license file changes

EyeLights_Fire/EyeLights_Fire/EyeLights_Fire.ino, EyeLights_Fire/EyeLights_Fire_CircuitPython/code.py
Keeping an eye on CI, won’t request review until it passes. Thx.
=> Add “Fire” demo for EyeLights (CircuitPython and Arduino)

EyeLights_Blinky_Eyes/EyeLights_Blinky_Eyes/EyeLights_Blinky_Eyes.ino, EyeLights_Blinky_Eyes/EyeLights_Blinky_Eyes_CircuitPython/code.py
Keeping an eye on CI to see if this passes, will make edits as needed until green light.
=> Add EyeLights blinky eyes, both CircuitPython and Arduino

Piano_In_The_Key_Of_Lime/NeoPixel0/code.py, Piano_In_The_Key_Of_Lime/NeoPixelAll/code.py, Piano_In_The_Key_Of_Lime/PianoInTheKeyOfLime/code.py, Piano_In_The_Key_Of_Lime/SingleTone/code.py, Piano_In_The_Key_Of_Lime/SlideSwitch/code.py, Piano_In_The_Key_Of_Lime/StartStopTone/code.py, Piano_In_The_Key_Of_Lime/TouchA1/code.py, Piano_In_The_Key_Of_Lime/TouchAll/code.py
Updated so it'll run on Bluefruit as well - thought it might be good for PyLeap.
=> Lime update

NeoPixel_Rings_Lamp/code.py
hiya @TheKitty code for our neopixel ring lamp project is ready to review, thanks!
=> neopixel ring lamp code

Nunchuck_Laser/code.py
=> Added Nunchuck Laser Code

Nunchuck_Laser/code.py
Added a couple of quick features such as an option to invert the pitch and a settable brightness level.
=> Nunchuck Laser code improvements

CircuitPython_Display_Text/updating_text_example/code.py
Adds an example of how to properly update the text in a label over time.
For use on this page once published: https://learn.adafruit.com/circuitpython-display_text-library/label-updating
=> Updating labels

Big_Switch_KB2040/code.py
=> code for big switch kb2040

PyLeap_CPB_EyeLights_LED_Glasses_RainbowSwirl/code.py, PyLeap_CPB_EyeLights_LED_Glasses_Sparkle/code.py
PyLeap_CPB_EyeLights_LED_Glasses_RainbowSwirl & Sparkle
the code.
process.
Thank you again for contributing!  We will try to …
=> Adding two example projects to PyLeap

QT_Py_Acrylic_Lamp/code.py
=> code for qt py acrylic lamp

PyGamer_Improved_Thermal_Camera/code.py
1) replace splash bitmap graphics `with...` code
2) accommodate changes in the `ulab` UI
3) add free memory performance monitoring
=> Update Improved Thermal Camera code.py for CircuitPython v7.x compatibility

Macropad_2FA_TOTP/code.py
=> Macropad_2FA_TOTP typo

CircuitPython_Templates/status_led_one_dotstar_rgb/code.py
For Template system - boards like ItsyBitsy M4 Express
=> Code for a board with one DotStar on board

Cooperative_Multitasking/neopixels-buttons/code.py, Cooperative_Multitasking/no-asyncio-one-led/code.py, Cooperative_Multitasking/no-asyncio-two-leds-does-not-work/code.py, Cooperative_Multitasking/no-asyncio-two-leds/code.py, Cooperative_Multitasking/one-led-buttons/code.py, Cooperative_Multitasking/one-led/code.py, Cooperative_Multitasking/two-led-buttons/code.py, Cooperative_Multitasking/two-leds/code.py
Move code in https://learn.adafruit.com/cooperative-multitasking-in-circuitpython-with-asyncio to here.
=> move Cooperative Multitasking code to repo

CPB_heart_rate_display/code.py
Code for CPB heart rate display.
=> Initialize project code

Make_It_A_Keyboard/strings/code.py
Simply fixing a comment in a code example.
=> Updated comment to have the correct text being sent in the following line of code.

FunHouse_Arduino_Demos/selftest/selftest.ino
now works with latest release!
=> fix funhouse factory test

ESP32_S2_WiFi_Tests/JSONdemo/JSONdemo.ino, ESP32_S2_WiFi_Tests/WiFiSSLClient/WiFiSSLClient.ino, ESP32_S2_WiFi_Tests/WiFiWebClient/WiFiWebClient.ino
we have to explicitly say we don't want to load a root certificate nowadays!
=> fix esp32 wifi demos

Adafruit_QT_Py_ESP32-S2/Analog_In/code.py, Adafruit_QT_Py_ESP32-S2/Capacitive_Touch_One_Pin/code.py, Adafruit_QT_Py_ESP32-S2/Capacitive_Touch_Two_Pins/code.py, Adafruit_QT_Py_ESP32-S2/Digital_Input/code.py, Adafruit_QT_Py_ESP32-S2/Storage/boot.py, Adafruit_QT_Py_ESP32-S2/Storage/code.py, CircuitPython_Templates/i2c_mcp9808/code.py, CircuitPython_Templates/storage_boot_py/boot.py, CircuitPython_Templates/storage_boot_py_neopixel/boot.py
Includes template code for QT Py ESP guide, some template code fixes, and a new boot.py for ESP32-S2 boards.
=> Code for QT Py ESP, and template fixes.

CircuitPython_Neko_Cat/code.py
This is a new version of the Neko Cat CircuitPython project.
This version has optional touch interaction, user can touch the display to place a laser dot that Neko will chase.
Also updated several docstrings.
=> update neko cat. Touch interaction and doc strings.

MagTag_Google_Sheets/naughty_nice/code.py, MagTag_Google_Sheets/weekly_planner/code.py
Learning System guide is currently busted due to Google deprecating the Sheets V3 API.
This PR changes code for two projects to use TSV (tab-separated-values) rather than JSON…and no longer needs the API, whatever the version. Tested, works.
Guide still needs updating with new instructions, I’ll work on that, but this addresses the code problems.
=> Code now uses TSV instead of JSON to fix Google V4 API issue

NeoPixel_Mini_VU_Meter/code.py
Adding code the NeoPixel Mini VU Meter Learn Guide. Using a QT Py RP2040, PDM mic and strip of 16 neopixels
=> Adding code for NeoPixel mini VU meter

Rotary_Phone_Keypad/boot.py, Rotary_Phone_Keypad/code.py
rotary phone dial pulse input device using Kee Boar KB2040
=> Rotary phone USB hid input first commit

Three_Button_USB_FootSwitch/code.py
code for three button foot switch
=> code for three button foot switch

IS31FL3741_DisplayIO/sports_glasses/code.py
Small change to make the code more consistent with other examples.
=> Change IS31FL3741 DisplayIO switch check

Single_Button_Footswitch/code.py
code for single button footswitch
@TheKitty Hiya, I wanted to update the code for our single button foot switch guide since it pre-dates the learn guide repo and the embed code is for circuit python V2. Thanks! 
Guide: https://learn.adafruit.com/USB-foot-switch-circuit-python/software
=> code for single button footswitch

Motion_Buddy/code.py
https://learn.adafruit.com/exercise-buddy/overview
On behalf of Charlyn G
=> Code for guide Exercise Buddy

Ukulele/code.py
This is for #1999.
Tested in forums:
https://forums.adafruit.com/viewtopic.php?f=57&t=187856
but guess I never PR'd actual fix.
=> Update Ukulele Code

CircuitPython_Knob_Sketcher/feather_sketcher/code.py
Add knob sketcher code for upcoming guide.
=> Add knob sketch code

CircuitPython_Knob_Sketcher/feather_sketcher/code.py
Minor changes to match actual build wiring and desired behavior.
=> Update Feather Knob Sketcher

Adafruit_ESP32_Arduino_Demos/ESP32_sleeptest/ESP32_sleeptest.ino, ESP32_S2_WiFi_Tests/JSONdemo/JSONdemo.ino
the power select pin is inverted now
=> update example for esp32-s2 feather

Adafruit_ESP32_Arduino_Demos/ESP32_sleeptest/ESP32_sleeptest.ino
we need to be a little manual for the feather esp32 v2!
=> update for feather v2

Factory_Tests/Feather_ESP32_V2_FactoryTest/Feather_ESP32_V2_FactoryTest.ino, Factory_Tests/QTPy_ESP32C3_FactoryTest/QTPy_ESP32C3_FactoryTest.ino
for qt py c3 and esp32 v2 feather
=> Add 2 more factory tests

ESP32_S2_WiFi_Tests/CPy_Native_WiFi_Test/code.py, ESP32_S2_WiFi_Tests/CPy_Native_WiFi_Test/secrets.py, Factory_Tests/KB2040_FactoryTest/KB2040_FactoryTest.ino
also add a wifi demo test in a standalone folder
=> factory demo for kb2040

CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py
Adds `try`/`except` blocks to handle WiFi and Adafruit IO disconnects gracefully, in a way that ensures the code will continue to run.
=> Update WiFi example.

PyBadge_Conference_Badge/code.py
These changes are to make the conference badge more readable and have been updated with better Python coding I've picked up since I originally made this.
=> Update PyBadge Conference Badge to be more readable

MIDI_Foot_Pedal/code.py
=> adding code for midi foot pedal

PyPortal_User_Interface/code.py
the code.
Fixes blank screen/barely legible text on Titano. Without these changes the code *appears* to not function on a Titano which is confusing for newbies.
Does not address PyPortal Pynt.
process.
Tested on Titano.
=> Update PyPortal User Interface code to support Titano

PyPortal_NeoPixel_Color_Picker/code.py
Fixed error:
Warning: The group property is being deprecated. User code should be updated to add the Button directly to the Display or other Groups.
=> Fixed button issue with deprecated group property

MIDI_Foot_Pedal/code.py
updated code for midi foot pedal to print potentiometer values in both serial and plotter in Mu Editor
=> update code for midi foot pedal

CLUE_Sensor_Plotter/code.py, CLUE_Sensor_Plotter/plotter.py
Update of CLUE plotter from this guide:
https://learn.adafruit.com/clue-sensor-plotter-circuitpython/circuitpython-sensor-plotter
to deal with hitting memory limit issues.
Tested on CLUE with CP 7.2.4
=> Update CLUE Plotter

CircuitPython_Templates/asyncio/code.py
Decided using `animation_controls` across all functions made it unclear. Also updates a `buttons` plural to `button` since there is only one in this example.
Tested the ability to host GIFs on GitHub. The asyncio template supports two hardware setups, one using a built-in button, and one using an external button. I wanted the GIF included in the template to at least match the hardware button set up, since we opted to only do one GIF and not redo it for every board guide in which this template is included. The Learn system allows you to use the Media>Remote URL option with a GitHub link (also tested this). So my plan is to include a template area directing the author to choose from one of the included GIF files, depending on how the button is setup for a given board. That way it at least …
=> Code tweak, GIF upload.

Adafruit_Feather_ESP32-S2/asyncio/code.py
Code already approved elsewhere. This is specifically for the Feather ESP32-S2.
=> Add asyncio template code for Feather ESP32-S2

LittleConnectionMachine/CircuitPython/code.py, LittleConnectionMachine/RaspberryPi/audio.py, LittleConnectionMachine/RaspberryPi/chaser.py, LittleConnectionMachine/RaspberryPi/cm1.py, LittleConnectionMachine/RaspberryPi/cpuload.py
=> Add LittleConnectionMachine project (Pi + CircuitPython)

Glider_Paper_Airplane_Controller/code.py
Code for the Glider Paper Airplane Controller Learn Guide. Uses the nRF52840 LED Glasses Driver board for BLE and accelerometer to control Glider.
=> Adding code for Glider

LittleConnectionMachine/CircuitPython/code.py
Super minor change, just pin numbers, but makes for better pictures
=> Change pins to make wiring diagram easier to read

ESP32S2_TFT_AdBlocker/AdBlockerDNSServer.cpp, ESP32S2_TFT_AdBlocker/AdBlockerDNSServer.h, ESP32S2_TFT_AdBlocker/ESP32S2_TFT_AdBlocker.ino, ESP32S2_TFT_AdBlocker/LICENSE, ESP32S2_TFT_AdBlocker/README.md, ESP32S2_TFT_AdBlocker/config.h, ESP32S2_TFT_AdBlocker/extras/secrets.json, ESP32S2_TFT_AdBlocker/filesystem.cpp, ESP32_S2_WiFi_Tests/JSONdemo/JSONdemo.ino
same as uf2 given to @jedgarpark
=> esp32-s2 tft 'nah' demo

I2C_Multiple_Same_Address/arduino/multi_bme280_2x/multi_bme280_2x.ino, I2C_Multiple_Same_Address/arduino/multi_bme280_3x/multi_bme280_3x.ino, I2C_Multiple_Same_Address/arduino/multi_bme280_4x/multi_bme280_4x.ino, I2C_Multiple_Same_Address/circuitpython/multi_bme280_2x/code.py, I2C_Multiple_Same_Address/circuitpython/multi_bme280_3x/code.py, I2C_Multiple_Same_Address/circuitpython/multi_bme280_4x/code.py
Code for guide on using multiple same address I2C devices.
=> Add code for multi I2C guide

Laser_Harp/code.py
Adding code for laser harp project. uses tca9548a to use 8 tof sensors. sends midi over uart to music maker featherwing
=> Adding code for laser harp

NeoPixel_Neon_Signs/code.py
=> code for neopixel neon sign

Pi_In_Stock_Notifier/code.py
Adding code for pi in stock notifier guide. sends a query to twitter to check if pi's are in stock at adafruit
=> Adding code for pi twitter notifier

Pi_In_Stock_Notifier/code.py
updating indexes for time comparison and moving no_tweet_text so the screen is not blank on the first query
=> updating circuitpython code

Laser_Harp/laser_harp_two_voice.py, Laser_Harp/usb_midi_code.py
adding two more examples for the laser harp project
one is code using usb midi instead of midi over uart
second is two voices depending on height as well as pitch bend control
=> adding more laser harp examples

GemmaM0_Pinball/code.py
fixed an issue w old pinball controller code
=> added pinball code

Traffic_Light_Wearable/code.py
adding code for the traffic light wearable project.
=> Adding code for traffic light wearable

Traffic_Light_Wearable/code.py
changing pin assignments- have other plans for the STEMMA connector now
=> updating pins

EInk_Weather_Station/adafruit_epd_weather/adafruit_epd_weather.ino
This fixes an issue where everything was red.
=> Convert eInk Weather Station to ThinkInk Driver

RCWL1601_I2C/arduino_oledtest/arduino_oledtest.ino, RCWL1601_I2C/arduino_simpletest/arduino_simpletest.ino
=> add rcwl demo files

EInk_Weather_Station/adafruit_epd_weather/adafruit_epd_weather.ino
This is a copy pasta fix for #2175.
=> Fix initializer for eInk Weather Station

NeoTrellis_MIDI_Feedback_Controller/code.py
NeoTrellis 8x8 with Feather RP2040 as MIDI controller with bi-directional message feedback for LED-to-GUI sync.
=> first commit neotrellis 8x8 MIDI feedback controller code

Adafruit_QT_Py_ESP32-S3/analog_in/code.py
=> updating analog in

Daily_Cheer_Automaton/CircuitPython/code.py
=> Updated daily cheer to use sdcardio

PyPortal_Mirror_Display/code.py, PyPortal_Mirror_Display/openweather_graphics.py
Updating the code file to use a delta to check the light sensor percentage over time. Also removing an older CP method from openweather_graphics.py.
=> Updating code for pyportal mirror project

Feather_ESP32-S2_TFT_Azure/code.py
updating the Labels to include x and y coordinates in the creation rather than outside
=> Updating Label x and y

Cassette_Player_Mod_L9110/code.py
Fixing a minor bug - variable definition before the loop
=> updating cassette code

Feather_ESP32-S2_TFT_Azure/code.py
Updating code for better connection stability after testing this past week
=> updating first Azure tutorial code

GitHub_Actions_Status_Tower_Light/actions_status.py
Existing code meant, on CTRL+C exit, if on, the light would remain on, and the buzzer would continue beeping. Updated code to catch the `KeyboardInterrupt`, run the `reset_state()` function, and print the exiting status to the serial console.
=> Reset state on CTRL+C exit.

Lola_Droid/code.py
=> adding code for Lola Droid

Owl_IR_TV_Remote/code.py
Adding code for the Owl IR TV Remote learn guide
=> Adding IR owl remote code

NAU7802_Food_Scale/callibration.py, NAU7802_Food_Scale/code.py
Adding main code and callibration.py file for the NAU7802 Food Scale learn guide.
=> adding code for the food scale learn guide

QT_Py_ESP32-S2_Sunrise_Lamp/AIO/code.py, QT_Py_ESP32-S2_Sunrise_Lamp/NTP/code.py
=> Add code for Sunrise Lamp

Buzzing_Mindfulness_Bracelet/code.py
just a simple comment correction :bowtie:
=> Correct pin number in Buzzing Mindfulness Bracelet comment

NAU7802_Food_Scale/calibration.py, NAU7802_Food_Scale/callibration.py, NAU7802_Food_Scale/code.py
Fixing all misspellings of calibration. Also tweaks to code after running long-term with larger weight.
=> Updating code and calibration

Azure_Food_Scale/calibration.py, Azure_Food_Scale/code.py
Adding code for the Azure Food Scale project
=> Adding code for the Azure Food Scale guide

Keypad_Examples/macropad_hid/code.py
I made some copy pasta error when adding an example. The code before this change is the wrong code, and is not the HID example I meant.
=> Incorrect code for numberpad HID example

ST_Combo_Boards/lis3mdl_lsm6ds_test/lis3mdl_lsm6ds_test.ino
Adding definition for the LSM6DSTR-C library.
=> Adding definition for LSM6DS3TRC

Flying_Fader/code.py
Motorized slide potentiometer demo example in CircuitPython.
=> first commit flying fader demo

Flying_Fader/code.py
demo code for motorized slide pot on Feather, now on a pin for touch that works (exists) on Feather RP2040.
=> changed touch pin so it'll work on Feather RP2040 (was on A4, now on A3)

MagTag_Weather/code.py
Updates MagTag Weather project:
https://learn.adafruit.com/magtag-weather
to improve location specification. Can now specify as either a string location or as a lat/lon tuple for cases where city name is ambiguous:
https://forums.adafruit.com/viewtopic.php?f=60&t=192681
Guide will also need some updating to discuss this new feature.
=> Update MagTag Weather code

Two_Way_Servo_Telegraph/code.py
Adding code for two way telegraph display project.
=> Adding code for two way telegraph guide

Two_Way_Servo_Telegraph/code.py
Just caught a minor value error that was left in the loop from testing. Should be polling IO every 5 seconds, not 2.
=> Updating value in code.py

Step_Switch_Pico_Demo/code.py
basic demo of using the LED step switches ('808' switches) with an RPi Pico RP2040
=> first commit step switch pico demo code

CircuitPython_GameAndWatch_Octopus/code.py, CircuitPython_GameAndWatch_Octopus/octopus_game_helpers.py
Fix commented SDCard configuration line.
Remove an extra empty line.
Make a comment more specific.
=> Octopus Game tweaks

Flying_Fader_Arduino/Flying_Fader_Arduino.ino
adding arduino version of the basic flying fader demo
=> Adding arduino version of flying fader demo

Feather_Sense_Audio_Visualizer_13x9_RGB_LED_Matrix/audio_spectrum_lightshow/code.py
Updating library import for CP8 compatibility.
=> Updating library import for CP8

Step_Switch_Pico_Demo/code.py
Redid button code to use keypad library, which made it simpler
=> changed step switch party demo to use keypad library

CircuitPython_ESP32_Camera/esp32-s3-eye-lcdview/code.py
This adds a small feature to the first example, so that the user can use a test pattern instead of the live camera image
=> Add ability to toggle color bars on/off

Step_Switch_Pico_Demo_Arduino/Step_Switch_Pico_Demo_Arduino.ino
arduino version of the step switch pico demo for guide
=> first commit Arduino version of step switch pico demo

WiFi_Mailbox_Notifier/code.py
Use `supervisor.reload()` instead of `microcontroller.reset()` when errors occur to preserve the `alarm.sleep_memory[]` error count. If too many reloads occur (e.g. the issue is not being resolved by a reload), then do a hard reset with `microcontroller.reset()`.
=> Update WiFi mailbox notifier code.

Walkmp3rson/code.py
Updated to use Feather RP2040 (left in a line to uncomment for Feather M4), changed rotary encoder I2C address to default 0x36, added audio.pause()/audio.resume() between track changes to remove noise.
=> adjusted for Feather RP2040

WiFi_Mailbox_Notifier/code.py
Feature addition due to Adafruit IO limitation. Otherwise, clarified comments etc.
=> Add more features and tighten up code.

CLUE_Sensor_Plotter/code.py, CLUE_Sensor_Plotter/plotter.py
Updating the CLUE plotter with CP8 for upcoming PyLeap project. 
-Adding PlotSource to plot_source import (otherwise error is thrown when changing params with A button) 
-Changing some font spacing in plotter.py so that nothing is cut off
=> Updating CLUE plotter

CircuitPython_CLUEbot/code.py, CircuitPython_CLUEbot/robot.py
=> Added CLUE Robot Code from CircuitPython Day Build

Darth_Faders/code.py
Darth Faders -- motorized slide potentiometer sculpture/prop code
=> first commit Darth Faders code

Trombone_Champ_Controller/code.py
Adding CircuitPython code for the Trombone Champ Controller learn guide. Uses an arcade button to send a space bar keypress and a neoslider to send mouse cursor movement.
=> Adding code for trombone champ controller

PyLeap_CLUE_BLE_NeoPixels/code.py
Updating animation value since a value of 0 seems to block out the entire animation in cp 8.0
=> Updating neopixel animation value

LED_Noodle_Lantern/code.py
adding code for led noodle lantern cc @TheKitty
=> adding code for led noodle lantern

Cheekmate/Arduino/Cheekmate/Cheekmate.ino
Register was set wrong, one-line fix
=> Small fix to Arduino Cheekmate

CLUE_Servo_Barometer/code.py
Adding code for the CLUE Servo Barometer project. Servo's range is mapped to barometric pressure range. CLUE's display shows temperature and pressure readings. A button and B button determine if the readings are shown in US or imperial units.
=> Adding code for CLUE servo barometer

Feather_Freezer_Alarm/code.py
Code from https://gist.github.com/matt-desmarais/781653dd03d5851c6c87a0c39371e7f2 for new Learn guide
=> Create code.py for Door Freezer Alarm

CLUE_Servo_Barometer/code.py
Updating code for CLUE barometer.
=> Updating CLUE barometer

Pico_W_CircuitPython_WiFi_Examples/Pico_W_Twitter_Feed/code.py
Updating some comments on the twitter example
=> Updating twitter example

Split_Ortho_Keyboard/code.py, Split_Ortho_Keyboard/keymaps.py
Split ortho keyboard code and keymap.py file.
=> first commit code and keymap config file

Introducing_CircuitPlaygroundExpress/CircuitPlaygroundExpress_CapTouch_Advanced/code.py
Fixes #747 comment.
File also moved to conform to standards.
=> Fix licensing to resolve CI issue.

CircuitPython_CLUEbot/robot.py
=> Rearranged function order to make them easier to explain in guide.

CPX_Halloween_Bat/code.py
Adding code for Circuit Playground Express bat. Uses two servos to flap wings. Onboard NeoPixels display the comet animation.
=> Adding code for CPX bat

CPX_Halloween_Bat/code.py
Changing attributes for the wing angles to variables rather than hard coding
=> Updating code

Halloween_Neon_Signs/Ghost.py, Halloween_Neon_Signs/Reaper.py, Halloween_Neon_Signs/Wolf.py
=> Adding halloween neon code

Magic_Band_Reader/code.py
Adding code for magic band reader
=> Adding code for magic band reader

PicoW_CircuitPython_HTTP_Server/code.py
Adding code for Pico W HTTP server. Sets static IP address, serves HTML as f string, uses DS18B20 temp sensor.
=> Adding code for HTTP server

BrainCraft_Google_Assistant/gv_buttontotalk.py
=> Update Google Assistant to work on Python versions later than 3.7

CircuitPython_IBM_XT_Keyboard_QTPy_RP2040/code.py
New code for upcoming guide is complete!
=> Ibm pc keyboard adapter

PyPortal_MQTT_Control/code.py
The MQTT library has changed to have an embedded MQTT class. This PR updates the reference to it.
=> Update MQTT class reference

PicoW_CircuitPython_HTTP_Server/code.py
Updating HTML so that it displays better on mobile.
=> Updating HTML

PiCowbell_Proto/i2c_scan/code.py
Tested on Pico with PiCowbell and MCP9808.
=> Add PiCowbell CircuitPython I2C scan.

Trinket_Ultrasonic_Rangefinder/README.md, Trinket_Ultrasonic_Rangefinder/code.py
=> Fix index out of range error

I2C_Multiple_Same_Address/arduino/multi_tca_2x/multi_tca_2x.ino, I2C_Multiple_Same_Address/circuitpython/multi_tca_2x/code.py
Add two new code examples for updating guide:
https://learn.adafruit.com/working-with-multiple-i2c-devices
=> Add multiple TCA example code for guide update

I2C_Multiple_Same_Address/arduino/multi_tca_2x/multi_tca_2x.ino
=> Add curlies

EYESPI/Arduino/Color/EYESPI_Test/EYESPI_Test.ino
Canvas was wrong size on narrow screens. Fixed!
=> EYESPI_Test.ino: fix canvas height

NeoPixel_Sprite_Weather_Display/code.py
Refactor of code.py to use ticks. Also adjusted to use functions.
=> Refactoring code dot py

NeoPixel_Sprite_Weather_Display/code.py
while running the project i realized i had forgotten the text update line after adding in the functions
=> adding text update

Drum_Trigger_2040/code.py
code for sixteen step drum trigger w KB2040 and AW9523 LED driver, 14-seg display, rotary encoder, step switches, tactile switch
=> first commit drum trigger code

Web_Workflow_Quickstart/env.py
With CP 8 beta 6 out now, this change is required. The rest of the guide is already updated.
=> Updated Web Workflow utility script env.py to use settings.toml instead of .env files

Pico_W_CircuitPython_WiFi_Examples/Pico_W_Adafruit_IO/code.py, Pico_W_CircuitPython_WiFi_Examples/Pico_W_Azure_IoT_Central/code.py, Pico_W_CircuitPython_WiFi_Examples/Pico_W_Basic_WiFi_Test/code.py, Pico_W_CircuitPython_WiFi_Examples/Pico_W_JSON_Feed/code.py, Pico_W_CircuitPython_WiFi_Examples/Pico_W_Requests/code.py, Pico_W_CircuitPython_WiFi_Examples/Pico_W_Twitter_Feed/code.py
Updating SSID and SSID password variables to match settings dot toml example page
=> updating variable names from guide feedback

CircuitPython_Mastodon_API_Examples/Read_From_Mastodon/code.py, CircuitPython_Mastodon_API_Examples/Send_To_Mastodon/code.py, NeoPixel_Sprite_Weather_Display/code.py, PicoW_CircuitPython_HTTP_Server/code.py, Scrolling_Alphanumeric_Countdown_Clock/code.py
Updating SSID and PW variables for match settings dot toml example
=> updating variable names

PyPortal_EZ_Make_Oven/code.py
I wanted an easier way to switch between the various solder reflow profiles already available on the PyPortal Device that did not require a connection to my computer and a modification of the config.json file. For instance, after running a Sn63/Pb37 profile I might want to run a custom profile for smoothing out Hot Glue that would be used to diffuse LED light. I wanted to be able to make the changes while only interacting with the PyPortal and without making a write change to the on disk config.json file. To that end this change is submitted that supports that effort.
Being able to dynamically select a profile was limited to being in memory since the code that is running only recognizes the disk as read only. To support dynamic profile selection it has to be done all in memory. I of …
=> ez make oven feature enhancement - dynamic profile selection in memory

PicoW_CircuitPython_HTTP_Server/code.py
Missing type annotation, noticed by @anecdata.
=> PicoW webserver add type annotation

See_N_Say/code.py
See N Say code for KB2040 + I2S amp and MiniBoost
=> first commit see n say code

CircuitPython_Scorpio_Tree/code.py
@djecken Please verify the code still works as expected. I modified it slightly based on pylint messages.
=> Add code for the sciorpio holiday tree project

White_Noise_Rocket/code.py
=> updating white noise rocket

CircuitPython_Templates/power_management_measuring_battery/code.py
Single program to sort out which chip is available, and then use it for battery measurement.
=> Adding LC/MAX measurement code.

microSD_BFF_Examples/ReadWriteQT/ReadWriteQT.ino
Adding an Arduino test for the microsd bff
=> Adding Arduino code

NeoKey_BFF_Examples/Arduino_NeoKey_Example/Arduino_NeoKey_Example.ino, NeoKey_BFF_Examples/CP_Keyboard_Example/code.py
Adding CircuitPython and Arduino examples for NeoKey BFF
=> adding example code for neokey bff

NeoKey_BFF_Examples/CP_Keyboard_Example/code.py
=> Adding delay

Magic_Band_Reader/code.py
updating code for magic band reader per user feedback on adafruit forums
=> updating code for magic band reader

Meowsic_MIDI/code.py
first commit meowsic midi code
=> meowsic midi code

Feather_ESP32-S3_Reverse_TFT_Primary_Guide/CircuitPython_CapTouch/code.py
adding touchio example for s3 reverse tft
=> adding touchio example

CircuitPython_SNES_Mouse/code.py
=> Add code for SNES mouse to USB HID with CircuitPython

Factory_Tests/Feather_ESP32S3_ReverseTFT_FactoryTest/Feather_ESP32S3_ReverseTFT_FactoryTest.ino
adding factory demo for s3 reverse tft
=> adding s3 reverse tft factory test

Star_Fragment_Lamp/code.py
Adding code for star fragment lamp. essentially a reverse sunrise lamp (turns on at sunset)
=> adding code for star fragment lamp

Bubble_Table_IR_Control/code.py
Code for IR Controlled Bubble Table using LED Animations Library
=> Bubble Table Code

PiCowbell_Adalogger_Examples/Arduino_PiCowbell_Adalogger_Example/Arduino_PiCowbell_Adalogger_Example.ino, PiCowbell_Adalogger_Examples/CircuitPython_Datalogger/code.py, PiCowbell_Adalogger_Examples/CircuitPython_Real_Time_Clock/code.py
Adding CP and Arduino examples for PiCowbell Adalogger product guide
=> Adding PiCowbell Adalogger Examples

Metro_M7_Examples/Digital_Input/code.py, Metro_M7_Examples/WiFi/code.py
Adding code examples for digital input and wifi
=> adding code examples for Metro M7

CircuitPython_Templates/airlift_ble_example/code.py
adding the BLE example to the repo to replace the Learn embed
=> adding BLE airlift example for template page

ChatGPT_Voice_Assistant/assistant.py
=> Added ChatGPT Voice Assistant

Hexpad/code.py
Hexpad chord pad for MIDI instruments code
=> first commit Hexpad code

Robot_Lyre/code.py
Adding code for the robot lyre project
=> adding robot lyre code

Desktop_Air_Monitor/code.py
Adding code for the desktop air monitor project. Logging data with PM2.5 and SCD40 to a display and IO
=> Adding code for the desktop air quality monitor

BLE_Client_Server/server/code.py
=> Update BLE code for CircuitPython 8 compatibility

Desktop_Air_Monitor/code.py
Updating code to remove IO logging and redefine AQI scaling
=> Updating desktop air monitor code

CircuitPython_GetSuperpower_PicoW_OpenAI/code.py
* Use the LED built into the button
* blink while getting text, solid when you can press to get another one
* clear out extra button presses
* allow auto restarting after most exceptions
=> improve guide code

ChatGPT_Bear/assistant.py
Just a small enhancement I thought of while working on my Code page.
=> Add a prompt when script first started

Weather_Wise_Umbrella_Stand/code.py
Adding code for the Weather Wise Umbrella Stand guide
=> Adding code for IoT umbrella stand

Weather_Wise_Umbrella_Stand/code.py
updating loop so that first_run doesn't block turning on the neopixels
=> updating loop

PiCowbell_CAN_Bus_Examples/CircuitPython_PiCowbell_CAN_Bus/code.py
Adding CAN Bus example for PiCowbell guide
=> adding CP example for PiCowbell

Feather_CAN_Bus_RP2040_Examples/CircuitPython_CAN_Bus/code.py
Adding CAN Bus example for the Feather RP2040 CAN Bus guide
=> Adding CAN Bus example

16bit_hello_picowbell_dvi/16bit_hello_picowbell_dvi.ino
Adding the 16bit hello arduino example with adafruit_dvibell_cfg defined.
=> Adding arduino example for picowbell dvi

Weather_Wise_Umbrella_Stand/code.py
Removing adafruit io location. Not needed
=> Updating umbrella code

Canary_Nightlight/code.py
Cleaned up comments, added more customisations, renamed variables to be more applicable.
=> Updated for customisability, readability.

Magic_AI_Storybook/listener.py, Magic_AI_Storybook/story.py
=> Last minute bug fixes for Magic Storybook

Canary_Nightlight/code.py
Corrected a bug where the time checks were written as `if time_passed > time_interval:`, which meant if the time interval was 1 second, the code would trigger at 2 seconds; it is now `>=`.
Corrected comments and a couple of checks to reflect that `time.time()` is an integer in CircuitPython, and therefore time intervals will not act as expected if using a float.
Rearranged the variables at the top to be in a more logical order.
The code was originally written so that even if the network down detection was disabled, it would still be pinging every second. Which, on writing the code walkthrough, I realised is terrible and makes no sense. I know why I wrote it that way though - if the AIO time check occurs while the network is down, it will throw and exception, and reset the board. This …
=> Refactor for better network handling.

Magic_AI_Storybook/listener.py, Magic_AI_Storybook/story.py
When I rewrote the listener in #2509, I simplified it by stripping out some functionality I didn't think was necessary. I was able to stop it from crashing, but this made the reliability much lower. This PR adds the functionality back in, but it is written correctly this time.
After some more testing, I ended up adjusting the parameters until it was picking up what I was saying.
=> Magic Storybook: Added stripped out stuff from listener back in

ANO_Rotary_Encoder_Synth/code.py
Adding code for ANO rotary encoder synth. Uses synthio, five ANO encoders, five alphanumeric displays and one 8x8 matrix.
=> adding code for rotary encoder synth

Computer_Perfection_Synth/code.py
=> fixed comments for MODE switch function

NeoDriver_seesaw_Examples/Arduino_NeoDriver_strandtest/Arduino_NeoDriver_strandtest.ino, NeoDriver_seesaw_Examples/CircuitPython_NeoDriver_seesaw/code.py, NeoDriver_seesaw_Examples/Extended_Bus_NeoDriver_seesaw/code.py
Adding CircuitPython, Arduino and CircuitPython with extended bus examples for NeoDriver guide
=> adding NeoDriver seesaw examples

Factory_Tests/Feather_ESP32S3_TFT_FactoryTest/Feather_ESP32S3_TFT_FactoryTest.ino
Updating the Feather ESP32-S3 TFT Factory Reset to check for either the LC709203F or MAX17048 battery monitors. Tested on both versions of the board.
=> Updating the Feather ESP32-S3 TFT Factory Reset

Desktop_Air_Monitor/code.py, MIDI_Melody_Maker/code.py, MIDI_for_Makers/Receive_MIDI_Over_UART_and_Send_Over_USB/code.py, QT_Py_RP2040_USB_to_Serial_MIDI_Friends/code.py
Updating the desktop air monitor to use try/except for reading the PM2.5 sensor and updating UART MIDI guides to include a timeout in instantiation based on quirk with Metro M7 found by JP
=> updating a few learn guides

runcpm-rp2040-dvi-usb/keyboard-copro/keyboard-copro.ino, runcpm-rp2040-dvi-usb/runcpm-pico/abstraction_arduino.h, runcpm-rp2040-dvi-usb/runcpm-pico/globals.h, runcpm-rp2040-dvi-usb/runcpm-pico/hardware/pico/feather_dvi.h, runcpm-rp2040-dvi-usb/runcpm-pico/runcpm-pico.ino
=> Updates to the code for the Runcpm-pico guide

Window_Skull_Matrix/code.py
While testing the MatrixPortal S3, I was not able to initially get the code to run. After a couple of small changes, which I believe were necessary because of CP changes, it works.
=> Update Window Skull code to run on CircuitPython 8

PlayStation_Controller_Spinner/code.py
PlayStation game of life roulette wheel controller code.
=> first commit playstation roulette controller

PlayStation_Controller_Spinner/code.py
now for QT Py and uses the neopixel as indicator
=> updated PlayStation spinner code for QT Py

Factory_Tests/Feather_ESP32S2_FactoryTest/Feather_ESP32S2_FactoryTest.ino
Adding an updated Factory Reset file for the ESP32-S2 Feather that checks for LC vs. MAX battery monitor
=> Adding updated Factory Reset for ESP32-S2 Feather

Factory_Tests/Feather_ESP32S2_TFT_FactoryTest/Feather_ESP32S2_TFT_FactoryTest.ino
Updating the ESP32-S2 TFT factory test to check for either the LC or MAX battery monitor chip.
=> Updating ESP32-S2 TFT Feather Factory Test

CircuitPython_DVI_Hello_World/code.py
Updating CircuitPython PicoDVI example to use new resolution.
=> Updating CP PicoDVI example

Ikea_Vindriktning_QT_Py_ESP32-S3/code.py
Adding CircuitPython code the Ikea air quality monitor guide
=> Adding code for Ikea air quality monitor

OozeMaster3000/OozeMaster3000.ino
For Erin’s water drip dress. Tested on SCORPIO.
=> Ooze Master 3000: add “splat map” for Erin’s project

Matrix_Portal_Moon_Clock/code.py
Rare occurrence (maybe once/month) but it happens. sandorcourane spotted this and provided the fix in the forums.
=> Fix crash on days without a moon rise or set

Tyrell_Synth/code.py
drone synth built into a Blade Runner building.
=> first commit Tyrell desktop synth code

Factory_Tests/MatrixPortal_S3_FacoryTest/MatrixPortal_S3_FacoryTest.ino, Factory_Tests/MatrixPortal_S3_FactoryTest/MatrixPortal_S3_FactoryTest.ino
I think this requires https://github.com/adafruit/ci-arduino/pull/157 to be merged first.
=> Added MatrixPortal S3 Factory Test

4x4_MIDI_Messenger/code.py
Updating 4x4 MIDI code to include onboard Feather neopixel and move default midi channel to the top
=> Updating 4x4 midi code

FisherPrice_USB_Foot_Pedal/code.py
Fisher-Price Kick Piano foot pedal with keyboard macros code.
=> first commit fisher price usb foot controller with keyboard macros

Grand_Central_M4_Arduino_SD_Card/Grand_Central_M4_Arduino_SD_Card.ino
Adding Arduino micro SD card example for the Grand Central M4
=> Adding arduino micro sd card example

.github/workflows/arduino_cron.yml
Minor fix to adabot's proper name as a follow up to #2567
=> Fix adabot's name in CI

Ambient_Machine/code.py
set mixer buffer size to 2048 and wave file to 1024
=> adjusted buffers

Adafruit_Metro_RP2040/Arduino/Metro_RP2040_SD_Card_Test/Metro_RP2040_SD_Card_Test.ino
Adding Arduino SD card example for Metro RP2040
=> Adding arduino Metro RP2040 SD card example

CircuitPython_Talking_Adabot_Clock/code.py
found bug where it thought 12PM was 12AM
=> fixing 12PM bug

Adafruit_Metro_ESP32-S3/Capacitive_Touch/One_Pin/code.py, Adafruit_Metro_ESP32-S3/Capacitive_Touch/Two_Pins/code.py, Adafruit_Metro_ESP32-S3/Digital_Input/code.py, Adafruit_Metro_ESP32-S3/I2S/Tone_Playback/code.py, Adafruit_Metro_ESP32-S3/I2S/WAV_Playback/code.py, Adafruit_Metro_ESP32-S3/SDCard/SD_Read/code.py, Adafruit_Metro_ESP32-S3/SDCard/SD_Write/code.py, Adafruit_Metro_ESP32-S3/Storage/boot.py, Adafruit_Metro_ESP32-S3/Storage/code.py, Adafruit_Metro_ESP32-S3/analog_in/analog_value/code.py, Adafruit_Metro_ESP32-S3/analog_in/get_voltage/code.py, Adafruit_Metro_ESP32-S3/asyncio/code.py, CircuitPython_Templates/adafruit_io_cpu_temp_neopixel_color/code.py, CircuitPython_Templates/sd_card_read/code.py, CircuitPython_Templates/sd_card_write/code.py
Also fixes issue with one template's code, and adds the SD Card Template code.
=> Metro ESP32-S3 guide code.

Matrix_Portal_S3_Message_Board/demo.py
=> Remove unused code from message board demo

Matrix_Portal_S3_Message_Board/code.py, Matrix_Portal_S3_Message_Board/demo.py
=> Final changes to messageboard demo code to make more readable

FunHouse_HA_Companion/.circuitpython.skip, FunHouse_HA_Companion/code.py
=> Update and Lint FunHouse Home Assistant code to work with settings.toml

FunHouse_Motion_Outlet/.circuitpython.skip, FunHouse_Motion_Outlet/code.py
=> Update and Lint FunHouse Motion Outlet code to work with settings.toml

FunHouse_Pet_Bowl_Sensor/.circuitpython.skip, FunHouse_Pet_Bowl_Sensor/code.py
=> Update and Lint FunHouse Pet Bowl Sensor code to work with settings.toml

Home_Assistant_Sensor/code.py
=> Update and Lint Home Assistant Sensor code to work with settings.toml

Piezo_Driver_Examples/Arduino_Piezo_Driver_Example/Arduino_Piezo_Driver_Example.ino, Piezo_Driver_Examples/CircuitPython_Piezo_Driver_Example/code.py
Adding Arduino and CircuitPython example for the piezo driver guide
=> adding examples for piezo driver

SPI_Breakout_Flash_Info/SPI_Breakout_Flash_Info.ino
Adding spi flash info example to use SPI pins for breakout
=> adding spi flash info example

SPI_Breakout_Flash_Info/SPI_Breakout_Flash_Info.ino
removing comment about other boards
=> remove comment

Matrix_Portal_S3_ESPN_API/CircuitPython/code.py, Matrix_Portal_S3_ESPN_API/get_team_logos.py
Adding CP code and a script for gathering team logos
=> adding code for the ESPN API project

Matrix_Portal_S3_ESPN_API/CircuitPython/code.py
update to add a 0 in front of single digit minute times
=> minor bug fix

Synth_Guitar/code.py
Adding code for the synth guitar project. Uses synthio
=> Adding synth guitar code

Matrix_Portal_S3_ESPN_API/CircuitPython/code.py
the soccer feed was demonstrating unsportsmanlike behavior with the json_stream so adding error handling to pull down the json traditionally in case other sports that aren't baseball, football, basketball or hockey do that as well. the s3 can handle the full json, it's just slower than json_stream
=> Adding more error catching

Bricktunes_LEGO_Color_Synth/code.py
first commit bricktunes LEGO color synth glove. The `cedargrove_chime` library is in the community bundle, but i think it has a path typo (`liibraries`) at the moment, so not sure if that'll cause any issues. I've let @CedarGroveStudios know about the issue.
=> first commit bricktunes code

PowerWash_Controller/code.py
powerwash simulator controller code
=> first commit powerwasher controller code

Factory_Tests/Qualia_ESP32S3_RGB666_FactoryTest/Qualia_ESP32S3_RGB666_FactoryTest.ino
This change makes it first try loading as FocalTouch touchscreen, and if that fails, a CST Capacitive touchscreen. Not sure if this makes it too complicated and if I should just go with #if statements, or if you like it as is.
cc: @ladyada
Note: requires Adafruit_CST8XX_Library 1.1.0
=> Update Qualia image to work with both types of touchscreens

LED_Noodle_Tree/code.py
@TheKitty Hiihi, I'm adding the code for our LED Noodle Tree project, please review. Thanks!
=> Adding code for LED Noodle Tree learn guide

Factory_Tests/Qualia_ESP32S3_RGB666_FactoryTest/Qualia_ESP32S3_RGB666_FactoryTest.ino, Matrix_Portal_S3_Message_Board/lib/messageboard/__init__.py
=> Bug fix for messageboard crashing in certain instances

Matrix_Portal_S3_Message_Board/lib/messageboard/__init__.py
=> Fix another messageboard bug revealed by the first fix

Matrix_Portal_S3_Message_Board/lib/messageboard/__init__.py, Matrix_Portal_S3_Message_Board/lib/messageboard/animations/__init__.py
This time, it's just fixing a visual glitch instead of a crash.
=> One last Bug fix for messageboard

Matrix_Portal_S3_SMS_Scroller/code.py
=> Add SMS Messsage Scroller Project

Ikea_Vindriktning_QT_Py_ESP32-S3/code.py
adding suggestions from https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/2634
=> adding suggestions from forum

LEGO_Lighting/code.py
first commit of the example code for LEGO winter village lighting using AW9523 driver and wired SMD LEDs.
=> first commit LEGO Lighting code

Faderwave_Synth/code.py
reverse hardware oscilloscope code for the faderwave pcb
=> first commit Faderwave synth code

Faderwave_Synth/code.py
some updates to menu functions, max notes, max detune
=> updated Faderwave code

MEMENTO/Basic_Camera/code.py
simplified basic camera example for the starter projects in Memento guide
=> simplified basic camera example

Matrix_Bluetooth_Controlled_LED_Sign/code.py
Simple Code for a Bluetooth-Controlled LED Sign
=> Adding Bluetooth-Controlled LED Sign code

Disconnected_CO2_Data_Logger/code.py, Motorized_Turntable/code.py
Updating two project code files from guide feedback
=> Updating code to CP 8

MEMENTO/Memento_IOT_Doorbell/code.py
Adds finalized code (from S&T demo) for the Memento doorbell camera project
=> Add Memento IOT Doorbell Camera

Rapunzel_Hair/code.py
first commit
the code.
process.
as soon as we …
=> Rapunzel Hair Code

MEMENTO/Wireless_Remote/code.py
added delay for IP address screen
=> added delay for IP address screen

Adafruit_Feather_Sense/code.py, Adafruit_Feather_Sense/feather_sense_sensor_demo/feather_sense_sensor_demo.ino
updating CP and Arduino examples to check for the LSM6DS33 or the LSM6DS3TR-C
=> updating example code for the new feather sense

CAN_Bus_BFF/Arduino/MCP2515_CAN_BFF_Receive/MCP2515_CAN_BFF_Receive.ino, CAN_Bus_BFF/Arduino/MCP2515_CAN_Feather_Send/MCP2515_CAN_Feather_Send.ino, CAN_Bus_BFF/CircuitPython/can_bus_bff_receiver.py, CAN_Bus_BFF/CircuitPython/can_bus_feather_send.py
Adding Arduino and CircuitPython CAN Bus BFF examples
=> adding CAN Bus BFF examples

MEMENTO/Memento_Focus_Stack/code.py
added MEMENTO focus stacking code example
=> first commit MEMENTO focus stacking

STEMMA_Analog_Switch_Examples/Arduino_Analog_Switch_Example/Arduino_Analog_Switch_Example.ino, STEMMA_Analog_Switch_Examples/CircuitPython/code.py
CircuitPython and Arduino examples for using the STEMMA analog switch
=> example code for STEMMA analog switch

CircuitPython_DVI_Hello_World/code.py
Adding a try/except to workaround a MemoryError in CircuitPython 9 beta2 as noted in https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/2746
=> adding try/except to DVI hello world

PiCowbell_Doubler/CircuitPython_PiCowbell_Doubler_Battery_Monitor/code.py
=> Update picowbell doubler CP example

CLUE_Light_Painter/code.py, CLUE_Sensor_Plotter/plotter.py, CircuitPython_CLUEbot/robot.py, CircuitPython_Display_Text/colormask_example/code.py, CircuitPython_Display_Text/scale_example/code.py, CircuitPython_PyPaint/code.py, CircuitPython_Pyloton/pyloton.py, EInk_CircuitPython_Quickstart/27_tricolor_eink_shield_text/code.py, FunHouse_Fume_Extractor/code.py, MagTag/MagTag_Google_Calendar/authenticator.py, MatrixPortal_S3_Flight_Proximity_Tracker/code.py, Matrix_Bluetooth_Controlled_LED_Sign/code.py, PyPortal/PyPortal_Google_Calendar/authenticator/code.py, PyPortal/PyPortal_Titano_Weather_Station/code.py, TFT_FeatherWing_TSC2007_Demos/CircuitPython/code.py, TFT_Shield_TSC2007_Demos/CircuitPython/code.py
Update all the code I could find that needed .`show(...)` to be replaced with `.root_group = ...`
I also did a Google site search to find as many places as I could that needed this fix in the Guides text.
=> replace .show(x) with .root_group = x

STEMMA_TCRT1000/CircuitPython/code.py, STEMMA_TCRT1000/arduino_tcrt1000_demo/arduino_tcrt1000_demo.ino
Adding CP and Arduino examples for the STEMMA Reflective Photo Interrupt Sensor (TCRT1000)
=> adding example code for TCRT1000

PyPortal/PyPortal_Youtube/code.py
Updating from secrets.py to settings.toml
=> PyPortal_Youtube: get youtube token from settings.toml

PyPortal/PyPortal_Thingiverse/code.py
=> PyPortal_Thingiverse: update to settings.toml

PyPortal/PyPortal_LeagueLevel/code.py
=> PyPortal_LeagueLevel: update to settings.toml

PyPortal/PyPortal_Halloween_Countdown/code.py
=> PyPortal_Halloween_Countdown: update to settings.toml

PyPortal/Dashblock_API/code.py
=> Update Dashblock_API to settings.toml

PyPortal/pyportal_pet_planter/code.py
=> pyportal_pet_planter: update to settings.toml

PyPortal/PyPortal_LIFX_Controller/code.py
Updating project to use settings.toml
=> PyPortal_LIFX_Controller: get LIFX_TOKEN from settings.toml

Adafruit_IO_Power_Relay/code.py
=> Adafruit_IO_Power_Relay: update to settings.toml

PyPortal/PyPortal_Word_of_the_Day/code.py
=> PyPortal_Word_Of_the_Day: update to settings.toml

PyPortal/PyPortal_Quarantine_Clock/code.py
=> PyPortal_Quarantine_Clock: update to settings.toml

MEMENTO/Memento_IOT_Doorbell/code.py
This change is purely for readability.
The LED is disabled in the main loop, so re-enabling it in the main loop makes more sense; also added some spacing between steps to make the code a little more legible.
None.
Unable to test, since I don't have this hardware. Changes should not affect functionality in any way.
=> Readability improvements

I2C_Multiple_Same_Address/arduino/multi_bme280_ltc4316/multi_bme280_ltc4316.ino, I2C_Multiple_Same_Address/circuitpython/multi_bme280_ltc4316/code.py
Adds new code examples for using LTC4316 with multiple same address I2C devices.
=> Add LTC4316 examples

STEMMA_IR_Remote_Receiver_Examples/Arduino_STEMMA_IR_Remote_Receiver/Arduino_STEMMA_IR_Remote_Receiver.ino, STEMMA_IR_Remote_Receiver_Examples/CircuitPython/code.py, STEMMA_IR_Remote_Receiver_Examples/CircuitPython_ProductDemo/code.py
Adding CP example code, product demo code and Arduino code for the IR remote receiver
=> example code for ir remote receiver

PlayStation_BLE/PlayStation_ESP32_BLE_Gamepad.ino
first commit playstation esp32 controller code
=> first commit playstation esp32 controller code

ADG72x_Examples/CircuitPython_ADG728/code.py, BNO055_BMP280_BFF_Examples/BNO055_BMP280_BFF_Arduino_Demo/BNO055_BMP280_BFF_Arduino_Demo.ino, BNO055_BMP280_BFF_Examples/CircuitPython/code.py
adding circuitpython and arduino examples for BNO055 BMP280 BFF. also updating adg728 example to flip between two channels
=> add BNO055 and BMP280 BFF examples

PlayStation_BLE/PlayStation_ESP32_BLE_Gamepad.ino
=> added wifi timout

Macropad_Hotkeys/macros/zzz_blank.py
of the code were modified.**
The PR #1930 added a new file. As the PR was created before the introduction of SPDX headers, this single file breaks the CI/CD action to check for headers.
This PR addresses this issue and adds the header.
- **Describe any known limitations with your change.**
None.
=> Adjust SPDX header for recently merged file

PlayStation_BLE/PlayStation_ESP32_BLE_Gamepad.ino
reduced current draw in deep sleep from 1.8mA to 77µA by explicitly stopping WiFi before deep sleep.
=> deeper sleep via 'esp_wifi_stop()'

STEMMA_IR_Demodulator_Examples/Arduino_STEMMA_IR_Demodulator_Example/Arduino_STEMMA_IR_Demodulator_Example.ino, STEMMA_IR_Demodulator_Examples/CircuitPython/code.py
Adding STEMMA IR demodulator examples for CircuitPython and Arduino
=> Adding IR demodulator examples

Wearable_Time_Lapse_Camera/timelapse.py
=> Rewrote Wearable Time Lapse Camera script in python

USB_Host_BFF_Examples/Arduino_USB_Host_BFF_DeviceInfo/Arduino_USB_Host_BFF_DeviceInfo.ino, USB_Host_BFF_Examples/Arduino_USB_Host_BFF_HIDReport/Arduino_USB_Host_BFF_HIDReport.ino, USB_Host_BFF_Examples/CircuitPython_DeviceInfo/code.py, USB_Host_BFF_Examples/CircuitPython_HIDReport/code.py
Adding Arduino and CircuitPython USB Host BFF examples for device info and HID report
=> usb host bff examples

Wearable_Time_Lapse_Camera/timelapse.py, Wearable_Time_Lapse_Camera/timelapse.sh
Just some code comment updates.
=> Update Code Comments for Wearable Timelapse Camera Project

Soundboard_Scooter_Bike/code.py
updating pins to fix code for project https://learn.adafruit.com/soundboard-speaker-for-bikes-scooters/
=> update code.py for correct pins

QT_Py_CH552_Examples/Blink_QTPyCH552/Blink_QTPyCH552.ino, QT_Py_CH552_Examples/CapTouch_QTPyCH552/CapTouch_QTPyCH552.ino, QT_Py_CH552_Examples/I2C_AHT20_QTPyCH552/I2C_AHT20_QTPyCH552.ino, QT_Py_CH552_Examples/Neopixel_QTPyCH552/Neopixel_QTPyCH552.ino, QT_Py_CH552_Examples/analogIn_QTPyCH552/analogIn_QTPyCH552.ino
Adding examples for the QT Py CH552 learn guide. examples for led blink, analog in, capacitive touch, i2c with the AHT20 and neopixel swirl
=> CH552 examples

White_Noise_Rocket/code.py
update neopixel count per white noise rocket guide feedback
=> Fix code for white noise rocket guide

QT_Py_Media_Controller/code.py
Updating media controller code to use more press options and user definable variables at the top
=> updating media controller code

Factory_Tests/Pixel_Trinkey_FactoryTest/Pixel_Trinkey_FactoryTest.ino
factory test for the pixel trinkey
=> adding factory test for pixel trinkey

TRRS_Trinkey_Demos/CircuitPython_AT_Demo/code.py, TRRS_Trinkey_Demos/TRRS_Trinkey_AT_Demo/TRRS_Trinkey_AT_Demo.ino
Adding AT switch demos for the TRRS Trinkey
=> AT switch demos

Neo_Trinkey_Examples/Arduino_Digital_Input/Arduino_Digital_Input.ino, Neo_Trinkey_Examples/Arduino_DotStar/Arduino_DotStar.ino, Neo_Trinkey_Examples/Arduino_NeoPixel/Arduino_NeoPixel.ino, Neo_Trinkey_Examples/CircuitPython_Digital_Input/code.py, Neo_Trinkey_Examples/CircuitPython_DotStar/code.py, Neo_Trinkey_Examples/CircuitPython_NeoPixel/code.py
Adding basic examples for NeoPixel Trinkey guide
=> neopixel trinkey examples

TRRS_Trinkey_Demos/XAC_Joystick/XACsettings.py, TRRS_Trinkey_Demos/XAC_Joystick/boot.py, TRRS_Trinkey_Demos/XAC_Joystick/code.py, TRRS_Trinkey_Demos/XAC_Joystick/xac_gamepad.py
=> XAC joysticks first commit

USB_MIDI_Host_Messenger/USB_MIDI_Host_Messenger.ino
first commit of usb midi host messenger arduino feather rp2040 usb host
=> first commit usb midi host messenger arduino feather rp2040 usb host

.github/workflows/arduino_cron.yml, Factory_Tests/Feather_RP2040_Adalogger/Feather_RP2040_Adalogger.ino
Adding Feather RP2040 Adalogger factory test and rp2040 adalogger to CI
=> rp2040 adalogger factory test

Servo_Commander/code.py
=> first commit servo commander code

Magic_Band_Reader/code.py
updating the project codes neopixel count to fit the learn guide build per user feedback
=> updating neopixel count to fit learn guide build

STEMMA_IR_Transceiver_Examples/Arduino_STEMMA_IR_Transceiver/Arduino_STEMMA_IR_Transceiver.ino, STEMMA_IR_Transceiver_Examples/CircuitPython/code.py
Adding CP and Arduino examples for the IR transceiver guide
=> adding examples for the stemma ir transceiver

Grill_Thermometer_Dashboard/code.py
code for BLE/WiFi grill thermometer guide
=> grill dashboard code

Introducing_Trinket_M0/Trinket_SDCardList/code.py
Add the middle line between the first and last line in the example for setting up an SD Card. The first item is a '?' and the code crashes. On web page: https://learn.adafruit.com/adafruit-micro-sd-breakout-board-card-tutorial/circuitpython blakebr
.
.
for file in os.listdir(path):
if file == "?": continue
print(file, path + "/" + file)
=> Issue noted in Learn

PyPortal/PyPortal_Wheres_My_Friend/code.py
Removes specific name, uses project name in header instead!
=> Fix Wheres My Friend Project

Feather_ESP32-S2_TFT_Azure/code.py
Minor changes so code works with 2024 Feather ESP32-S2 TFT. Also needs to use SSL to connect to Azure. 
Previous version was no longer able to connect and would produce the following error.
```
Connecting to WiFi...
Connected to WiFi!
Year seems good, skipping set time.
Connecting to Azure IoT Central...
Traceback (most recent call last):
File "code.py", line 104, in <module>
File "adafruit_azureiot/iotcentral_device.py", line 163, in connect
File "adafruit_azureiot/device_registration.py", line 210, in register_device
File "adafruit_azureiot/device_registration.py", line 108, in connectto_mqtt
File "adafruit_minimqtt/adafruit_minimqtt.py", line 402, in connect
File "adafruit_minimqtt/adafruit_minimqtt.py", line 475, in _connect
File "adafruit_connection_manager.py", line 330, in …
```
=> Azure ESP32-S2 TFT SSL and MAX17048

.github/workflows/arduino_cron.yml, Factory_Tests/Adafruit_ESP32-C6_Feather_FactoryTest/Adafruit_ESP32-C6_Feather_FactoryTest.ino
adding factory test for C6 feather
=> factory test for C6 feather

Qualia/Qualia_S3_1D_Chomper_Game/code.py
Updates the import line to the correct module
=> fix entity import in 1d chomper

Factory_Tests/Qualia_ESP32S3_RGB666_FactoryTest/Qualia_ESP32S3_RGB666_FactoryTest.ino
demo for 3.7" rect display https://www.adafruit.com/product/5799
requested https://forums.adafruit.com/viewtopic.php?t=212612
@caternuson i cant find my 3.7" rectangular maybe if you can test it (or @BlitzCityDIY if you happen to have a 3.7" handy, i ganked your sushi conveyor!)
=> 3.7" 240x960 demo

MEMENTO/Memento_itsaSNAP_Capture_Cam/code.py
A new remote camera project using itsaSNAP and the Memento.
=> Project using the Memento and itsaSNAP

Feather_DVI_Arduino_Video_Synth/Feather_DVI_Arduino_Video_Synth/Feather_DVI_Arduino_Video_Synth.ino
PicoDVI library was updated. Testing if that fixed CI
=> adding back tests for picodvi

TinyPod/code.py
Adding tinypod code. uses esp32-s3 feather for ble and ano seesaw encoder
=> adding tinypod code

A4988_Examples/Arduino_A4988/Arduino_A4988.ino, A4988_Examples/CircuitPython_A4988/code.py
Example code for the A4988 in CircuitPython and Arduino
=> a4988 examples

IoT_Christmas_Lights_Switch/code.py
adding circuitpython code for the xmas light iot switch project
=> adding xmas light iot switch

Newxie_TFT_Examples/Newxie_Python_Multi_Pi/newxie_clock.py, Newxie_TFT_Examples/Newxie_Python_Multi_Pi/newxie_count.py
adding two demos for using four newxie displays together with raspberry pi
=> newxie multi display

Factory_Tests/Adafruit_Sparkle_Motion_Mini_FactoryTest/Adafruit_Sparkle_Motion_Mini_FactoryTest.ino, Sparkle_Motion_Mini_Examples/Arduino_I2S_SparkleMotionMini/Arduino_I2S_SparkleMotionMini.ino
factory test for the sparkle motion mini
=> sparkle mini factorytest

Sparkle_Motion_Examples/Arduino_I2S_SparkleMotion/Arduino_I2S_SparkleMotion.ino, Sparkle_Motion_Examples/Arduino_Sparkle_Motion_Multi_NeoPixels/Arduino_Sparkle_Motion_Multi_NeoPixels.ino, Sparkle_Motion_Examples/CircuitPython_Sparkle_Motion_Neopixel_Animation/code.py
A few examples adapted for the bigger sparkle motion
=> sparkle motion examples

Sparkle_Motion_Examples/Arduino_Sparkle_Motion_IR_Remote/Arduino_Sparkle_Motion_IR_Remote.ino, Sparkle_Motion_Examples/CircuitPython_Sparkle_Motion_IR_Remote/code.py
Examples for controlling a NeoPixel strip with an IR remote control
=> sparkle motion IR control neopixels examples

WipperSnapper_Offline/config.json
Adding folder for resource storage for Learn Guide "No-Code Offline Data Logger with WipperSnapper"
=> Add: WipperSnapper Offline Guide Resources

Metro/Metro_RP2350_Breakout/code.py
New Learn guide
CircuitPython code
=> Submit code for Metro RP2350 Breakout

Bluetooth_Lumon_Speaker/Bluetooth_Lumon_Speaker.ino, QT_Py/NeoPixel_Moon_Phase_Clock/code.py
CircuitPython code for moon phase clock and arduino code for bluetooth lumon speaker
=> adding moon phase clock & bluetooth speaker

USB_Host_BFF_Examples/Arduino_USB_Host_BFF_DeviceInfo/Arduino_USB_Host_BFF_DeviceInfo.ino
Adding back the esp32 test for usb host bff code (library was released yesterday). Adding a minor comment to the code to trigger Arduino CI
=> bring back esp32 test for usb host max breakout

WipperSnapper_Offline/config.json
This pull request updates the `config.json` file for the following guide: https://learn.adafruit.com/no-code-offline-data-logging-with-wippersnapper/usage
The new `config.json` file reflects a file that is automatically generated by the WipperSnapper Offline Beta 2 release.
=> Update - WS Offline Guide

Sparkle_Motion_Stick_Examples/Arduino_Sparkle_Motion_Stick_IR_Remote/Arduino_Sparkle_Motion_Stick_IR_Remote.ino
Adding IR remote Arduino example for the Sparkle Motion Stick
=> adding ir remote example

Mother_Of_All_Demos_Keyset/code.py
CircuitPython code for the mother of all demos keyset project
=> mother of all demos code

Adafruit_ESP32_Arduino_Demos/SerialESPPassthrough/SerialESPPassthrough.ino
tested on fruit jam (ESP32-C6 client)
=> fix functionality for RP2x hosts

TFT_Spirit_Board/esp32s3_s2_tft_featherwing_480x320/spirit_board.py, TFT_Spirit_Board/pyportal/spirit_board.py, TFT_Spirit_Board/pyportal_titano/spirit_board.py
updating a few references to deprecated class in docstrings. I searched other usage of deprecated
=> displayio api updates

LED_Matrix_Clock/code.py
new features for matrix clock project
* "blinking eyes" every 30 seconds
* scrolling text during alarm
* scrolling text to denote if alarm is enabled
=> updating matrix clock code

Wiz5500_Ethernet_Breakout/Arduino_Wiz5500_Breakout/Arduino_Wiz5500_Breakout.ino, Wiz5500_Ethernet_Breakout/CircuitPython_Wiz5500_Breakout/code.py
adding circuitpython and arduino examples for the wiz5500 ethernet breakout
=> ethernet breakout examples

Ideal_Diode_Examples/Arduino_Ideal_Diode_Monitor/Arduino_Ideal_Diode_Monitor.ino, Ideal_Diode_Examples/CircuitPython_Ideal_Diode_Monitor/code.py
circuitpython and arduino examples for the ideal diode breakout
=> adding ideal diode examples

ESP-NOW_basics/espnow_transceiver.py
esp-now basics guide transciever code
=> first commit esp-now basics

Raspberry_Pi_KittenTTS/code.py, Raspberry_Pi_KittenTTS/generate_forecast.py
Tested successfully on both Pi 4 and 5.
I looked into the huggingface hub and the KittenTTL initialization code a bit to try to find a way to make this be "latest" instead of hardcoded to a version. It does not appear to be possible at this time to me. I asked in the KittenTTS discord and will use that approach if it does turn out to be possible.
=> update to KittenTTS 0.2 model.

PCM5122_Examples/Arduino_PCM5122_HW_Mode/Arduino_PCM5122_HW_Mode.ino, PCM5122_Examples/CircuitPython_PCM5122_HW_Mode/code.py
hardware mode examples for cp and arduino
=> pcm5122 hardware mode
